### ISSUE TITLE
provisioning a new device is still showing raise/releasing MONGO alarms

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1007]
time=2021-03-23T10:29:55.926Z | lvl=DEBUG | corr=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | trans=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=smartcity | subsrv=/ | msg=Request for path [/iot/devices] from [localhost:18082] | comp=IoTAgent
time=2021-03-23T10:29:55.926Z | lvl=DEBUG | corr=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | trans=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=smartcity | subsrv=/ | msg=Body:

{
    "devices": [
        {
            "device_id": "AIQ_A464",
            "entity_name": "IAQ_MA001",
            "entity_type": "IAQ",
            "static_attributes": [
                {
                    "value": "36.71749, -4.4743",
                    "type": "geo:point",
                    "name": "location"
                },
                {
                    "name": "address",
                    "type": "String",
                    "value": "Facultad"
                }
            ],
            "protocol": "IoTA-UL"
        }
    ]
}

 | comp=IoTAgent
time=2021-03-23T10:29:55.927Z | lvl=DEBUG | corr=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | trans=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | op=IoTAgentNGSI.DeviceProvisioning | from=n/a | srv=smartcity | subsrv=/ | msg=Handling device provisioning request. | comp=IoTAgent
time=2021-03-23T10:29:55.928Z | lvl=DEBUG | corr=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | trans=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"smartcity","subservice":"/","type":"IAQ"} | comp=IoTAgent
time=2021-03-23T10:29:55.930Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type","apikey"]] not found: [{"service":"smartcity","subservice":"/","type":"IAQ"}] | comp=IoTAgent
time=2021-03-23T10:29:55.931Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.BidirectionalPlugin | from=n/a | srv=n/a | subsrv=n/a | msg=Extracting attribute list | comp=IoTAgent
time=2021-03-23T10:29:55.931Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.BidirectionalPlugin | from=n/a | srv=n/a | subsrv=n/a | msg=Sending bidirectionality subscriptions for device [AIQ_A464] | comp=IoTAgent
time=2021-03-23T10:29:55.931Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Registration | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for bindings for the function [deviceProvisioningHandler] and protocol [null] | comp=IoTAgent
time=2021-03-23T10:29:55.931Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Registration | from=n/a | srv=n/a | subsrv=n/a | msg=Binding found for function [deviceProvisioningHandler] and protocol [null] | comp=IoTAgent
time=2021-03-23T10:29:55.933Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=smartcity | subsrv=/ | msg=Looking for device with id [AIQ_A464]. | comp=IoTAgent
time=2021-03-23T10:29:55.938Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=smartcity | subsrv=/ | msg=Device [AIQ_A464] not found. | comp=IoTAgent
time=2021-03-23T10:29:55.939Z | lvl=ERROR | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Alarms | from=n/a | srv=n/a | subsrv=n/a | msg=Raising [MONGO-ALARM]: {"name":"DEVICE_NOT_FOUND","message":"No device was found with id:AIQ_A464","code":404} | comp=IoTAgent
time=2021-03-23T10:29:55.939Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"smartcity","subservice":"/","type":"IAQ"} | comp=IoTAgent
time=2021-03-23T10:29:55.942Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type","apikey"]] not found: [{"service":"smartcity","subservice":"/","type":"IAQ"}] | comp=IoTAgent
time=2021-03-23T10:29:55.943Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.DeviceService | from=n/a | srv=n/a | subsrv=n/a | msg=deviceData before merge with conf: {"id":"AIQ_A464","type":"IAQ","name":"IAQ_MA001","service":"smartcity","subservice":"/","staticAttributes":[{"value":"36.71749, -4.4743","type":"geo:point","name":"location"},{"name":"address","type":"String","value":"Facultad de Medicina"}],"protocol":"IoTA-UL","transport":"HTTP","internalId":null,"explicitAttrs":false,"subscriptions":[],"polling":true} | comp=IoTAgent
time=2021-03-23T10:29:55.943Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.DeviceService | from=n/a | srv=n/a | subsrv=n/a | msg=deviceData after merge with conf: {"id":"AIQ_A464","type":"IAQ","name":"IAQ_MA001","service":"smartcity","subservice":"/","active":null,"staticAttributes":[{"value":"36.71749, -4.4743","type":"geo:point","name":"location"},{"name":"address","type":"String","value":"Facultad de Medicina"}],"lazy":null,"commands":[],"protocol":"IoTA-UL","transport":"HTTP","internalId":null,"explicitAttrs":false,"subscriptions":[],"polling":true} | comp=IoTAgent
time=2021-03-23T10:29:55.944Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.DeviceService | from=n/a | srv=n/a | subsrv=n/a | msg=Registering device into NGSI Service:
{
    "id": "AIQ_A464",
    "type": "IAQ",
    "name": "IAQ_MA001",
    "service": "smartcity",
    "subservice": "/",
    "active": null,
    "staticAttributes": [
        {
            "value": "36.71749, -4.4743",
            "type": "geo:point",
            "name": "location"
        },
        {
            "name": "address",
            "type": "String",
            "value": "Facultad"
        }
    ],
    "lazy": null,
    "commands": [],
    "protocol": "IoTA-UL",
    "transport": "HTTP",
    "internalId": null,
    "explicitAttrs": false,
    "subscriptions": [],
    "polling": true
} | comp=IoTAgent
time=2021-03-23T10:29:55.944Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Registration | from=n/a | srv=n/a | subsrv=n/a | msg=Registration with Context Provider is not needed. Device without lazy atts or commands | comp=IoTAgent
time=2021-03-23T10:29:55.946Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Devices-v2 | from=n/a | srv=n/a | subsrv=n/a | msg=deviceData: {"id":"AIQ_A464","type":"IAQ","name":"IAQ_MA001","service":"smartcity","subservice":"/","active":null,"staticAttributes":[{"value":"36.71749, -4.4743","type":"geo:point","name":"location"},{"name":"address","type":"String","value":"Facultad de Medicina"}],"lazy":null,"commands":[],"protocol":"IoTA-UL","transport":"HTTP","internalId":null,"explicitAttrs":false,"subscriptions":[],"polling":true} | comp=IoTAgent
time=2021-03-23T10:29:55.946Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Devices-v2 | from=n/a | srv=n/a | subsrv=n/a | msg=config.timestamp undefined true | comp=IoTAgent
time=2021-03-23T10:29:55.950Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Devices-v2 | from=n/a | srv=n/a | subsrv=n/a | msg=Creating initial entity in the Context Broker:
 {
    "url": "http://iot-orion:1026/v2/entities?options=upsert",
    "method": "POST",
    "json": {
        "id": "IAQ_MA001",
        "type": "IAQ",
        "location": {
            "type": "geo:json",
            "value": {
                "type": "Point",
                "coordinates": [
                    36.71749,
                    -4.4743
                ]
            }
        },
        "address": {
            "type": "String",
            "value": "Facultad de Medicina"
        },
        "TimeInstant": {
            "type": "DateTime",
            "value": "2021-03-23T10:29:55.948Z"
        }
    },
    "headers": {
        "fiware-service": "smartcity",
        "fiware-servicepath": "/",
        "fiware-correlator": "dfe5a406-818e-4388-808f-46e894452c49"
    }
} | comp=IoTAgent
time=2021-03-23T10:29:55.951Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.RestUtils | from=n/a | srv=n/a | subsrv=n/a | msg=executeWithSecurity | comp=IoTAgent
time=2021-03-23T10:29:55.951Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["type"] with queryObj {"type":"IAQ"} | comp=IoTAgent
time=2021-03-23T10:29:55.955Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=smartcity | subsrv=/a | msg=Device group data found: {"commands":[],"staticAttributes":[],"lazy":[],"attributes":[],"internalAttributes":[],"_id":"60584888d434e17f675b761a","resource":"/iot/d","apikey":"xvp8pp1yrsexyaac92z1di3my","type":"IAQ","service":"smartcity","subservice":"/a","description":"ul-iaq","timestamp":true} | comp=IoTAgent
time=2021-03-23T10:29:55.955Z | lvl=ERROR | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Alarms | from=n/a | srv=n/a | subsrv=n/a | msg=Releasing [MONGO-ALARM] | comp=IoTAgent
time=2021-03-23T10:29:55.965Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.Devices-v2 | from=n/a | srv=n/a | subsrv=n/a | msg=Initial entity created successfully. | comp=IoTAgent
time=2021-03-23T10:29:55.966Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=smartcity | subsrv=/ | msg=Storing device with id [AIQ_A464] and type [IAQ] | comp=IoTAgent
time=2021-03-23T10:29:55.995Z | lvl=DEBUG | corr=dfe5a406-818e-4388-808f-46e894452c49 | trans=dfe5a406-818e-4388-808f-46e894452c49 | op=IoTAgentNGSI.DeviceProvisioning | from=n/a | srv=n/a | subsrv=n/a | msg=Device provisioning request succeeded | comp=IoTAgent
time=2021-03-23T10:29:55.996Z | lvl=DEBUG | corr=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | trans=a0e5b0c0-c43b-4339-a6a5-063d522b0912 | op=IoTAgentNGSI.DomainControl | from=n/a | srv=n/a | subsrv=n/a | msg=response-time: 71 | comp=IoTAgent

**Comment by fgalan** [comment]
PRs #1008 (fix) and PR #1009 (CNR)
