### ISSUE TITLE
Group command is not provisioned in device when use a different entity_type

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1011]
Given a Device Group with a command.

{"services":[{"_id":"605c4a1f9bf6772f44fadc1b","__v":1,"iotagent":"http://172.17.0.1:4061","apikey":"0pbjm5q950pfcrbs8e407ysfk","entity_type":"thing","service_path":"/","service":"smartcity","resource":"/iot/d","description":"UL2","protocol":"IoTA-UL","internal_attributes":[],"attributes":[],"lazy":[],"static_attributes":[],"commands":[{"name":"MiOtrocommand","type":"command","value":""}],"timestamp":true}],"count":1}

When a device is provisioned for that command using another "entity_type":

time=2021-03-30T09:23:44.417Z | lvl=DEBUG | corr=fae9e99e-c0e2-4c11-bb3c-e8ce034520a5 | trans=fae9e99e-c0e2-4c11-bb3c-e8ce034520a5 | op=IoTAgentNGSI.GenericMiddlewares | from=172.17.0.22 | srv=smartcity | subsrv=/ | msg=Body:

{
"devices": [
{
"device_id": "disp1",
"entity_name": "entity1",
"entity_type": "entityType1",
"protocol": "IoTA-UL",
"apikey": "0pbjm5q950pfcrbs8e407ysfk"
}
]
}

| comp=IoTAgent
time=2021-03-30T09:23:44.421Z | lvl=DEBUG | corr=fae9e99e-c0e2-4c11-bb3c-e8ce034520a5 | trans=fae9e99e-c0e2-4c11-bb3c-e8ce034520a5 | op=IoTAgentNGSI.DeviceProvisioning | from=172.17.0.22 | srv=smartcity | subsrv=/ | msg=Handling device provisioning request. | comp=IoTAgent
time=2021-03-30T09:23:44.423Z | lvl=DEBUG | corr=fae9e99e-c0e2-4c11-bb3c-e8ce034520a5 | trans=fae9e99e-c0e2-4c11-bb3c-e8ce034520a5 | op=IoTAgentNGSI.MongoDBGroupRegister | from=172.17.0.22 | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"smartcity","subservice":"/","type":"entityType1","apikey":"0pbjm5q950pfcrbs8e407ysfk"} | comp=IoTAgent
time=2021-03-30T09:23:44.426Z | lvl=DEBUG | corr=e4a38c52-8cd7-4004-858c-8538df98e49c | trans=e4a38c52-8cd7-4004-858c-8538df98e49c | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type","apikey"]] not found: [{"service":"smartcity","subservice":"/","type":"entityType1","apikey":"0pbjm5q950pfcrbs8e407ysfk"}] | comp=IoTAgent

Then group is not selected due to iota-node-lib is searching by type and apikey and then no group is found, loosing command definition. But searching only by apikeygroup matches and group command is properly provisioned.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1010
