### ISSUE TITLE
Not able to find a proper way to pass metadatas to update values method.

### ISSUE THREAD

**Issue by javieriturra** [telefonicaid/iotagent-node-lib#102]
Looking at: https://github.com/telefonicaid/iotagent-node-lib#iotagentlibupdate
Could you provide any example to pass metadatas over attribute values?

**Comment by dmoranj** [comment]
I'm not sure of what you want to accomplish here: inserting metadatas as part of the updated attribute is easy enough (as the `attributes ` parameter of the `update` function has the same sintax that would be used in the creation of the payload). So, you can add your metadatas in each of the attributes in the `attributes` array, and they will be sent to the Context Broker.

**Comment by dmoranj** [comment]
I assume the previous post answered your question. If that wasn't the case, please reopen.
