### ISSUE TITLE
Service is not coverted to lowercase

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#1023]
According to https://thinking-cities.readthedocs.io/en/master/multitenancy/index.html with regards to **service**:

> If uppercase characters are used, they are converted to lowercase.

It seems that IOTAs are not behaving this way and the service path in the MongoDB documents is stored case sensitive.

However, before addressing this issue, we should take into account backward compatibility aspects.

**Comment by fgalan** [comment]
It comes from issue https://github.com/telefonicaid/iotagent-json/issues/532

**Comment by AlvaroVega** [comment]
Maybe in 
https://github.com/telefonicaid/iotagent-node-lib/blob/6748fc9cedee6133d530e7fd37581236e8d369ec/lib/services/ngsi/ngsiUtils.js#L158

**Comment by fgalan** [comment]
> However, before addressing this issue, we should take into account backward compatibility aspects.

To know potentially existing devices/cgroups/whatever currently using uppercase in DB the following query can be useful:

```
db.devices.find({service: /[A-Z]/})
```

**Comment by AlvaroVega** [comment]
Maybe this other approach https://github.com/telefonicaid/iotagent-node-lib/pull/1024 ... and updating tests which expects subservice could be in uppercase?

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1024
