### ISSUE TITLE
jexl not working if is activaded at group level

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1027]
Possible bug / to be analyze:

at group level:
optional boolean value, to set expression language used to compute expressions, possible values are: legacy or jexl. When not set or wrongly set, legacy is used as default value.

at device level:
optional boolean value, to set expression language used to compute expressions, possible values are: legacy or jexl. When not set or wrongly set, legacy is used as default value.

defaultExpressionLanguage: the default expression language used to compute expressions, possible values are: legacy or jexl. When not set or wrongly set, legacy is used as default value.

IOTA_DEFAULT_EXPRESSION_LANGUAGE | defaultExpressionLanguage

Logis is handled by:
https://github.com/telefonicaid/iotagent-node-lib/blob/211670ae17fb27aa100e1d1e6a3e538c7e0be7c9/lib/plugins/expressionPlugin.js#L67-L84

If no is defined at device level should remains group level

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1029
