### ISSUE TITLE
Do not transform value using attribute type after apply expression JEXL 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1036]
Keep attribute value as expression plugin returns

Do not perform:
https://github.com/telefonicaid/iotagent-node-lib/blob/9557e7568f28ee5c35116d7213c41a8a25425897/lib/plugins/jexlParser.js#L129-L147

Introduced by https://github.com/telefonicaid/iotagent-node-lib/pull/800/

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1034/
