### ISSUE TITLE
Invalid entityId (null) as a result of multientity and expression plugin over entityName

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1039]
parser.applyExpression could return a nul, NaN, 0, or false value

EntityId should be valid (non Null, NaN, etc)

https://github.com/telefonicaid/iotagent-node-lib/blob/9557e7568f28ee5c35116d7213c41a8a25425897/lib/plugins/multiEntity.js#L231-L234

**Comment by AlvaroVega** [comment]
Until 2.15.0 iota-node-libreray was using legacy expression parser in multientity (was fixed in https://github.com/telefonicaid/iotagent-node-lib/pull/990) , so this issue happens since that version

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1038
