### ISSUE TITLE
Multientity plugin is applying expression without check if there is a valid context over apply the expression before

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1040]
To analize

Multientity plugin is applying expression without check if there is a valid context over apply the expression before

https://github.com/telefonicaid/iotagent-node-lib/blob/9557e7568f28ee5c35116d7213c41a8a25425897/lib/plugins/multiEntity.js#L231

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1041
