### ISSUE TITLE
explicitAttrs doesn't work for group provision

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-node-lib#1045]
In a device group provision, with explicitAttrs

```json
{
    "services": [
        {
            "apikey": "{{JSON_APIKEY}}",
            "entity_type": "device",
            "explicitAttrs": true,
            "attributes": [
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "Number"
                },
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "Number"
                }
            ],
            "protocol": [
                "IoTA-JSON"
            ]
        }
    ]
}
```

When you send an attribute not defined (e.g. "e"), it is delivered to Context Broker.
http://{{ENDPOINT_IOTA_JSON_HTTP}}/iot/json?i=dev2json&k={{JSON_APIKEY}}
```json
{
  "t": 35,
  "e": 34
}
```

Both attributes are present in the entity

However, this mechanism works properly in the device provision.

**Comment by fgalan** [comment]
Maybe related issue: https://github.com/telefonicaid/iotagent-node-lib/issues/1016

**Comment by fgalan** [comment]
After merging PR #1046 this issue could have been solved.
