### ISSUE TITLE
add functions to jexl transformations

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1052]
Current transformations are:
https://github.com/telefonicaid/iotagent-node-lib/blob/3bbc3c2c817d5f9913b2f74cc90b3b3dfd4cc955/lib/plugins/jexlParser.js#L38-L41

New requested transformations:

{
sumaarray: (arr) => arr.reduce((i,v)=>i+v),
length:(arr) => arr.length,
typeof: (val) => typeof val,
isarray:(arr) => Array.isArray(arr),
isnan: (val) => isNaN(val),
parseint: (val) => parseInt(val),
parsefloat: (val) => parseFloat(val),
toisodate: (val) => new Date(val).toISOString(),
tostring: (val) => val.toString(),
urlencode: (val) => encodeURI(val),
urldecode: (val) => decodeURI(val),
replacestr: (str, from, to) => str.replace(from,to),
replaceregexp: (str, reg, to) => str.replace(new RegExp(reg),to),
replaceallstr: (str, from, to) => str.replaceAll(from,to),
replaceallregexp: (str, reg, to) => str.replaceAll(new RegExp(reg),to),
split: (str,ch) => str.split(ch)
}

**Comment by fgalan** [comment]
This PR (very old :) https://github.com/telefonicaid/iotagent-node-lib/pull/688 shows some function that in that moment we thought were interesting to included. Maybe they are good candidates.

**Comment by AlvaroVega** [comment]
But his new PR is just for jexl, not for legacy like #688 was

**Comment by mrutid** [comment]
Including some more transformations (mapper and thmapper) mapping values to choices arrays:


{
sumaarray: (arr) => arr.reduce((i,v)=>i+v),
length:(arr) => arr.length,
typeof: (val) => typeof val,
isarray:(arr) => Array.isArray(arr),
isnan: (val) => isNaN(val),
parseint: (val) => parseInt(val),
parsefloat: (val) => parseFloat(val),
toisodate: (val) => new Date(val).toISOString(),
tostring: (val) => val.toString(),
urlencode: (val) => encodeURI(val),
urldecode: (val) => decodeURI(val),
replacestr: (str, from, to) => str.replace(from,to),
replaceregexp: (str, reg, to) => str.replace(new RegExp(reg),to),
replaceallstr: (str, from, to) => str.replaceAll(from,to),
replaceallregexp: (str, reg, to) => str.replaceAll(new RegExp(reg),to),
split: (str,ch) => str.split(ch),
mapper: (val, values, choices) => choices[values.findIndex((target)=>target==val)],
thmapper: (val,values,choices) => choices[values.reduce((acc,curr,i,arr) => acc?acc:
val<=curr?acc=i:acc=null,null)]
}

**Comment by mrutid** [comment]
> This PR (very old :) #688 shows some function that in that moment we thought were interesting to included. Maybe they are good candidates.

I think these are more advanced and specific  than the #688 I'm not missing anything at the moment... if you have anymore ideas I would happily add them.

**Comment by mrutid** [comment]
I think we should use this bulk signature and consider function-mappings as part of the agent configuration.
```
jexl.addTransforms({{}} map)
Adds multiple transforms from a supplied map of transform name to transform function.
```

**Comment by fgalan** [comment]
PR #1055

**Comment by fgalan** [comment]
> This PR (very old :) #688 shows some function that in that moment we thought were interesting to included. Maybe they are good candidates.

After the new bunch of functions for JEXL, I think the old PR #688 is no longer needed, so I'll close it.
