### ISSUE TITLE
apply jexl over a non valid context, allowing null/undefined values

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1053]
The following code should be removed or at least not executed by processExpressionAttributes
https://github.com/telefonicaid/iotagent-node-lib/blob/3bbc3c2c817d5f9913b2f74cc90b3b3dfd4cc955/lib/plugins/jexlParser.js#L145-L159

Maybe just not calling contextAvailable from:

https://github.com/telefonicaid/iotagent-node-lib/blob/3bbc3c2c817d5f9913b2f74cc90b3b3dfd4cc955/lib/plugins/expressionParser.js#L239-L245

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1054
