### ISSUE TITLE
Mistakes in the documentation of bidirectional example

### ISSUE THREAD

**Issue by danielvillalbamota** [telefonicaid/iotagent-node-lib#1065]
I have seen two issues in the [bidirectional](https://github.com/telefonicaid/iotagent-node-lib/blob/b23ae285cf2aba69e82866a233ca1d1a9980df4c/doc/advanced-topics.md#bidirectionality-plugin-bidirectional) example:

```
      "attributes": [
        {
          "name":"location",
          "type":"geo:point",
          "expression": "${latitude}, ${longitude}",
          "reverse": [
            {
              "object_id":"longitude",
              "type": "Text",
              "expression": "${trim(substr(@location, indexOf(@location, \",\") + 1, length(@location)))}"
            },
            {
              "object_id":"latitude",
              "type": "Text",
              "expression": "${trim(substr(@location, 0, indexOf(@location, \",\")))}"
            }
          ]
        }
      ],

```

First, the `"expression": "${latitude}, ${longitude}",` should include `@` before the attributes to put the values in the expression: `"expression": "${@latitude}, ${@longitude}",`.

Second, expressions inside the reverse option does not match with the format of the `location` attribute in the CB as it is transformed in a `geo:json` object and not the `geo:point` expected in the expression.

I can PR the first one, but I do not how to solve the second.

**Comment by danielvillalbamota** [comment]
I have sent a PR (https://github.com/telefonicaid/iotagent-node-lib/pull/1070)

**Comment by fgalan** [comment]
> I have sent a PR (#1070)

Does it cover only the first item and the issue should remain opened for the second? Or both are covered?

**Comment by danielvillalbamota** [comment]
With the note in parenthesis I also consider the second item covered, at least the way to avoid it.
