### ISSUE TITLE
Batch registration of devices with payload as file

### ISSUE THREAD

**Issue by Madhu-NEC** [telefonicaid/iotagent-node-lib#1075]
Does IOTAgent support batch registration of devices with payload as file?
For example, there is a csv file containing information of 1000 different devices. Now i want to register these 1000 devices in one go reading information from the file.

**Comment by AlvaroVega** [comment]
I guess you  know API for register a device supports register an array of devices:
https://thinking-cities.readthedocs.io/en/latest/device_api/index.html#register-your-iot-device

```
{
    "devices": [{
        "device_id": "device1",
          ....
         }, {
        "device_id": "device2",
        ....
         }, {
        "device_id": "device3",
         ....
         }
}
```

Then you need convert the CSV to that device array. for the payload

**Comment by Madhu-NEC** [comment]
Hi @fgalan , @AlvaroVega  ,
>I guess you know API for register a device supports register an array of devices:

Yes, an array of devices is supported for device registration. But I want to ask if we can support file as payload for device registration at IOTAgent end? 
For example, we can provide csv file containing details of devices as payload for device registration. Then the data will be prepared by IOTAgent itself from the csv file before executing device registration API to send the payload.

**Comment by fgalan** [comment]
I'd suggest to implement somekind of csv-to-array in your client to cover this kind of cases. From my point of view, it's not a good idea to overload the IOTA API with a new format (csv) when other pretty similar (array) already exists.

**Comment by Madhu-NEC** [comment]
Hi @fgalan ,
Thanks for the support. Closing the issue.
