### ISSUE TITLE
Discrepancy in request validation between update and create in device provisioning API.

### ISSUE THREAD

**Issue by MichelSc** [telefonicaid/iotagent-node-lib#1083]
I use version 2.16 of the iotagent-node-lib libary.

I provision a device with POST /iot/devices and update it with PUT /iot/devices/:device_id.

Request validation is more relaxed with post (create) than with put (update):
- additional properties for the device are accepted in create, not in update
- property 'internal_attributes' is accepted in create, not in update.

See files updateDevice.json and createDevice.json in lib/templates.

Bug or feature?

For me this a bug. I want to provision a device with some internal_attributes. This works OK. Then I want to update these internal_attributes with PUT /iot/devices. This is not possible. The request in invalidated. NOK

**Comment by AlvaroVega** [comment]
Maybe just related with https://github.com/telefonicaid/iotagent-node-lib/issues/1092

**Comment by fgalan** [comment]
> Maybe just related with #1092 ?

Let's see if PR #1096 also solves this issue

**Comment by fgalan** [comment]
@MichelSc after the merging of PR #1096, could you check if the issue has been solved or it remains, please? Thanks!

**Comment by MichelSc** [comment]
The solution of #1096 cannot be a solution for this issue. Both are related to the feature internalAttributes but this issue is the validation of an external request update while #1096 is about the update in mongo.

The fix for the present issue is I believe to modify https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/templates/updateDevice.json so as to make it consistent with https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/templates/createDevice.json.

**Comment by fgalan** [comment]
> The fix for the present issue is I believe to modify https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/templates/updateDevice.json so as to make it consistent with https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/templates/createDevice.json.

Maybe could you do to a pull request with the modification you propose, please?

**Comment by MichelSc** [comment]
Pull request created: https://github.com/telefonicaid/iotagent-node-lib/pull/1107

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-node-lib/pull/1107 has been merged.

Maybe this issue can be closed @MichelSc please? Thanks!

**Comment by MichelSc** [comment]
Issue can be closed.
