### ISSUE TITLE
InternalAttributes not updated in mongoDb

### ISSUE THREAD

**Issue by MichelSc** [telefonicaid/iotagent-node-lib#1092]
I use device.internalAttributes to store data related to my specific application.

When the device is registered, the internalAttributes is correctly stored in mongo: OK.

When the device is updated, the internalAttributes is lost in mongo:
- the old value is lost: NOK
- the new value is not stored: NOK

See file services/devices/deviceRegistryMongoDB.js, line 279, method update:
- internalAttributes is not copied from device parameter to data object: NOK
- copying it fix the problem

**Comment by fgalan** [comment]
@MichelSc after the merging of PR #1096, could you check if the issue has been solved or it remains, please? Thanks!

**Comment by MichelSc** [comment]
Code review ok (in master) but not tested, because not released in 2.17

**Comment by fgalan** [comment]
> Code review ok (in master) but not tested, because not released in 2.17

If you are using an existing IOTA (IOTA-UL, IOTA-JSON), you could use `:latest` docker container to test it (`:latest` use as dependency the master branch in iotagent-node-lib)

If you are using your own IOTA, you could set the dependency for the library to master branch (like this: https://github.com/telefonicaid/iotagent-ul/blob/master/package.json#L42)

**Comment by MichelSc** [comment]
Tested ok with "iotagent-node-lib": "git://github.com/telefonicaid/iotagent-node-lib.git#master"

**Comment by fgalan** [comment]
Thanks for the feedback!

Taking into account your positive report we are going to close the issue.
