### ISSUE TITLE
Wrong http error code when provisioning a device with wrong static attributes

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-node-lib#1109]
Trying to create a device through manager with wrong location (cordinates between "" are not valid for Context broker)

{
    "devices": [
        {
            "device_id": "PA-VILL-ALU-005",
            "entity_name": "PA-VILL-ALU-005",
            "entity_type": "StreetlightControlCabinet",
            "static_attributes": [
                {
                    "name": "location",
                    "type": "geo:json",
                    "value": {
                        "type": "Point",
                        "coordinates": [
                            "-0.038202",
                            "39.976196"
                        ]
                    }
                }
            ],
            "protocol": "IoTA-JSON"
        }
    ]
}

The manager responds with a 200 OK, but the device is not created.

The iota makes the following request/response to/from the context broker:

POST /v2/entities?options=upsert HTTP/1.1
fiware-service: demo
fiware-servicepath: /castellon
fiware-correlator: 4144375b-bd44-4f56-9c4d-3d1ef0d50826
host: 10.0.0.2:1026
accept: application/json
content-type: application/json
content-length: 224
Connection: close

{"id":"PA-VILL-ALU-005","type":"StreetlightControlCabinet","location":{"type":"geo:json","value":{"type":"Point","coordinates":["-0.038202","39.976196"]}},"TimeInstant":{"type":"DateTime","value":"2019-09-04T06:18:25.315Z"}}HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Wed, 04 Sep 2019 06:18:25 GMT
Content-Type: application/json
Content-Length: 1948
Connection: close
Fiware-Correlator: 4144375b-bd44-4f56-9c4d-3d1ef0d50826

{"error":"InternalError","description":"Database Error &#40;collection: orion-demo.entities - insert&#40;&#41;: { _id: { id: &quot;PA-VILL-ALU-005&quot;, type: &quot;StreetlightControlCabinet&quot;, servicePath: &quot;/castellon&quot; }, attrNames: [ &quot;location&quot;, &quot;TimeInstant&quot; ], attrs: { location: { type: &quot;geo:json&quot;, creDate: 1567577905, modDate: 1567577905, value: { type: &quot;Point&quot;, coordinates: [ &quot;-0.038202&quot;, &quot;39.976196&quot; ] }, mdNames: [] }, TimeInstant: { type: &quot;DateTime&quot;, creDate: 1567577905, modDate: 1567577905, value: 1567577905.0, mdNames: [] } }, creDate: 1567577905, modDate: 1567577905, location: { attrName: &quot;location&quot;, coords: { type: &quot;Point&quot;, coordinates: [ &quot;-0.038202&quot;, &quot;39.976196&quot; ] } }, lastCorrelator: &quot;4144375b-bd44-4f56-9c4d-3d1ef0d50826&quot; } - exception: OperationException: { index: 0, code: 16755, errmsg: &quot;Can&#39;t extract geo keys: { _id: { id: &quot;PA-VILL-ALU-005&quot;, type: &quot;StreetlightControlCabinet&quot;, servicePath: &quot;/castellon&quot; }, attrNames: [ &quot;location&quot;, &quot;Time...&quot;, op: { _id: { id: &quot;PA-VILL-ALU-005&quot;, type: &quot;StreetlightControlCabinet&quot;, servicePath: &quot;/castellon&quot; }, attrNames: [ &quot;location&quot;, &quot;TimeInstant&quot; ], attrs: { location: { type: &quot;geo:json&quot;, creDate: 1567577905, modDate: 1567577905, value: { type: &quot;Point&quot;, coordinates: [ &quot;-0.038202&quot;, &quot;39.976196&quot; ] }, mdNames: [] }, TimeInstant: { type: &quot;DateTime&quot;, creDate: 1567577905, modDate: 1567577905, value: 1567577905.0, mdNames: [] } }, creDate: 1567577905, modDate: 1567577905, location: { attrName: &quot;location&quot;, coords: { type: &quot;Point&quot;, coordinates: [ &quot;-0.038202&quot;, &quot;39.976196&quot; ] } }, lastCorrelator: &quot;4144375b-bd44-4f56-9c4d-3d1ef0d50826&quot; } }&#41;"}

Iota (and iotamanager) should respond with an error.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1110
