### ISSUE TITLE
multientity with attributes with same entity_name but different entity_type is using the same entity_name+entity_type

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1127]
`json
"attributes": [
      {
        "object_id": "LAFmax",
        "name": "LAFmax",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "NoiseLevelObserved"
      },
      {
        "object_id": "LAFmin",
        "name": "LAFmin",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "NoiseLevelObserved"
      },
      {
        "object_id": "LAT",
        "name": "LAeq",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "NoiseLevelObserved"
      },
      {
        "object_id": "solar",
        "name": "solarRadiation",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "prec",
        "name": "precipitation",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "stks",
        "name": "strikes",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "ws",
        "name": "windSpeed",
        "type": "Number",
        "expression": "${@ws * 3.6}",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "wd",
        "name": "windDirection",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "gws",
        "name": "gustWindSpeed",
        "type": "Number",
        "expression": "${@gws * 3.6}",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "airTemp",
        "name": "temperature",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "vPress",
        "name": "vaporPressure",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "aPress",
        "name": "atmosphericPressure",
        "type": "Number",
        "expression": "${@aPress * 10}",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "x",
        "name": "xOrientation",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "y",
        "name": "yOrientation",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "RH",
        "name": "relativeHumidity",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "HST",
        "name": "estimatedTemperature",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "WeatherObserved"
      },
      {
        "object_id": "PM2_5",
        "name": "PM25",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "AirQualityObserved"
      },
      {
        "object_id": "PM10",
        "name": "PM10",
        "type": "Number",
        "entity_name": "MC0202E20006800028",
        "entity_type": "AirQualityObserved"
      }
]
`

**Comment by mrutid** [comment]
Solves an special use case
https://github.com/telefonicaid/iotagent-node-lib/pull/1128

different attr_names

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1135
