### ISSUE TITLE
Wrong JEXL null mangement

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-node-lib#1132]
Instead of returning NULL, parse function returns undefined.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-node-lib/pull/1133

**Comment by fgalan** [comment]
> PR #1133

Reverted in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1137. Reopening issue

**Comment by fgalan** [comment]
> 
> 
> > PR #1133
> 
> Reverted in PR #1137. Reopening issue

Fixed again in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1138
