### ISSUE TITLE
update CB attributes using array of entities

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1142]
In order to remove this revert:
https://github.com/telefonicaid/iotagent-node-lib/pull/1141

So many tests from iotagent-json and iotagent-ul should be updated (CB mocks)

**Comment by fgalan** [comment]
Basically this issues consists on reverting the work done in PR #1141 (PR in this repo) then change all mocks expectations in IOTA-JSON and IOTA-UL (PRs in their respective repositories) to align with the new expectations.

Maybe IOTA Sigfox and IOTA LWM2M should be also be checked.

**Comment by AlvaroVega** [comment]
Done in plugins refactor
