### ISSUE TITLE
Accept JEXL Expressions for entity name in autoprovisioned devices

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-node-lib#1145]
When a Group is provisioned with a property:

"entity_name_exp" : "<JEXL expression>"

The Entity Name for the "not provisioned devices" should be the result of the expression instead of <type>:<id>

`
deviceData.type + conjunction + deviceData.id
`

The context for the JEXL expression should be the ID, TYPE, S, SS and avaliable measures.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1255
