### ISSUE TITLE
MQTT messages  posted to wrong API Key.

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-node-lib#1155]
I've discovered a Command/ServiceGroup issue similar to #1076. The following provisioning was made with **Ultralight** over MQTT but it shouldn't make a difference. 

1. Provision two service groups

```console
curl -s -o /dev/null -X POST  \
  "http://iot-agent:$IOTA_NORTH_PORT/iot/services" \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "1068318794",
     "cbroker":     "'"http://orion:$ORION_PORT"'",
     "entity_type": "Motion",
     "resource":    "",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "MQTT",
     "timezone":    "Europe/Berlin",
     "attributes": [
        {"object_id": "c", "name":"count", "type":"Integer"},
        {"object_id": "t", "name": "TimeInstant", "type":"DateTime"}
      ],
      "static_attributes": [
          {"name": "category", "type":"Text", "value": ["sensor"]},
          {"name": "controlledProperty", "type": "Text", "value": "motion"},
          {"name": "function", "type": "Text", "value":["sensing"]},
          {"name": "supportedProtocol", "type": "Text", "value": ["ul20"]},
          {"name": "supportedUnits", "type": "Text", "value": "C62"}
      ]
   },
   {
     "apikey":      "3020035",
     "cbroker":     "'"http://orion:$ORION_PORT"'",
     "entity_type": "Bell",
     "resource":    "",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "MQTT",
     "timezone":    "Europe/Berlin",
     "commands": [ 
        {
          "name": "ring",
          "type": "command"
        }
      ],
      "static_attributes": [
          {"name": "category", "type":"Text", "value": ["actuator"]},
          {"name": "controlledProperty", "type": "Text", "value": "noiseLevel"},
          {"name": "function", "type": "Text", "value":["onOff"]},
          {"name": "supportedProtocol", "type": "Text", "value": ["ul20"]}
      ]
   }
 ]
}'
```

2. Provision  an actuator and a sensor based on entity `type` using the two service groups.

```console
curl -s -o /dev/null -X POST \
  "http://iot-agent:$IOTA_NORTH_PORT/iot/devices" \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "transport":   "MQTT",
     "static_attributes": [
         {"name": "refStore", "type": "Relationship","value": "urn:ngsi-ld:Store:001"}
     ]
   },
   {
      "device_id": "bell001",
      "entity_name": "urn:ngsi-ld:Bell:001",
      "entity_type": "Bell",
      "transport":   "MQTT",
      "static_attributes": [
          {"name": "refStore", "type": "Relationship","value": "urn:ngsi-ld:Store:001"}
      ]
    }
  ]
}
'
```

3. Actuate the bell:

```console
curl -L -X POST 'http://localhost:4041/v2/op/update' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
--data-raw '{
    "actionType": "update",
    "entities": [
        {
            "type": "Bell",
            "id": "urn:ngsi-ld:Bell:001",
            "ring" : {
                "type": "command",
                "value": ""
            }
        }
    ]
}'
```

**Expected:** Message is posted to   `mqtt://mosquitto/3020035/bell001/cmd`  i.e. the API Key for the bell
**Actual Result:**   Message is posted to  `mqtt://mosquitto/1068318794/bell001/cmd` using the API Key for the motion sensor

It looks like the APIKey is being retrieved from the first persisted record rather than being merged properly based on `type`

**Comment by AlvaroVega** [comment]
I'm got something different when I tried to execute the same sequence: device is not found:

time=2021-11-25T15:00:13.074Z | lvl=DEBUG | corr=78bf220d-c1a9-4d24-944c-56a2f350302b | trans=78bf220d-c1a9-4d24-944c-56a2f350302b | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=openiot | subsrv=/ | msg=Request for path [/v2/op/update] from [localhost:4061] | comp=IoTAgent
time=2021-11-25T15:00:13.075Z | lvl=DEBUG | corr=78bf220d-c1a9-4d24-944c-56a2f350302b | trans=78bf220d-c1a9-4d24-944c-56a2f350302b | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=openiot | subsrv=/ | msg=Body:

{
    "actionType": "update",
    "entities": [
        {
            "type": "Bell",
            "id": "urn:ngsi-ld:Bell:001",
            "ring": {
                "type": "command",
                "value": ""
            }
        }
    ]
}

 | comp=IoTAgent
time=2021-11-25T15:00:13.078Z | lvl=DEBUG | corr=78bf220d-c1a9-4d24-944c-56a2f350302b | trans=78bf220d-c1a9-4d24-944c-56a2f350302b | op=IoTAgentNGSI.ContextServer-v2 | from=n/a | srv=openiot | subsrv=/ | msg=Handling v2 update from [localhost:4061] | comp=IoTAgent
time=2021-11-25T15:00:13.078Z | lvl=DEBUG | corr=78bf220d-c1a9-4d24-944c-56a2f350302b | trans=78bf220d-c1a9-4d24-944c-56a2f350302b | op=IoTAgentNGSI.ContextServer-v2 | from=n/a | srv=openiot | subsrv=/ | msg={
    "actionType": "update",
    "entities": [
        {
            "type": "Bell",
            "id": "urn:ngsi-ld:Bell:001",
            "ring": {
                "type": "command",
                "value": ""
            }
        }
    ]
} | comp=IoTAgent
time=2021-11-25T15:00:13.079Z | lvl=DEBUG | corr=78bf220d-c1a9-4d24-944c-56a2f350302b | trans=78bf220d-c1a9-4d24-944c-56a2f350302b | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=openiot | subsrv=/ | msg=Looking for device with name [urn:ngsi-ld:Bell:001]. | comp=IoTAgent
time=2021-11-25T15:00:13.086Z | lvl=DEBUG | corr=d9eccc53-876e-4b3c-b5a6-b869cf74dd43 | trans=d9eccc53-876e-4b3c-b5a6-b869cf74dd43 | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=openiot | subsrv=/ | msg=Device [urn:ngsi-ld:Bell:001] not found. | comp=IoTAgent
time=2021-11-25T15:00:13.087Z | lvl=ERROR | corr=d9eccc53-876e-4b3c-b5a6-b869cf74dd43 | trans=d9eccc53-876e-4b3c-b5a6-b869cf74dd43 | op=IoTAgentNGSI.Alarms | from=n/a | srv=n/a | subsrv=n/a | msg=Raising [MONGO-ALARM]: {"name":"DEVICE_NOT_FOUND","message":"No device was found with id:urn:ngsi-ld:Bell:001","code":404} | comp=IoTAgent
time=2021-11-25T15:00:13.087Z | lvl=DEBUG | corr=d9eccc53-876e-4b3c-b5a6-b869cf74dd43 | trans=d9eccc53-876e-4b3c-b5a6-b869cf74dd43 | op=IoTAgentNGSI.ContextServer-v2 | from=n/a | srv=n/a | subsrv=n/a | msg=There was an error handling the update action: {"name":"DEVICE_NOT_FOUND","message":"No device was found with id:urn:ngsi-ld:Bell:001","code":404}. | comp=IoTAgent
time=2021-11-25T15:00:13.087Z | lvl=DEBUG | corr=d9eccc53-876e-4b3c-b5a6-b869cf74dd43 | trans=d9eccc53-876e-4b3c-b5a6-b869cf74dd43 | op=IoTAgentNGSI.ContextServer-v2 | from=n/a | srv=n/a | subsrv=n/a | msg=Update NGSIv2 error [DEVICE_NOT_FOUND] handing request: No device was found with id:urn:ngsi-ld:Bell:001 | comp=IoTAgent
time=2021-11-25T15:00:13.089Z | lvl=DEBUG | corr=78bf220d-c1a9-4d24-944c-56a2f350302b | trans=78bf220d-c1a9-4d24-944c-56a2f350302b | op=IoTAgentNGSI.DomainControl | from=n/a | srv=openiot | subsrv=/ | msg=response-time: 30 | comp=IoTAgent

**Comment by AlvaroVega** [comment]
I've executed the following secuence (equivalent yours, over iotagent-ul and contextbroker) but I've got other result:

curl -i -X POST http://localhost:4061/iot/services \
  -H 'content-type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "1068318794",
     "entity_type": "motion",
     "resource":    "",
     "protocol":    "pdi-iota-ultralight",
     "transport":   "mqtt",
     "timezone":    "europe/berlin",
     "attributes": [
        {"object_id": "c", "name":"count", "type":"integer"},
        {"object_id": "t", "name": "timeinstant", "type":"datetime"}
      ],
      "static_attributes": [
          {"name": "category", "type":"text", "value": ["sensor"]},
          {"name": "controlledproperty", "type": "text", "value": "motion"},
          {"name": "function", "type": "text", "value":["sensing"]},
          {"name": "supportedprotocol", "type": "text", "value": ["ul20"]},
          {"name": "supportedunits", "type": "text", "value": "c62"}
      ]
   },
   {
     "apikey":      "3020035",
     "entity_type": "bell",
     "resource":    "",
     "protocol":    "pdi-iota-ultralight",
     "transport":   "mqtt",
     "timezone":    "europe/berlin",
     "commands": [ 
        {
          "name": "ring",
          "type": "command"
        }
      ],
      "static_attributes": [
          {"name": "category", "type":"text", "value": ["actuator"]},
          {"name": "controlledproperty", "type": "text", "value": "noiselevel"},
          {"name": "function", "type": "text", "value":["onoff"]},
          {"name": "supportedprotocol", "type": "text", "value": ["ul20"]}
      ]
   }
 ]
}'

curl -i -X POST http://localhost:4061/iot/devices \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "transport":   "MQTT",
     "static_attributes": [
         {"name": "refStore", "type": "Relationship","value": "urn:ngsi-ld:Store:001"}
     ]
   },
   {
      "device_id": "bell001",
      "entity_name": "urn:ngsi-ld:Bell:001",
      "entity_type": "Bell",
      "transport":   "MQTT",
      "static_attributes": [
          {"name": "refStore", "type": "Relationship","value": "urn:ngsi-ld:Store:001"}
      ]
    }
  ]
}
'

curl -i -X POST http://localhost:10026/v2/op/update \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
--data-raw '{
    "actionType": "update",
    "entities": [
        {
            "type": "Bell",
            "id": "urn:ngsi-ld:Bell:001",
            "ring" : {
                "type": "command",
                "value": ""
            }
        }
    ]
}'

HTTP/1.1 422 Unprocessable Entity
Connection: Keep-Alive
Content-Length: 109
Content-Type: application/json
Fiware-Correlator: b73813f8-4e04-11ec-8f10-0242ac110010
Date: Thu, 25 Nov 2021 15:31:10 GMT

{"error":"Unprocessable","description":"one or more of the attributes in the request do not exist: [ ring ]"}

**Comment by AlvaroVega** [comment]
@jason-fox  with the help of @fgalan we found that `entity_type` in service group is "bell" but `entity_type` of devie is "Bell". What do you really mean?

**Comment by jason-fox** [comment]
Mine is consistently  `Bell` and `Motion` I hope.

**Comment by AlvaroVega** [comment]
One of the times is looking with proper params:
time=2021-11-25T15:59:02.742Z | lvl=DEBUG | corr=440b7f31-5b10-4469-9a48-ffe299d492b1 | trans=440b7f31-5b10-4469-9a48-ffe299d492b1 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"openiot2","subservice":"/","type":"Bell"} | comp=IoTAgent

but other no:
ime=2021-11-25T15:59:02.749Z | lvl=DEBUG | corr=440b7f31-5b10-4469-9a48-ffe299d492b1 | trans=440b7f31-5b10-4469-9a48-ffe299d492b1 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"openiot2","subservice":"/"} | comp=IoTAgent

So fix is possible.

**Comment by AlvaroVega** [comment]
These are the PRs about to fix this issue: 
https://github.com/telefonicaid/iotagent-json/pull/604
https://github.com/telefonicaid/iotagent-ul/pull/521
https://github.com/telefonicaid/iotagent-node-lib/pull/1156

**Comment by fgalan** [comment]
> These PRs are the fix for this issue: [telefonicaid/iotagent-json#604](https://github.com/telefonicaid/iotagent-json/pull/604) [telefonicaid/iotagent-ul#521](https://github.com/telefonicaid/iotagent-ul/pull/521) #1156

All PRs has been merged.

@jason-fox could you test again in order to see if it has been solved, please?
