### ISSUE TITLE
Refactor entities-NGSI-v2.js module

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-node-lib#1166]
A profound refactor of the module is needed, starting with **sendUpdateValueNgsi2** method. 

Currently there are too much branching due to plugin application (mainly multi-entity) which could be addressed in an uniform way. For example everything could be considered "multientity" and use just the bulk method of the NGSI API.

The plugin architecture should be revised also: Name Mapping, Expression and Multi-entity plugin are not optional or pluggable. If we consider their business logic from the beginning in an integrated way many of the current complexity will disappear (waterfalling synchronous methods and decorating shared objects to later on remove decorations seems weird). 

A better world is possible. 

This may apply also to the brother module: entities-NGSI-LD.js

**Comment by AlvaroVega** [comment]
Done in https://github.com/telefonicaid/iotagent-node-lib/pull/1314
