### ISSUE TITLE
JEXL expression for conditional propagation of measures

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#1179]
Currently we have `explictAttr` which allows a "all or nothing" propagation of measures.

It would be great to have more control on this, so a per-attribute JEXL expression can be defined for non-explicit attributes. If the expression evaluates to `true` the attribute is propagated, otherwise it isn't (we can also do it the other way arround: if the exprassion evaluate to `false` the attribute is not propagated, otherwise it is).

**Comment by AlvaroVega** [comment]
related https://github.com/telefonicaid/iotagent-node-lib/pull/1157

**Comment by fgalan** [comment]
Alternatively, instead of having a per-attribute expression with a true/false result, we can have a per-group/per-device expression to specify an array of attributes to be excluded.

**Comment by mrutid** [comment]
Finally.

We are going to extend the possible values of _explicitAttrs_, in this way we have got the following cases:

- _explicitAttrs=false_: every measure will be propagated to NGSI interface (no changes)

- _explicitAttrs=true_: just measures defined in active, static (plus conditionally TimeInstant) will be propagated to NGSI interface (no changes)

- _explicitAttrs="['attr1','atr2']"_: just measures defined in JSON/JEXL array will be will be propagated to NGSI interface (BASIC CASE of new feature)

- _explicitAttrs="JEXL EXPRESION:BOOL/ARRAY"_:  just measures returned in JSON/JEXL array (or  base case if boolean) will be will be propagated to NGSI interface (new feature)

**Comment by AlvaroVega** [comment]
but how convert "['attr1','atr2']" to array of string ?

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-node-lib/pull/1180
