### ISSUE TITLE
refactor plugins

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1195]
Current implementation of plugins is too complex, inefficient and hard to maintain.
Feature performed for plugins could be implemented in a non middleware way

**Comment by fgalan** [comment]
Related with issue #1166 (maybe that issue can be considered part of this Epic)

**Comment by AlvaroVega** [comment]
The following analysis where done:
/lib/services/ngsi/entitiesNGSIv2.js
   sendUpdateValueNGSIv2
    CB request should be performed in a batch, not for just one entity
    This code shoud be a loop for eatch attribute checking all configuracion option and applying it to compose an array of enttities. And appying multientity, expressions and alias in that point.


- atribute alias plugin: to be removed
   object_id: must the mandatory and unique
    name: must the the same of object_id by default

- expresions plugin: to be removed
   legacy languate should be removed
     

- context for jexl should be created and be the same for all places.  Context must be statics + measure + device/group config

- timestamp should not be a plugin

- Tests: CB mocks should be updated since batch (array of entities) are expected to be updates to CB (currently most of the tests are using single entities)

- Bidirecional plugin: must be kept
