### ISSUE TITLE
multientity just with entity_type but not entity_name

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1220]
Used in attributes defined at  device level  -> entity_name shoud be current entity_name
Used in attributes defined at  group level -> entity_name shoujld be expected default entity_name (related` https://github.com/telefonicaid/iotagent-node-lib/issues/1222)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/issues/1220
