### ISSUE TITLE
add `entity_name` with expression to group

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1222]
Actually entity_name is derived from: "device.type : device.id" (i.e. for autoprovision)
https://github.com/telefonicaid/iotagent-node-lib/blob/4741f7bc43ed5f2c3050d054e963ca7a59c07d6b/lib/services/devices/deviceService.js#L289
We need a new field in group to set what will be the entity_name that we want later in base an expression.

**Comment by chicco785** [comment]
As of today the trick to solve this, is using the multi entity, where the entity name can be defined using an expression.
Probably the code there can re-used to tackle this also at the group level.

**Comment by mapedraza** [comment]
Thanks for so much for the answer @chicco785. What you are proposing is true, expressions can be used in combination with multientity plugin to have a custom entity name on "secondary" entities, but there is no way to apply an expression for the "main" entity, so, that is the reason of this issue.

**Comment by AlvaroVega** [comment]
related and maybe the same: https://github.com/telefonicaid/iotagent-node-lib/issues/1145

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1255
