### ISSUE TITLE
Fix explicitAttrs documentation

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1226]
ExplicitAttrs documentation like 
https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/advanced-topics.md#explicitly-defined-attributes-explicitattrs
is refering all time to measures, but really explicitAttrs is implemented taking into acount just attribute names (not object_id). We
should documentation in this sense.

Maybe related https://github.com/telefonicaid/iotagent-node-lib/issues/1169

Implementation
https://github.com/telefonicaid/iotagent-node-lib/blob/151c205456783a8217c6ae1b97ed7f7eca75d80b/lib/services/ngsi/entities-NGSI-v2.js#L335

**Comment by fgalan** [comment]
Should this issue be closed after merging PR https://github.com/telefonicaid/iotagent-node-lib/pull/1227 ?
