### ISSUE TITLE
IoT Agent GET request blocked by CORS policy

### ISSUE THREAD

**Issue by johncaipa** [telefonicaid/iotagent-node-lib#1230]
Hi, I am testing an example from the FIWARE tutorials where the [IoT Agent](https://github.com/FIWARE/tutorials.Time-Series-Data) is used from docker, I am trying to GET information about the services and devices provided from an external application in nodejs, and I get the following error messages, the GET request work from postman, could you tell me what the problem could be, or how should I enable CORS in the IoT Agent? thanks
![WhatsApp Image 2022-04-11 at 7 25 38 PM](https://user-images.githubusercontent.com/31298276/162856299-4e7247c3-4231-449a-a2d4-6743c61959b8.jpeg)
I don't know if I'm doing something wrong, I didn't find information about it in the documentation

**Comment by fgalan** [comment]
Maybe this issue has been closed because you have found the solution?

In that case, it would be great if you could comment how did you solve it at the end :)
