### ISSUE TITLE
explicitAttrs when is []

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1235]
given a device with:
```
explicitAttrs : object?['status']:[]
```
and an attribute like:

Protocol parameter | Device attribute | Type | Expression | Entity Type | Entity Name
-- | -- | -- | -- | -- | --
fake1 | status | Text | object.a?object.a:null

sending a measure:
```
curl -i -X POST 'http://localhost:7897/iot/json?i=disp1&k=6idn7z9cba3o57tgoascazdwd' -d '{ "fake1": "OK", "object3": { "a": "3"}}' -H 'content-type: application/json'
```
Should not update with null status

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1236
