### ISSUE TITLE
apply expressions to pull comands

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1263]
Currently expressions are only applied to push commands:
https://github.com/telefonicaid/iotagent-json/blob/2c7653513f180fc51728f1b327a98108a0031133/lib/commandHandler.js#L72-L75

Poll commands are registered in:
lib/services/northBound/contextServerUtils.js
https://github.com/telefonicaid/iotagent-node-lib/blob/d612742b0fe656786089345b981f8ab602b6dc3f/lib/services/northBound/contextServerUtils.js#L114-L116

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1256
