### ISSUE TITLE
Some tests fail ocassionally

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-node-lib#128]
The folowing test fails ocasionally:
´´´
NOTE: ACTUAL 0, EXPECTED -1

 1) Device provisioning API: List provisioned devices When a request for listing all the devices with a offset of 3 arrives should skip the first 3 devices:
      
      actual expected
      
      -10
      
      at Assertion.prop.(anonymous function) (/Users/mru/github/iotagent-node-lib/node_modules/should/lib/should.js:61:14)
      at Request._callback (/Users/mru/github/iotagent-node-lib/test/unit/listProvisionedDevices-test.js:272:91)
      at Request.self.callback (/Users/mru/github/iotagent-node-lib/node_modules/request/request.js:123:22)
´´´

**Comment by mrutid** [comment]
It fails about 20% of executions, at least on Mongo 2.4.8 and 2.4.12.

Alternative Output found just in 2.4.12:

**Comment by dmoranj** [comment]
We are going to execute all the tests 10 times in the versions with detected errors.

Test runs:
- [ ] 2.4.8
- [ ] 2.4.12
- [ ] 2.6.5
- [ ] 2.6.10
- [ ] 3.0.6 (latest)

**Comment by dmoranj** [comment]
It was not a problem with MongoDB, really. The problem was in how the test created the devices:
```
                async.times(10, createDeviceRequest, function(error, results) {
                    done();
                });
```
The test works on the hypothesis that all the devices are created sequentially. But `times` is not guaranteed to be sequential; it just happens to be in most cases, if the computer is fast enough or has a very low load. The function `timeSeries` on the other hand, provides the serialized times function expected by the test.
