### ISSUE TITLE
Wrong management of default entity_name at multientity with JEXL

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-node-lib#1292]
When a default entity name ("type:device_id") or any "wrong JEXL expression" literal is used as entity name, an exception is raised. All the following will fail when a measure is received:

 "attributes" : [ 
        {
            "name" : "a",
            "type" : "Number",
            "entity_name" : "type:deviceid",
            "entity_type" : "myType"
        },
        {
            "name" : "b",
            "type" : "Number",
             "entity_type" : "myType"
        }
    ]

Wrong JEXL expression should behave same as <null> result

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1293
