### ISSUE TITLE
reuse a previous jexl transformation in multientity

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1305]
Using JEXL for entity_name in multientity measures get transformed value, but not for expression value.
And there is not option to use a previous value of an JEXL

**Comment by AlvaroVega** [comment]
i.e. a device with a multientity with an entity_name based in a previous jexl transformation: 
`json
{"device_id":"disp1","apikey":"nn7tc5xxlup2tv1yglryuoepr","service":"smartcity","service_path":"/test","entity_name":"thing:disp1","entity_type":"thing","timestamp":true,"polling":true,"transport":"HTTP","attributes":[{"object_id":"temp","name":"temperature","type":"Number","expression":"temp*10"},{"object_id":"status","name":"status","type":"Text","expression":"(temp > 90) || (temp < 10) ? 'ALARMA' : 'OK'"},{"object_id":"vol","name":"vol","type":"Text","expression":"temperature"},{"object_id":"r","name":"r","type":"Text","expression":"\"OK\"","entity_name":"id + temperature","entity_type":"thing"}],"commands":[],"static_attributes":[],"protocol":"IoTA-JSON","explicitAttrs":false}
`

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1370

Documentation pending (CC: @mapedraza )

**Comment by fgalan** [comment]
> Documentation pending (CC: @mapedraza )

Moved to issue #1372
