### ISSUE TITLE
remove autocast feature

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1323]
Autocast feature is currently doing unexpected and unwanted transformations which could be done by jexl in a controlled way, so it must be fully removed.

Maybe related with https://github.com/telefonicaid/iotagent-node-lib/issues/1037

https://github.com/telefonicaid/iotagent-node-lib/blob/9dc0657952ad1b9879a79afc8bd54134f9099957/lib/services/ngsi/ngsiUtils.js#L98-L134

**Comment by AlvaroVega** [comment]
Alternativally autocast could be reimplemented with just:
```
try {
value = JSON.parse(value)
} catch () {
 keep value as 
}
```

**Comment by mrutid** [comment]
We are losing the autocast for the case: 
1->true
Which still avaliable via JEXL explicit casting.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1324
