### ISSUE TITLE
Issue of IoT-Agent integration with Scorpio Broker

### ISSUE THREAD

**Issue by MayankSingh-NEC** [telefonicaid/iotagent-node-lib#1325]
As reported in iotagent- json [issue 678](https://github.com/telefonicaid/iotagent-json/issues/678) and iotagent- ul [issue 538](https://github.com/telefonicaid/iotagent-ul/issues/538), [issue 573]( https://github.com/telefonicaid/iotagent-ul/issues/573) there is an issue in iotagent while integration with scorpio broker which I found to be related to node lib.

**Comment by fgalan** [comment]
Just to know... what the NGSI-LD spec says about case sensitiveness in `service`?

CC: @jason-fox

**Comment by mapedraza** [comment]
After closing https://github.com/telefonicaid/iotagent-ul/issues/573

I assume this issue can be closed too, right?

**Comment by jason-fox** [comment]
I have tested SCORPIO=3.0.11 with ULTRALIGHT=2.0.0 and actuations are working fine for me.
