### ISSUE TITLE
allow use all measure values for entityName expression in a groupconfiguration

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1334]
related PR: https://github.com/telefonicaid/iotagent-node-lib/pull/1255

Performed by:
https://github.com/telefonicaid/iotagent-node-lib/blob/531a1f8dfe874c5d93b108a7c791a7c70683fa42/lib/services/devices/deviceService.js#L293-L309

Currently only allow use service, subservice, id type and static attrs

**Comment by AlvaroVega** [comment]
But an autoprovisioned devices are performing these steps:
- Creating initial entity in CB
- Updating  entity with measure values

**Comment by AlvaroVega** [comment]
Related issue https://github.com/telefonicaid/iotagent-node-lib/pull/1111

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1389
