### ISSUE TITLE
 add skipValue to each attribute with expression

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1353]
SImplify explictAttrs to be only boolean ?
add to each attribute with expression a skipValue to allow not propagate attribute is as a result of expression result is skipValue

This way all logic from explicAttrs when is an expression will be translated into each attribute

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1364
