### ISSUE TITLE
Add new JEXL transformation: hextostring

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-node-lib#1367]
hextostring: (val) => new TextDecoder().decode(new Uint8Array(val.match(/.{1,2}/g).map(byte => parseInt(byte, 16))))

So: 

"706174617461"|hextostring => "patata"

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1368
