### ISSUE TITLE
static attributes (and other configuration flags)  in groups and autoprovision devices

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1377]
Static attributes in groups are copied to autoprovision device data and before modifications of attribute static are not progression to entity.

**Comment by AlvaroVega** [comment]
The reason of thtat is static_attributes are in this array:

https://github.com/telefonicaid/iotagent-json/blob/48a9fbc071c5fec05fe9241eb18d8509c800a637/lib/iotaUtils.js#L239

**Comment by AlvaroVega** [comment]
Other configuration flags like timestamp, expressionLanguage, etc are just copied form group to new autoprovisioned device and futher modifications of group are not propaged to devices

**Comment by AlvaroVega** [comment]
> Static attributes in groups are copied to autoprovision device data and before modifications of attribute static are not progression to entity.

When a static attribute of a groups is modified (maybe is just not so static) then this value is not going to device entities after a new measure arrives to device; until then attribute has previous value in entity device.

**Comment by AlvaroVega** [comment]
We are going to keep this issue open until clarify issue bout static_attrs with auto provisioned devices

**Comment by fgalan** [comment]
After the merging of PR https://github.com/telefonicaid/iotagent-node-lib/pull/1396, should this issue be closed?
