### ISSUE TITLE
Flow control in CB updates

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#1380]
It would be great if IOTAs could also benefit from [flow control feature in CB](https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/admin/perf_tuning.md#updates-flow-control-mechanism), enabling the `?option=flowControl` in the updates sent to ContextBroker. Maybe this should be a configuration parameter, with the usual "tree layers":

* General config in config.js / env var
* Group
* Device

the latter overriding the former.

This would help ETL integrations, when the ETL sends information via IOTA.

**Comment by mapedraza** [comment]
As discussed in our 2023 roadmap meeting, this feature does not have sense (NodeJS is asynchronous). Instead, it should make sense in the southbound as described here: https://github.com/telefonicaid/iotagent-node-lib/issues/1420
