### ISSUE TITLE
Add doc about device group heritage

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1395]
> Maybe we should tell in someplace in the documentation how this works. I mean, something like this:
> 
> > In the case of autoprovisioned devices, the associated document created in database doesn't include config group parameters (timestamp and explicitAttrs in particular). That way, these parameters can freely established modifying the device information after creation using the provisioning API. However, note that if a device (autoprovisioned or not) doesn't have these parameters defined at device level in database, the parameters are inherit from config group parameters.
> 
> Not sure where to include such fragment. Do we have some place in which autoprovisioned devices are explained? @mapedraza what do you think?

I agree, it seems reasonable. Maybe a new chapter explaining autoprovision under https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/api.md#iot-agent-information-model

_Originally posted by @mapedraza in https://github.com/telefonicaid/iotagent-ul/issues/616#issuecomment-1609356377_

**Comment by fgalan** [comment]
To be covered in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1391

**Comment by mapedraza** [comment]
Done in commit https://github.com/telefonicaid/iotagent-node-lib/commit/64f4ba31544fc48de7ad11d7eb373ec8e9f81735
