### ISSUE TITLE
Timeinstant config parameter is ignored

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1404]
### IoT Agent Node Lib version the issue has been seen with

3.2.0

### Bound or port used (API interaction)

Southbound (Devices data API), Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

normal

### Expected behaviour you didn't see

When using `timeInstant`parameter under a group, it is not working as expected. 6 possible cases analyzed

| `timeInstant` value | measure contains timeInstant | actual behaviour  | expectation |
| -- | -- | -- | -- |
| `true` | Yes | TimeInstant and metadata updated with measure value | works well - OK |
| `true` | No | TimeInstant and metadata updated with server timestamp | works well - OK |
| `false` | Yes | TimeInstant and metadata updated with measure value | should appear as attribute but not as metadata - NOK |
| `false` | No | TimeInstant and metadata updated with server timestamp | should not appear neither as attribute not as metadata - NOK |
| Not defined | Yes | TimeInstant and metadata updated with measure value | works well - OK |
| Not defined | No | TimeInstant and metadata updated with server timestamp | works well - OK |

### Configs

```yaml
environment:
    - "IOTA_CB_HOST=orion"
    - "IOTA_CB_PORT=1026"
    - "IOTA_NORTH_PORT=4041"
    - "IOTA_REGISTRY_TYPE=mongodb"
    - "IOTA_MONGO_HOST=mongodb"
    - "IOTA_MONGO_PORT=27017"
    - "IOTA_MONGO_DB=iotagent-json"
    - "IOTA_HTTP_PORT=7896"
    - "IOTA_PROVIDER_URL=http://iot-agent:4041"
```

**Comment by mapedraza** [comment]
Additionally, test does not implements all the cases:
https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/ngsiv2/plugins/timestamp-processing-plugin_test.js

**Comment by AlvaroVega** [comment]
Maybe related https://github.com/telefonicaid/iotagent-node-lib/issues/1377 ?

**Comment by AlvaroVega** [comment]
timeInstant value | measure contains timeInstant | actual behaviour | expectation
-- | -- | -- | --
false | Yes | TimeInstant and metadata updated with measure value | should appear as attribute but not as metadata - NOK
-- | -- | -- | --

This case happens when group has timestamp to false but device is autoprovisioned, and has no explicity defined timestamp at device level

**Comment by mapedraza** [comment]
Added tests in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1415

**Comment by fgalan** [comment]
Test cases covered by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1415. Closing.
