### ISSUE TITLE
Static attributes written once (at device creation)

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1424]
### IoT Agent Node Lib version the issue has been seen with

Master (3.3.0)

### Bound or port used (API interaction)

Southbound (Devices data API), Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

None

### Expected behaviour you didn't see

If static attribute is updated on the entity manually, it will remain the same as the IoTA is not going to write again that value. I do not know if that was the behaviour before using append by default

### Unexpected behaviour you saw

The IotA is not update on each request the static attributes before using append by default

### Steps to reproduce the problem

1. Create a device with static attributes (s=1)
2. Send data, and check the entity (s=1)
3. Update the static attribute (s=2)
4. Send another data through IoTA
5. Check the data. Static attribute does not change (s=2)

**Comment by AlvaroVega** [comment]
I'm not remember any change about this in previous versions. Since which issue or release are you testing?

**Comment by fgalan** [comment]
After internal discussion, we validate the issue described in this issue is the desired one.

**Comment by mapedraza** [comment]
After checking in deep this issue, it was because other config parameters (entity expression name). Checked from iotagent-json:1.26.0 to latest and the behaviour is the expected: to update statics everytime a measure arrives. 

Thus, this issue is not valid anymore
