### ISSUE TITLE
Remove device should use id and apikey

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1435]
### IoT Agent Node Lib version the issue has been seen with

3.2.0 and previous

### Bound or port used (API interaction)

Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

None

### Image type

None

### Expected behaviour you didn't see

Remove device should use id, apikey, serivce and subservice 

### Unexpected behaviour you saw

Remove device  only uses  id, service and subservice 

### Configs

```yaml
environment:
    - "IOTA_CB_HOST=orion"
    - "IOTA_CB_PORT=1026"
    - "IOTA_NORTH_PORT=4041"
    - "IOTA_REGISTRY_TYPE=mongodb"
    - "IOTA_MONGO_HOST=mongodb"
    - "IOTA_MONGO_PORT=27017"
    - "IOTA_MONGO_DB=iotagent-json"
    - "IOTA_HTTP_PORT=7896"
    - "IOTA_PROVIDER_URL=http://iot-agent:4041"
```

**Comment by AlvaroVega** [comment]
For a case having two devices provisioined with the same id but different apikey (like this case  https://github.com/telefonicaid/iotagent-node-lib/issues/1426 ) , then delete is done in a wrong way

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1438
