### ISSUE TITLE
Native support for NGSI-v2 and LD ingestion

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1451]
### Describe the solution you'd like

Enable native support to ingest NGSI-v2 and LD payloads directly from IoTA. This probably have implications both in https://github.com/telefonicaid/iotagent-node-lib and https://github.com/telefonicaid/iotagent-json

**Comment by AlvaroVega** [comment]
Done in https://github.com/telefonicaid/iotagent-json/issues/778
