### ISSUE TITLE
Allow to add metadata to attributes from measures

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1453]
### Describe the solution you'd like

Enable the possibility to map measures (or expressions) to metadata

**Comment by AlvaroVega** [comment]
attribute metadatas (for measures mapped to attributes or for static attributes) are now able to use expressions. Could we close this issue  @mapedraza ?

**Comment by mapedraza** [comment]
Implemented in https://github.com/telefonicaid/iotagent-node-lib/pull/1601
