### ISSUE TITLE
[Remove] Single Configuration Mode

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1469]
Remove support for Single Configuration Mode

This is an old method that provide backwards compatibility with older IoTAS (I assume CPP IoTAS)

According to the documentation:

>In order to allow backward-compatibility with those agents, the IoT Agent Library now implement a compatibility mode:
>the **Single Configuration Mode**, that makes the agent behave like the old agents. In this mode:
>
>-   Each Subservice can contain just one Configuration. If a second Configuration is created for a Subservice, an error
>    is raised.
>
>-   Each Device provisioned for a Subservice is automatically assigned to the Subservice one Configuration if there is
>    any.
>
>This compatibility has to be set for the whole IoT Agent, and there is no option of having both modes simultaneously
>running. Transitions from one mode to the other should be made with care, and may involve data migration.

*References*

https://github.com/search?q=repo%3Atelefonicaid%2Fiotagent-node-lib%20Single%20Configuration%20Mode&type=code

https://github.com/telefonicaid/iotagent-node-lib/blob/2d027c920ee180eedc49be5f3132abdd7ca75220/lib/commonConfig.js#L449

**Comment by fgalan** [comment]
Done in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1503
