### ISSUE TITLE
`entityNameExpr` allows invalid Orion entityID

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1477]
### IoT Agent Node Lib version the issue has been seen with

3.4.0

### Bound or port used (API interaction)

Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

None

### Unexpected behaviour you saw

When using expressions that results into an integer or boolean, the IoTA can build an invalid NGSv2 payload:

When defining a group like this and using a number ID (like `123`)

```
{
  "attributes": [
  ],
  "resource": "/iot/json",
  "apikey": "123456789",
  "type": "mytype",
  "service": "srv",
  "subservice": "/subsrv",
  "expressionLanguage": "jexl",
  "entityNameExp": "id",
  "__v": 0
}
```

The payload is:

```
{
   "ID":123
   ...
}
```

### Configs

```yaml
environment:
    - "IOTA_CB_HOST=orion"
    - "IOTA_CB_PORT=1026"
    - "IOTA_NORTH_PORT=4041"
    - "IOTA_REGISTRY_TYPE=mongodb"
    - "IOTA_MONGO_HOST=mongodb"
    - "IOTA_MONGO_PORT=27017"
    - "IOTA_MONGO_DB=iotagent-json"
    - "IOTA_HTTP_PORT=7896"
    - "IOTA_PROVIDER_URL=http://iot-agent:4041"
```

**Comment by AlvaroVega** [comment]
duplicated https://github.com/telefonicaid/iotagent-node-lib/issues/1476 ?
