### ISSUE TITLE
DOC: explicitAttributes true: just active attributes, not measures

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1500]
### IoT Agent Node Lib version the issue has been seen with

3.2.0

### Bound or port used (API interaction)

Southbound (Devices data API)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

normal

### Expected behaviour you didn't see

explicitAttributes true:
Just be attributes defined in active. Not measures.

### Unexpected behaviour you saw

explicitAttributes true:

https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/api.md#explicitly-defined-attributes-explicitattrs

Case 2:

"explicitAttrs": true

just measures defined in active, static (plus conditionally TimeInstant) will be propagated to NGSI interface.

https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/api.md#explicitly-defined-attributes-explicitattrs

### Configs

```yaml
environment:
    - "IOTA_CB_HOST=orion"
    - "IOTA_CB_PORT=1026"
    - "IOTA_NORTH_PORT=4041"
    - "IOTA_REGISTRY_TYPE=mongodb"
    - "IOTA_MONGO_HOST=mongodb"
    - "IOTA_MONGO_PORT=27017"
    - "IOTA_MONGO_DB=iotagent-json"
    - "IOTA_HTTP_PORT=7896"
    - "IOTA_PROVIDER_URL=http://iot-agent:4041"
```

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/iotagent-node-lib/blob/5ed79f6f8e48fd33863f581e1b91bf58f2fc9c03/test/unit/ngsiv2/plugins/multientity-plugin_test.js#L1277-L1317

**Comment by AlvaroVega** [comment]
PR about test: https://github.com/telefonicaid/iotagent-node-lib/pull/1502

**Comment by AlvaroVega** [comment]
Related PRs with explicitAttrs:

https://github.com/telefonicaid/iotagent-node-lib/pull/1355

**Comment by AlvaroVega** [comment]
PR for fix this issue: https://github.com/telefonicaid/iotagent-node-lib/pull/1502/commits/3af221990159ab3c22f2b719cfc708e6c0d412f3

**Comment by fgalan** [comment]
That commit belongs to PR https://github.com/telefonicaid/iotagent-node-lib/pull/1502, which has been closed.

Should this issue be closed also?
