### ISSUE TITLE
Static attributes test review

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1506]
### GPS3

**Provision**

https://github.com/telefonicaid/iotagent-node-lib/blob/e3645e6d5b5a00e5781eacbe2b2cd645b871adca/test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js#L270-L280

**Mock**
https://github.com/telefonicaid/iotagent-node-lib/blob/e3645e6d5b5a00e5781eacbe2b2cd645b871adca/test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js#L1821-L1831

**Expectation**
https://github.com/telefonicaid/iotagent-node-lib/blob/e3645e6d5b5a00e5781eacbe2b2cd645b871adca/test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin34.json#L1-L14

### GPS4

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-node-lib/pull/1507

**Comment by AlvaroVega** [comment]
GPS3 case is right since expliciAttrs is a jexl which does not include any static attr.
