### ISSUE TITLE
typeInformation should contain global config values, not just device + group 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1515]
### Component

Other

**Comment by Keshav-NEC** [comment]
Hi @AlvaroVega, I would like to contribute on this issue. Please confirm the below understanding :

Is the issue related to 
> https://github.com/telefonicaid/iotagent-node-lib/blob/4b4fe6130fa2bccc3494a455050e3c80e5c1e972/lib/services/northBound/restUtils.js#L201

Please provide the detail that should be included in `global config values`.

Please provide `API` so the I can debug it. Thanks.

**Comment by Keshav-NEC** [comment]
Hi @mapedraza , I proposed the below code modifications and understanding for https://github.com/telefonicaid/iotagent-node-lib/blob/301280a4644a93a68a836ec4a9ee2278f88f515a/lib/services/ngsi/ngsiService.js#L149 to

```typeInformation = { ...config.getConfig(), ...deviceInformation };```

and I have confirmed that ```typeInformation.timestamp``` is **true** not **undefined** at https://github.com/telefonicaid/iotagent-node-lib/blob/d1586fb65a4848ba615ad0cf0da7e39afb2fa350/lib/services/ngsi/entities-NGSI-v2.js#L305

Please confirm, if I can proceed further and raise PR after doing changes in [entities-NGSI-v2.js](https://github.com/telefonicaid/iotagent-node-lib/blob/d1586fb65a4848ba615ad0cf0da7e39afb2fa350/lib/services/ngsi/entities-NGSI-v2.js#L304-L309) or any other change is required.

**Comment by fgalan** [comment]
Fixed by PR #1580
