### ISSUE TITLE
Link for API reference is showing 404

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/iotagent-node-lib#1518]
Link for API reference is showing 404 at :
https://github.com/telefonicaid/iotagent-node-lib/blob/17bec4218b4c95358d9d0428003b97f4ef633981/doc/index.md?plain=1#L14

**Comment by Keshav-NEC** [comment]
Hi @pooja1pathak , I am working on it.

**Comment by fgalan** [comment]
Should this issue be closed after merging PR #1519?
