### ISSUE TITLE
Timeinstant as attribute case (not measure)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1557]
### Is your feature request related to a problem? Please describe

When timestamp conf if false but:

attribute map is:
Param | Att Entity | type
Datetime | Timestamp | DateTime
TimeInstant | DateObserved | Datetime

measure contains: 
DateTIme:
TimeInstant: 

metadatas are lose

Full case is described at https://github.com/telefonicasc/jcyl-project/issues/153

**Comment by AlvaroVega** [comment]
Testing with device with timestamp true and the following mapping

![Screenshot from 2024-02-23 11-15-02](https://github.com/telefonicaid/iotagent-node-lib/assets/983422/272ebf05-5eaf-46db-ab28-9ceb8120c664)

and with the follow measure:

 curl -i -X POST 'http://localhost:7897/iot/json?i=disp1&k=zrvj173zhvzb12t233z48vg96' -d '{ "TimeInstant": "2024-02-22T08:02:23.000Z", "datetime": "2024-02-22T08:02:23.000Z", "color": "blue"}' -H 'content-type: application/json'


entity has provided TimeInstant in metadata attributes:

![Screenshot from 2024-02-23 11-16-19](https://github.com/telefonicaid/iotagent-node-lib/assets/983422/362c8723-6908-46bb-8c9c-4d3b46977561)

**Comment by AlvaroVega** [comment]
Testing with device with timestamp false and the following mapping

![Screenshot from 2024-02-23 11-15-02](https://github.com/telefonicaid/iotagent-node-lib/assets/983422/5eeaab8f-b0a7-4ec2-9ee5-bbb752f69ab1)


and with the follow measure:

curl -i -X POST 'http://localhost:7897/iot/json?i=disp1&k=zrvj173zhvzb12t233z48vg96' -d '{ "TimeInstant": "2024-02-22T08:02:23.000Z", "datetime": "2024-02-22T08:02:23.000Z", "color": "blue"}' -H 'content-type: application/json'

entity has provided TimeInstant in metadata attributes:

![Screenshot from 2024-02-23 11-18-10](https://github.com/telefonicaid/iotagent-node-lib/assets/983422/09bf3b48-6675-476d-8223-3cc66fe54b45)

**Comment by AlvaroVega** [comment]
Testing with a group with timeinstant=true and the following measures:

 curl -i -X POST --location 'http://localhost:7897/iot/json?i=disp1&k=APIKEY1' --header 'Content-Type: application/json' --data '{"hola":"adios", "TimeInstant": "2022-02-02T22:22:22.222Z"}'


 curl -i -X POST --location 'http://localhost:7897/iot/json?i=disp2&k=APIKEY1&t=2022-02-02T22:22:22.222Z' --header 'Content-Type: application/json' --data '{"hola":"adios"}'


both cases entity TimeInstant has provided value (2022-02-02T22:22:22.222Z) and metadata Timeinstant is also filled with that value (2022-02-02T22:22:22.222Z)

**Comment by AlvaroVega** [comment]
When a mapping is defined like
attribute map is:
Param | Att Entity | type
mydatetime | Timestamp | DateTime

and a measure arrives like:

 curl -i -X POST --location 'http://localhost:7897/iot/json?i=SENSOR&k=APIKEY1' --header 'Content-Type: application/json' --data '{"hola":"adios", "mydatetime": "2022-02-02T02:22:22.222Z"}'


then entity TimeInstant and metadata Timeinstant has system timeinstnat, not provided in mydatetime ("2022-02-02T02:22:22.222Z")

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1593
