### ISSUE TITLE
Change type from string to Text

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/iotagent-node-lib#1569]
FUNCTIONAL TESTS  are failing after changing constants.DEFAULT_ATTRIBUTE_TYPE is string instead of Text as mentioned in issue [#810](https://github.com/telefonicaid/iotagent-json/issues/810) in IoTAgent-JSON in PR [#813](https://github.com/telefonicaid/iotagent-json/pull/813)

Change type from string to Text will be required in test file for successful execution.

**Comment by Keshav-NEC** [comment]
Hi, I am working on it

**Comment by fgalan** [comment]
After merging PR #1571, I think this issue could be closed.
