### ISSUE TITLE
add new API to delete high number of devices

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1578]

**Comment by AlvaroVega** [comment]
Current delete is for one device:

i.e.: 
DELETE
	https://localhost/iota/iot/devices/DeviceID?apikey=gu1y31lo1agyr2xqf448n0s5v&protocol=IoTA-JSON

**Comment by AlvaroVega** [comment]
@fgalan

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1579
