### ISSUE TITLE
Allow use a different TimesInstant wording for metadata

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1595]
### Component

New feature

### Is your feature request related to a problem? Please describe

Instead use "TimeInstant"in metadata it would be great use a different or custom word

**Comment by fgalan** [comment]
For instance, instead of using `TimeInstant` being able to use `timestamp`.

Should be configurable at group and devices level, using the same strategy in other similar fields we already have in the API.

**Comment by Madhu1029** [comment]
Hi @AlvaroVega ,
Could you please explain this issue in detail? I would like to contribute on this.

**Comment by fgalan** [comment]
@Madhu1029 after internal discussion, we have decided this functionality is not important for the IOTA. Thus, the issue has been closed.

If you want to contribute, I'd recommend to have a look to other issues and pick another.
