### ISSUE TITLE
allow to define metadatas in device attributes

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1598]
### Component

New feature

### Describe the solution you'd like

allow use measures with metadatas it will be constants

static already could has metadata object
active and lazy could define a metadata object with name and and type are constant and value are depending on context

metadata will not part of jexl context by the moment

### The systemd version you checked that didn't have the feature you are asking for

3.2.0

**Comment by AlvaroVega** [comment]
related https://github.com/telefonicaid/iotagent-node-lib/issues/1453

**Comment by mapedraza** [comment]
Implemented in https://github.com/telefonicaid/iotagent-node-lib/pull/1601
