### ISSUE TITLE
Add `timestamp` tests

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1600]
- 1. Add explicitAttrs value = [ ] 
Expected value = no update to CB entity
   - 1.a Using timestamp = true (it also skips TImeInstant Attr) https://github.com/telefonicaid/iotagent-node-lib/blob/3946928b53e243f3728ff8d46aa230e1b7d13286/test/functional/testCases.js#L1707
   - 1.b Using timestamp = false

- 2. Add timestamp = false, TimeInstant is defined by a JEXL attribute expression and explicitAttrs value = [ attrA ]
Expected value = no TImeInstant value present, only attrA

CC: @danielvillalbamota

**Comment by fgalan** [comment]
Test added in PR #1605
