### ISSUE TITLE
Problems with explicitAttrs and TimeInstan #1605

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1606]
### Unexpected behaviour you saw

When using explictAttrs with value `[]` (no attribute should pass), TimeInstant value pass. See https://github.com/telefonicaid/iotagent-node-lib/pull/1605

**Comment by AlvaroVega** [comment]
corner case?

**Comment by fgalan** [comment]
PR #1610 is the regression for this issue (i.e. when this issue gets fixed, the test included in that PR will check it). In fact, maybe this issue could be solved in task/add-533-func branch (the one used by PR #1610) so we have all in the same place.

**Comment by mapedraza** [comment]
> I understand that after merging PR #1618 this issue can be closed.

That's right
