### ISSUE TITLE
sort multimeasures by an attribute (by TimeInstant )

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1612]
### Component

Feature enhancement

### Is your feature request related to a problem? Please describe

related https://github.com/telefonicaid/iotagent-json/issues/825 and https://github.com/telefonicaid/iotagent-node-lib/pull/1607

**Comment by AlvaroVega** [comment]
Done in https://github.com/telefonicaid/iotagent-node-lib/pull/1607

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1607
