### ISSUE TITLE
Include attribute metadata as part of the JEXL context

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1630]
### Component

IoT Agent Node Lib
IoT Agent JSON

### Is your feature request related to a problem? Please describe

Include attribute metadata as part of the JEXL context

Related implementation in CB: https://github.com/telefonicaid/fiware-orion/issues/4594#issuecomment-2264980414

### Describe the solution you'd like

Include attribute metadata as part of the JEXL context

File related:
https://github.com/telefonicaid/iotagent-node-lib/blob/46ac1d88a392f4432d4c849c2522c1d6a577f285/lib/services/ngsi/entities-NGSI-v2.js#L340

Note: In the case of NGSIv2 and NGSI-LD payloads, it would be great to have the payload metadata context available before evaluating attributes expression.

A uses case is to use `previousValue` built-in metadata to evaluate if an attribute really changes and, eventually, propagate or not the IoTA update depending on this (to avoid overload the destination CB)

**Comment by fgalan** [comment]
> A uses case is to use `previousValue` built-in metadata to evaluate if an attribute really changes and, eventually, propagate or not the IoTA update depending on this (to avoid overload the destination CB)

That would be done by a subscription at CB with `"metadata": [ "previousValue"]" using IOTA southbound API as endpoint.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-node-lib/pull/1631
