### ISSUE TITLE
[Doc] Change the term services group to groups

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1632]
Across all the documentation

**Comment by mapedraza** [comment]
Should the API methods be changed?

https://github.com/telefonicaid/iotagent-node-lib/blob/c57d8929d4a44c7ee57ba16d673024b8ea3ffb75/doc/api.md#L1684-L1751

**Comment by fgalan** [comment]
> Should the API methods be changed?

Maybe that change should be part of PR https://github.com/telefonicaid/iotagent-node-lib/pull/1637 (to change code implementation and doc at the same time, when that PR gets merged)

**Comment by fgalan** [comment]
After merging PR https://github.com/telefonicaid/iotagent-node-lib/pull/1635 (and taking into account the deferred task described in [previous comment](https://github.com/telefonicaid/iotagent-node-lib/issues/1632#issuecomment-2273224607)) maybe this issue can be closed.
