### ISSUE TITLE
[DOC] Uniqueness of groups and devices

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-node-lib#1633]
Is this correct?

https://github.com/telefonicaid/iotagent-node-lib/blob/c57d8929d4a44c7ee57ba16d673024b8ea3ffb75/doc/api.md?plain=1#L162-L167

Is not group defined by apikey and resource?
Devices by device_id and apikey?

CC: @fgalan @AlvaroVega

**Comment by AlvaroVega** [comment]
According with model/Group.js and lib/services/groups/*  `Group service uniqueness is defined by the combination of: service, subservice, resource and apikey `.
I don't why but I've always use default `resource`, but it`s possible to use different resources.
Device uniqueness is as described: service, subservice, device_id and apikey.

**Comment by fgalan** [comment]
Should this issue be closed after the merge of PR https://github.com/telefonicaid/iotagent-node-lib/pull/1639 ?

**Comment by mapedraza** [comment]
Yes, it is solved after #1639
