### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by chazemar** [telefonicaid/iotagent-node-lib#165]
Could you please specify the LICENSE ?
Thanks.

**Comment by dmoranj** [comment]
I'll add a copy to the repository during the day. It's specified in the headers of the source code, anyway: GNU Affero General Public License.

**Comment by chazemar** [comment]
Ok
FYI we use the project for one of our sample code :
https://github.com/Orange-OpenSource/fiware-cepheus/tree/linksprite-ngsi
:+1:
