### ISSUE TITLE
report operation response time

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1650]
### Is your feature request related to a problem? Please describe

When a request to iotagent arrives it would be great to have a way to know how much time is expected to process and respond. I.e. a measure arrives and is processed by iotagent.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/845 and PR https://github.com/telefonicaid/iotagent-ul/pull/685
