### ISSUE TITLE
MEASURES-002 error should include all device/groups expression defined when log error

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1655]
From https://github.com/telefonicasc/VentanillaUnicaSC/issues/66

**Comment by AlvaroVega** [comment]
related with https://github.com/telefonicaid/iotagent-json/pull/816

**Comment by AlvaroVega** [comment]
For example sending a mesaure like: 
```script
$ curl -i -X POST 'http://localhost:7897/iot/json?i=disp1&k=APIKEY1' -d '{ "TimeInstant": "2024-09-18T08:56:19.425000+02:00"}' -H 'content-type: application/json'
```

Produces de following log:

time=2024-09-18T07:37:04.229Z | lvl=ERROR | corr=e7078978-e14d-4b37-9962-13858e15f478 | trans=e7078978-e14d-4b37-9962-13858e15f478 | op=IOTAJSON.HTTP.Binding | from=n/a | srv=n/a | subsrv=n/a | msg=MEASURES-002: Couldn't send the updated values to the Context Broker due to an error: {"name":"ENTITY_GENERIC_ERROR","message":"Error accesing entity data for device: thing:disp1 of type: thing and {\"timestamp\":true,\"defaultResource\":\"/iot/json\",\"explicitAttrs\":false,\"multiCore\":false,\"relaxTemplateValidation\":false,\"defaultEntityNameConjunction\":\":\",\"defaultType\":\"Thing\",\"_id\":\"66c46db351c4502ed9099258\",\"lazy\":[],\"active\":[{\"object_id\":\"a\",\"name\":\"a\",\"type\":\"Text\",\"metadata\":{}},{\"object_id\":\"b\",\"name\":\"b\",\"type\":\"Number\",\"expression\":\"55\",\"metadata\":{}},{\"object_id\":\"temp\",\"name\":\"temp\",\"type\":\"Number\",\"expression\":\"temp + 14\",\"metadata\":{\"unit\":{\"type\":\"text\",\"value\":\"cms\",\"expression\":\"\\\"hola\\\"+\\\"adios\\\"\"}}}],\"commands\":[],\"staticAttributes\":[{\"name\":\"precio\",\"type\":\"number\",\"value\":66},{\"name\":\"color\",\"type\":\"string\",\"value\":\"blue\",\"metadata\":{\"units\":{\"type\":\"text\",\"value\":\"cms\"}}}],\"creationDate\":\"2024-08-20T10:19:31.844Z\",\"id\":\"disp1\",\"type\":\"thing\",\"name\":\"thing:disp1\",\"service\":\"smartcity\",\"subservice\":\"/\",\"internalId\":null,\"apikey\":\"APIKEY1\",\"protocol\":\"IoTA-JSON\",\"transport\":\"HTTP\",\"polling\":true,\"subscriptions\":[],\"entityNameExp\":\"r\"}","details":{"error":"BadRequest","description":"date has invalid format"},"code":400} | comp=IoTAgent

**Comment by AlvaroVega** [comment]
Currently there is no issue

**Comment by fgalan** [comment]
Related https://github.com/telefonicaid/fiware-orion/issues/4616
