### ISSUE TITLE
Align with FIWARE projects

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/iotagent-node-lib#327]
if this project is now officially part of FIWARE, it should align by having badges, readthedocs, webhook and mirror on github.com/fiware etc. 

please check Orion for a reference

**Comment by fgalan** [comment]
May Sprint is full of work with regars to IOTAgents. Thus, this issue is deferred until (at least) June Sprint.

**Comment by dmoranj** [comment]
Already addressed in past PRs.
