### ISSUE TITLE
Error deleting service

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-node-lib#328]
When trying to delete a service from iota using the following:

DELETE /iot/services?apikey=121212121212121212121212199&amp;resource=/iot/d HTTP/1.1
Host: 192.168.21.64:4061
Accept: application/json
Fiware-Service: city012
Fiware-ServicePath: /electricidad
x-auth-token: 22a15a409f294cb8b4c7419a96c46154
Cache-Control: no-cache
Postman-Token: 9287a290-7eec-2c9f-7500-2ba7d42201a2

The entry in mongo collection is deleted but an error is shown in the request:

404
{
  "name": "DEVICE_GROUP_NOT_FOUND",
  "message": "Couldn\t find device group"
}

The log shows the following:

time=2016-05-10T10:09:26.234Z | lvl=DEBUG | corr=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | trans=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | op=IoTAgentNGSI.RestUtils | srv=city012 | subsrv=/electricidad | msg=Request for path [/iot/services] from [nodes_4061_to_4061]
time=2016-05-10T10:09:26.234Z | lvl=DEBUG | corr=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | trans=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | op=IoTAgentNGSI.RestUtils | srv=city012 | subsrv=/electricidad | msg=Unrecognized body type undefined
time=2016-05-10T10:09:26.234Z | lvl=DEBUG | corr=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | trans=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=city012 | subsrv=/electricidad | msg=Looking for entity params ["resource","apikey"]
time=2016-05-10T10:09:26.238Z | lvl=DEBUG | corr=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | trans=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=city012 | subsrv=/electricidad | msg=Removing device group with id [5731b347205f97ed7d1141e9]
time=2016-05-10T10:09:26.238Z | lvl=DEBUG | corr=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | trans=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=city012 | subsrv=/electricidad | msg=Looking for device group with id [5731b347205f97ed7d1141e9].
time=2016-05-10T10:09:26.240Z | lvl=DEBUG | corr=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | trans=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=city012 | subsrv=/electricidad | msg=Entity [5731b347205f97ed7d1141e9] not found for removal.
time=2016-05-10T10:09:26.241Z | lvl=DEBUG | corr=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | trans=5074517d-5f51-4b7e-b7a5-3e2fb269ed79 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=city012 | subsrv=/electricidad | msg=Error [DEVICE_GROUP_NOT_FOUND] handing request: Couldn   find device group
time=2016-05-10T10:09:26.241Z | lvl=DEBUG | corr=6c962639-b98d-4e72-bb78-58545c764914 | trans=6c962639-b98d-4e72-bb78-58545c764914 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=response-time: 8

**Comment by dmoranj** [comment]
Please, add the configuration to the issue, for further information.

**Comment by manucarrace** [comment]
/* Ansible managed: modified by IoT devops team */
/*
 * Copyright 2016 Telefonica Investigación y Desarrollo, S.A.U
 *
 * This file is part of iotagent-ul
 *
 * iotagent-ul is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * iotagent-ul is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with iotagent-ul.
 * If not, seehttp://www.gnu.org/licenses/.
 *
 * For those usages not covered by the GNU Affero General Public License
 * please contact with::[iot_support@tid.es]
 */

'use strict';

var config = {};

config.mqtt = {

    /**
     * Host where the MQTT Broker is located.
     */
    host:       '10.0.0.8',

    /**
     * Port where the MQTT Broker is listening
     */
    port:        1883,

    /**
     * User name for the IoTAgent in the MQTT broker, if authentication is activated.
     */
    username:   'iotagent',

    /**
     * Password for the IoTAgent in the MQTT broker, if authentication is activated.
     */
    password:   'iotagent'

};


config.http = {
    /**
     * Port where the HTTP Ultralight transport binding will be listening for device requests.
     */
    port: 8085
};

config.iota = {
    /**
     * Configures the log level. Appropriate values are: FATAL, ERROR, INFO, WARN and DEBUG.
     */
    logLevel: 'DEBUG',


    /**
     * When this flag is active, the IoTAgent will add the TimeInstant attribute to every entity created, as well
     * as a TimeInstant metadata to each attribute, with the current timestamp.
     */
    timestamp: true,


    /**
     * Context Broker configuration. Defines the connection information to the instance of the Context Broker where
     * the IoT Agent will send the device data.
     */
    contextBroker: {
        /**
         * Host where the Context Broker is located.
         */
        host: '10.0.0.2',


        /**
         * Port where the Context Broker is listening.
         */
        port: 1026
    },


    server: {
        /**
         * Port where the IoT Agent will be listening for requests.
         */
        port: 4061
    },


    /**
     * Configuration for the IoT Manager. If the IoT Agent is part of a configuration composed of multiple IoTAgents
     * coordinated by an IoT Manager, this section defines the information that will be used to connect with that manager.
     */


    iotManager: {
        /**
         * Host where the IoT Manager is located.
         */
        host: '10.0.0.6',

        /**
         * Port where the IoT Manager is listening.
         */
        port: 8086,

        /**
         * Path where the IoT Manager accepts subscriptions.
         */
        path: '/iot/protocols',

        /**
         * Protocol code identifying this IoT Agent.
         */
        protocol: 'PDI-IoTA-UltraLight',

        /**
         * Textual description of this IoT Agent.
         */
        description: 'MQTT Ultralight 2.0 IoT Agent. Node.js version',

        /**
         * Default resource of the IoT Agent. This value must be different for every IoT Agent connecting to the IoT
         * Manager.
         */
        defaultResource: '/iot/d'
    },



    /**
     * Defines the configuration for the Device Registry, where all the information about devices and configuration
     * groups will be stored. There are currently just two types of registries allowed:
     *
     * - 'memory': transient memory-based repository for testing purposes. All the information in the repository is
     *             wiped out when the process is restarted.
     *
     * - 'mongodb': persistent MongoDB storage repository. All the details for the MongoDB configuration will be read
     *             from the 'mongoDb' configuration property.
     */
    deviceRegistry: {
        type: 'mongodb'
    },


    /**
     * Mongo DB configuration section. This section will only be used if the deviceRegistry property has the type
     * 'mongodb'.
     */
    mongodb: {

        /**
         * Host where MongoDB is located. If the MongoDB used is a replicaSet, this property will contain a
         * comma-separated list of the instance names or IPs.
         */
        host: '10.0.0.19,10.0.0.20,10.0.0.21',


        /**
         * Port where MongoDB is listening. In the case of a replicaSet, all the instances are supposed to be listening
         * in the same port.
         */
        port: '27017',


        /**
         * Name of the set in case the Mongo database is configured as a Replica Set. Optional otherwise.
         */
        replicaSet: 'cb_rs0',

        /**
         * Name of the Mongo database that will be created to store IOTAgent data.
         */
        db: 'iotagent_ul_general'
    },

    /**
     *  Types array for static configuration of services. Check documentation in the IoTAgent Library for Node.js for
     *  further details:
     *
     *      https://github.com/telefonicaid/iotagent-node-lib#type-configuration
     */
    types: {},

    /**
     * Default service, for IOTA installations that won't require preregistration.
     */
    defaultService: 'howtoService',

    /**
     * Default subservice, for IOTA installations that won't require preregistration.
     */
    defaultSubservice: '/howto',

    /**
     * URL Where the IOTA Will listen for incoming updateContext and queryContext requests (for commands and passive
     * attributes). This URL will be sent in the Context Registration requests.
     */
    providerUrl: 'http://10.0.0.2:4061',


    /**
     * Default maximum expire date for device registrations.
     */
    deviceRegistrationDuration: 'P1M',

     /**
     * Default type, for IOTA installations that won't require preregistration.
     */
    defaultType: 'Thing'
};

/**
 * Default API Key, to use with device that have been provisioned without a Configuration Group.
 */
config.defaultKey =  '1234';

/**
 * Default transport protocol when no transport is provisioned through the Device Provisioning API.
 */
config.defaultTransport = 'MQTT';


module.exports = config;
