### ISSUE TITLE
if no services 404 and error payload are returned

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/iotagent-node-lib#330]
GET /iot/services/

404

```json
{
  "name": "DEVICE_GROUP_NOT_FOUND",
  "message": "Couldn\t find device group"
}
```

for coherency with other APIs, ex. NGSIv2, it would be better to return an empty array

**Comment by dmoranj** [comment]
That's not exactly a bug, but a feature. See [the definition of the Configuration API](https://github.com/telefonicaid/fiware-IoTAgent-Cplusplus/blob/develop/doc/north_api.md). I don't like it either. But we must be cautious modifying an API that is actually in use in other projects.
