### ISSUE TITLE
 Need of standardization for IoTAs with MQTT binding

### ISSUE THREAD

**Issue by XavierVal** [telefonicaid/iotagent-node-lib#361]
Need of standardization for iotas and binding mqtt measure reporting
The doc says:

| IoTAgent  | Binding | topic 1 measure | topic N measures |
| ------------- | ------------- | ------------- | ------------- |
| IOTA_UL | MQTT | attrs | attrs |
| IOTA_JSON | MQTT | attributes | attributes |

It should be the same param name to be more standard in both agents and being different does not bring new info because it is already set the kind of protocol used in the device provision. 

So, attr or attributes? 

refs:
[iotajson](https://github.com/telefonicaid/iotagent-json#measure-reporting)
[iotaul](https://github.com/telefonicaid/iotagent-ul/tree/develop#mqtt)

**Comment by dmoranj** [comment]
I would suggest `attr` but I don't have a strong opinion about that.

**Comment by XavierVal** [comment]
`attr` sounds good enough 👍
