### ISSUE TITLE
No timeout defined for HTTP commands

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-node-lib#373]
It should be defined a timeout for commands responses.

Also it would be nice to change the status of the command in case the commnad endpoint does not respond

**Comment by manucarrace** [comment]
I would say this is more than an enhancement. If no timeout is defined a command could be in PENDING status forever.

**Comment by dmoranj** [comment]
Thinking it carefully, this issue doesn't belong to the library, but to the particular implementations of the IoTAs, as the mechanism to implement the Timeouts will most probably rely on the particular implementations of the Southbound protocols. I'll close this one and reopen the corresponding ones in the JSON and UL IOTA repositories.
