### ISSUE TITLE
Wrong Syntax response trying to create device with metadatas

### ISSUE THREAD

**Issue by b-rvc** [telefonicaid/iotagent-node-lib#387]
Trying to create a device with metadata field in attributes will response with a code 400 and details: `{"name":"WRONG_SYNTAX","message":"Wrong syntax in request: Errors found validating request."}}]`

The body of the payload sent is: 

```
{
	"devices": [{
		"protocol": "IoTA-UL",
		"entity_name": "dm567eA2",
		"entity_type": "thing",
		"static_attributes": [{
			"type": "value",
			"name": "att_name",
			"value": "string"
		}],
		"attributes": [{
			"type": "int",
			"name": "temperature",
			"object_id": "meas"
		}, {
			metadata": [{
				"metaname": "string",
				"metaobject_id": "unit",
				"metatype": "celsius"
			}]
		}],
		"device_id": "device002"
	}]
}
```

**Comment by dmoranj** [comment]
As the error says, the payload is not syntactically right: the following:
```
{
            metadata": [{
                "metaname": "string",
                "metaobject_id": "unit",
                "metatype": "celsius"
            }]
        }
```
is not a valid attribute description: all attributes should contain an 'object_id' or a 'name' and a 'type'. The metadata attribute, on the other side, is not currently accepted in the provisioning API (please, add an issue requesting the feature if it seems to be important).
