### ISSUE TITLE
Use a more consistent, uniform and sensor/device oriented terminology

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/iotagent-node-lib#437]
After implementing the FIWARE Device Simulator and once it has been started to be used, a request to use a more consistent terminology to configure the simulator and consequently the IoTAs has arisen. Currently property names such as `staticAttributes`, `active`, `object_id` are included in the configuration of the IoTAs which seem not to be the used in the sensor/device domain.

I will invite a person in contact with sensor/devices produces to guide and to help us to solve this issue.

**Comment by dmoranj** [comment]
Regarding this issue, it's important to remember that those attributes are part of the main API of all the IoTAgents, and it's being used already in multiple projects, so changing those names may have big impact; every action in this direction should be thought carefully.

**Comment by dmoranj** [comment]
I'm closing this issue, as the global improvement of the API must be considered an epic in the Roadmap, and IMO doesn't belong to the issues list.
