### ISSUE TITLE
[Bug] Bidirectional plugin provision fails

### ISSUE THREAD

**Issue by XavierVal** [telefonicaid/iotagent-node-lib#503]
Context Broker rejects the creation of the empty entity with empty values in the provision:

```
{
    "url": "http://1.1.1.1:1026/v1/updateContext",
    "method": "POST",
    "json": {
        "contextElements": [
            {
                "type": "sensor",
                "isPattern": "false",
                "id": "eii01201ttt",
                "attributes": [
                    {
                        "name": "humidity",
                        "type": "percent",
                        "value": " "
                    },
                    {
                        "name": "fillingLevel",
                        "type": "Number",
                        "value": " "
                    },
                    {
                        "name": "location",
                        "type": "geo:point",
                        "value": " "
                    },
                    {
                        "name": "TimeInstant",
                        "type": "ISO8601",
                        "value": " "
                    }
                ]
            }
        ],
        "updateAction": "APPEND"
    },
```

`time=2016-11-02T10:38:47.018Z | lvl=DEBUG | corr=40f2c743-4867-4e52-8a54-6d1aecdd803f | trans=40f2c743-4867-4e52-8a54-6d1aecdd803f | op=IoTAgentNGSI.NGSIParser | srv=carga | subsrv=/scarga | msg=Device provisioning failed due to the following error:  | comp=IoTAgent Request error connecting to the Context Broker: {"code":"472","reasonPhrase":"request parameter is invalid/not allowed","details":"action: APPEND - entity: [eii01201ttt, sensor] - offending attribute: location - error parsing location attribute for new attribute: geo coordinates format error [see Orion user manual]:  "}`

**Comment by dmoranj** [comment]
The problem is not with the bidirectional plugin, but with the default values for attribute types.
