### ISSUE TITLE
Object and Array support in the Expression Translation plugin

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#568]
It would be cool to be able to do someething like this:

```
         "attributes":[
            ...
            {
               "name":"insideHouse",
               "type":"Array",
               "expression": [ "${@temperature}", "${@humidity}", "${@pressure}" ]
            },
            {
               "name":"permiter",
               "type":"Object",
               "expression": {
                 "north": "${@presenceN}",
                 "south": "${@presenceS}",
                 "west": "${@presenceW}",
                 "east": "${@presenceE}"
               }
            }
         ]
```
so, as result of the plugin, if we get a measure like this at southbound

```
t|25|h|79|p|27|pN|0|pS|1|pE|1|pW|0
```

the IOTA sends the following update to CB at northbound:

```
{
   "insideHouse": [ 25, 79, 27],
   "perimeter": {
     "north": 0,
     "south": 1,
     "east": 1,
     "west": 0
}
```

Current Expression Translation plugin doesn't support Array and Object, as far as I know.

There is an interesting challengue related with specific types of the final sub-elements, e.g. how to specify type in the sub-elements of the array or Object, i.e. `[ 25, 79, 27 ]` or `[ "25", "79", "27"]`. Maybe the cast could be specified in at expression level? i.e. `"expression": [ "(${@temperature},{Number}" ]`... just thinking aloud :)

The expressionLanguage.md document should be modified in order to take into account the new types.

**Comment by dherykw** [comment]
+1 It would be very helpful, indeed we think that it is mandatory to represent FIWARE data models

**Comment by fgalan** [comment]
The legacy expression language is deprecated, so this issue is no longer valid. We are going to close it.

Note that JEXL support natively objects and arrays (https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/expressionLanguage.md#comparison-between-expression-languages).
