### ISSUE TITLE
Bug in mergeArrays of deviceService

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#569]
If the parameters of mergeArrays function are not instances of Array type, the function will fail in line 246.

This error has been detected in the test of line 139 of https://github.com/Fiware/iot.IoTagent-LWM2M/blob/master/test/unit/commands-test.js.

**Comment by fgalan** [comment]
Hint: you can add the line to the link just adding `#Lxx` to the URL. It is very useful in long source files.

Example: https://github.com/Fiware/iot.IoTagent-LWM2M/blob/master/test/unit/commands-test.js#L139

(Off-topic, but I hope that useful :)

**Comment by dcalvoalonso** [comment]
Thanks so much!! Very useful indeed!! :)

**Comment by fgalan** [comment]
Preventively labeling the issue as bug

**Comment by dcalvoalonso** [comment]
I have added a new test to raise this error: https://github.com/dcalvoalonso/iotagent-node-lib/blob/bug/mergeArrays/test/unit/lazyAndCommands/lazy-devices-test.jsL915

**Comment by dcalvoalonso** [comment]
New PR to fix this bug: https://github.com/telefonicaid/iotagent-node-lib/pull/571
