### ISSUE TITLE
Alias plugin for NGSIv2

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#583]
This issue is related to https://github.com/telefonicaid/iotagent-node-lib/issues/527 and was proposed by @fgalan in https://github.com/telefonicaid/iotagent-ul/pull/242#discussion_r171173668.

In https://github.com/dcalvoalonso/iotagent-node-lib/blob/task/activeAttsNgsi2/lib/plugins/attributeAlias.js#L70, we should add some functionality to cast the attribute's value to the appropriate type.

This shall be merged in the ongoing https://github.com/telefonicaid/iotagent-node-lib/pull/556.

**Comment by fgalan** [comment]
Doubt: this is an issue in the iotagent-nodel-lib? Or in the iotagent-ul?

I mean, string-to-native-JSON casting is meaninfull only in iotagent-ul, as the UL protocol in the southbound o the IOTA is strictly strict based. However, in the case of iotagent-json agent, the southbound uses JSON so casting is not needed.

What do you think?

**Comment by dcalvoalonso** [comment]
In my eyes this is an issue for the iotagent-nodel-lib. We have aleady implemented string-to-native-JSON casting in https://github.com/telefonicaid/iotagent-ul/pull/242 but as we agreed in https://github.com/telefonicaid/iotagent-ul/pull/242#discussion_r171173668, we have a problem when attributes' alias are used to send observations. Implementing this in the  iotagent-ul would require to somehow duplicate the alias plugin functionality there...

**Comment by fgalan** [comment]
> Implementing this in the iotagent-ul would require to somehow duplicate the alias plugin functionality there...

In my opinion, this argument is powerful enough to keep the issue/fix in the scope of the library :)

**Comment by fgalan** [comment]
Not sure if this issue has been solved ty #556, https://github.com/telefonicaid/iotagent-json/pull/265 or
https://github.com/telefonicaid/iotagent-ul/pull/242

What do you think @dcalvoalonso ? Is it closeable?

**Comment by dcalvoalonso** [comment]
Yes  @fgalan. In my eyes this was solved and therefore we can close the issue. :)
