### ISSUE TITLE
Configuration API

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#588]
In [Configuration API](https://github.com/telefonicaid/iotagent-node-lib#device-group-model), it is stated that the model is as follows for active attributes:

| Payload Field | DB Field | Definition                                     |
| ------------------- | ------------------- |:---------------------------------------------- |
| active    	        | attributes    	    | list of active attributes of the device. For each attribute, its `name` and `type` must be provided. |

This is also used in the example:

```
{
	"services": [
	{
	    "resource": "/deviceTest",
	    "apikey": "801230BJKL23Y9090DSFL123HJK09H324HV8732",
	    "type": "Light",
	    "trust": "8970A9078A803H3BL98PINEQRW8342HBAMS",
	    "cbHost": "http://unexistentHost:1026",
	    "commands": [
	        {
	            "name": "wheel1",
	            "type": "Wheel"
	        }
	    ],
	    "lazy": [
	        {
	            "name": "luminescence",
	            "type": "Lumens"
	        }
	    ],
	    "active": [
	        {
	            "name": "status",
	            "type": "Boolean"
	        }
	    ]
	}
	]
}
```

Nevertheless, in all the tests and examples used actually in the library, the payload field used is `attributes`. For instance:
- https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/examples/groupProvisioningRequests/provisionFullGroup.json
- https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/examples/groupProvisioningRequests/provisionFullGroupAlternate.json
- https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/examples/groupProvisioningRequests/bidirectionalGroup.json

Also in the IOTAs:
- UL
  - https://github.com/telefonicaid/iotagent-ul/blob/master/test/groupProvisioning/provisionFullGroup.json
- JSON
  - https://github.com/telefonicaid/iotagent-json/blob/master/test/groupProvisioning/provisionFullGroupAMQP.json

**Comment by fgalan** [comment]
Seems to be a documentation bug. What do you think @dcalvoalonso ?

**Comment by dcalvoalonso** [comment]
Yes, I agree with you... I haven't found any example using `active` as payload field.

I will submit tomorrow a PR to fix it. ;)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/589
