### ISSUE TITLE
registration of protocols in the iot manager

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/iotagent-node-lib#590]
@fgalan @dcalvoalonso @dmoranj 
i am still trying to understand many details of the framework :) so please be patient with me :P 

some agents support multiple  communication protocols (e.g. UL supports HTTP, MQTT and AMQP), shouldn't all the protocols supported by a given deployment be self-registered in the IoT Manager in this case?

Thx for the hints!

**Comment by chicco785** [comment]
digging more, i realised that the actual protocol may be only UL or JSON. 
while HTTP, MQTT and AMQP are transportation. so only one registration is needed. i was confused by the config.js in UL that define the protocol as combination of UL and Transport.

is that correct? thx

```
    /**
     * Configuration for the IoT Manager. If the IoT Agent is part of a configuration composed of multiple IoTAgents
     * coordinated by an IoT Manager, this section defines the information that will be used to connect with that manager.
     */
    //iotManager: {
        /**
         * Host where the IoT Manager is located.
         */
        //host: 'localhost',

        /**
         * Port where the IoT Manager is listening.
         */
        //port: 8082,

        /**
         * Path where the IoT Manager accepts subscriptions.
         */
        //path: '/protocols',

        /**
         * Protocol code identifying this IoT Agent.
         */
        //protocol: 'MQTT_UL',

        /**
         * Textual description of this IoT Agent.
         */
        //description: 'MQTT Ultralight 2.0 IoT Agent (Node.js version)'
    //},
```

**Comment by fgalan** [comment]
This issue seems to be related to a question that I understand it is now answered. Is my interpretation correct @chicco785 ? Can the issue be closed?

**Comment by fgalan** [comment]
Closing issue. @chicco785 please tell otherwise, in the case the issue needs to be re-opened again.
