### ISSUE TITLE
missing support for authentication for NGSIv1 subscriptions

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/iotagent-node-lib#592]
current code does not provide any authentication means for subscriptions

**Comment by chicco785** [comment]
@fgalan just realised reading the issues that subscprition code may be deprecated

**Comment by fgalan** [comment]
To which particular issues do you refer, please?

**Comment by chicco785** [comment]
#558

**Comment by fgalan** [comment]
In fact, that issue was proposing a wrong thing (see last comment I have added to that issue)

Thanks for raising it... I have completely forgot about it :) Now #558 has been closed.

**Comment by chicco785** [comment]
so this means auth would be still a good thing to have, right?

**Comment by fgalan** [comment]
To have a global picture of this... which request from IOTA to ContextBroker are currently using authentication?

**Comment by chicco785** [comment]
Hi,
at the moment the only code using authentication (of any type) is in `ngsiService.js` (that covers only NGSI v1, till v2 is not officially integrated), endpoints support authentication in the code are:
- /v1/updateContext
- /v1/queryContext

I suspect this means that authentication support is also missing in other parts of the code behind the subscription part, for example in the `deviceService.js`, `createInitialEntity` operation and in all the operations in `registrationUtils.js` that create the registrations.

**Comment by fgalan** [comment]
> t the moment the only code using authentication (of any type) is in ngsiService.js (that covers only NGSI v1, till v2 is not officially integrated), endpoints support authentication in the code are:

Given that NGSIv2 integration (at least the first part, i.e. active attributes) is near to be integrated in the library, I'd suggest to hold on this issue until that moment, then reevaluate the list of endpoints.

What do you think @dcalvoalonso @chicco785 ?

**Comment by dcalvoalonso** [comment]
I agree @fgalan. We can finish first the integration of NGSIv2 and then address this new issue.

**Comment by chicco785** [comment]
as you prefer, we need authentication working for different cases,
including FIWARE foundation ones,
so we will go ahead.

**Comment by fgalan** [comment]
Considering the merging of PR #764 (not yet, but very soon), I understand this issue can be closed.

@dcalvoalonso @chicco785 could you confirm, pls?

**Comment by dcalvoalonso** [comment]
Yes, I think so.
