### ISSUE TITLE
missing support for https support in NGSIv1 subscription code

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/iotagent-node-lib#593]
when the device contains a specific context broker, the https is not correctly supported by subscriptions

**Comment by fgalan** [comment]
What do you mean by "the device contains a specific context broker" ?

**Comment by chicco785** [comment]
in case of using the device group and specifying an alternative context broker host, the code was not supporting the https case correctly.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-node-lib/pull/594 implements thiw for NGSIv1 subscriptions (i.e. `/v1/subscribeContext`). This issue will be keep opened until NGSIv2 subscriptions gets also supported (i.e. `/v2/subscriptions) once that work lands in master.

CC: @dcalvoalonso

**Comment by fgalan** [comment]
Considering the merging of PR #763 (not yet, but very soon), I understand this issue can be closed.

@dcalvoalonso @chicco785 could you confirm, pls?

**Comment by dcalvoalonso** [comment]
Yes, I think so.
