### ISSUE TITLE
missing support for device=true in the delete service endpoint

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/iotagent-node-lib#596]
According to the documentation of the Configuration API, when removing a service the following parameter should allow to remove all attached devices to the service:
* `device (optional, boolean)`. Default value is false. Remove devices in service/subservice. This parameter is not valid when Fiware-ServicePath is '/*' or '/#'.

**Comment by fgalan** [comment]
I understand this issue has been fixed by PR #597. Is that correct @chicco785  ?

**Comment by chicco785** [comment]
correct!
