### ISSUE TITLE
[iot/services] Many groups, one servicePath 

### ISSUE THREAD

**Issue by gabrieledeluca** [telefonicaid/iotagent-node-lib#604]
**CONFIGURATION API** 

I have more of one group on the same servicePath. I can call POST _/iot/services_ on order to create an array of services on a _servicePath_ and, in fact, these are stored on mongodb (groups table) correctly. But when I call the GET service in order to fetch all services related to the _servicePath_, service return only one service. Why?

**Comment by fgalan** [comment]
Maybe is a limitation of the current API

@dcalvoalonso what do you think?

**Comment by gabrieledeluca** [comment]
Yes, the problem happens when I use mongodb (as deviceRegistry option). In order to clarify, below you can find a query result on my db and the service response associated.

*************************
**MONGODB** 
*************************
Query: **db.getCollection('groups').find({})**

/* 1 */
{
    "_id" : ObjectId("5afae83e73dcc47d6fc914ed"),
    "cbHost" : "192.168.56.101:1026",
    "subservice" : "/demo",
    "service" : "opcua_car",
    "type" : "Car",
    "apikey" : "801230BJKL23Y9090DSFL123HJK09H324HV8732",
    "resource" : "/Car",
    "attributes" : [ 
        {
            "type" : "Number",
            "name" : "Engine_Temperature"
        }, 
        {
            "type" : "Number",
            "name" : "Engine_Oxigen"
        }
    ],
    "lazy" : [ 
        {
            "type" : "Number",
            "name" : "Speed"
        }
    ],
    "staticAttributes" : [],
    "commands" : [ 
        {
            "type" : "command",
            "name" : "Stop"
        }, 
        {
            "type" : "command",
            "name" : "Accelerate"
        }
    ],
    "__v" : 0
}

/* 2 */
{
    "_id" : ObjectId("5afae8a24db94a7dab06648b"),
    "cbHost" : "192.168.56.101:1026",
    "subservice" : "/demo",
    "service" : "opcua_car",
    "type" : "Car2",
    "apikey" : "801230BJKL23Y9090DSFL123HJK09H324HV8732",
    "resource" : "/Car2",
    "attributes" : [ 
        {
            "type" : "Number",
            "name" : "Engine_Temperature"
        }, 
        {
            "type" : "Number",
            "name" : "Engine_Oxigen"
        }
    ],
    "lazy" : [ 
        {
            "type" : "Number",
            "name" : "Speed"
        }
    ],
    "staticAttributes" : [],
    "commands" : [ 
        {
            "type" : "command",
            "name" : "Stop"
        }, 
        {
            "type" : "command",
            "name" : "Accelerate"
        }
    ],
    "__v" : 0
}


*************************
**GET SERVICES**
*************************

**curl -X GET \
  http://localhost:4041/iot/services/ \
  -H 'fiware-service: opcua_car' \
  -H 'fiware-servicepath: /demo'** 

**RESPONSE (BODY)** 
{
    "_id": "5afae83e73dcc47d6fc914ed",
    "cbHost": "192.168.56.101:1026",
    "subservice": "/demo",
    "service": "opcua_car",
    "apikey": "801230BJKL23Y9090DSFL123HJK09H324HV8732",
    "resource": "/Car",
    "attributes": [
        {
            "name": "Engine_Temperature",
            "type": "Number"
        },
        {
            "name": "Engine_Oxigen",
            "type": "Number"
        }
    ],
    "lazy": [
        {
            "name": "Speed",
            "type": "Number"
        }
    ],
    "commands": [
        {
            "name": "Stop",
            "type": "command"
        },
        {
            "name": "Accelerate",
            "type": "command"
        }
    ],
    "entity_type": "Car",
    "internal_attributes": [],
    "static_attributes": []
}

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/613
