### ISSUE TITLE
multientity with multiple measures

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#635]
a payload like 
```{"id":"thin:disp1","type":"thin","t":{"value":"20","type":"string"},"u":{"value":"30","type":"string"}}```

with these attributes:
```[{"value":"20","type":"string","name":"t"},{"value":"30","type":"string","name":"u"}]```

is simplified to:
```{"id":"thin:disp1","type":"thin","Temperature":{"type":"String","value":"30","object_id":"u"}}```

by https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/pluginUtils.js#L63

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/638
