### ISSUE TITLE
Maintain the ToC on Github whilst  hiding it on ReadtheDocs

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-node-lib#648]
Kind of related to the ToC discussion of #620 . I thought I'd raise an issue for discussion before trying anything out.

Q: Is the Table of Contents placed at the head of each markdown file:

1. Essential for navigating the documentation whilst on GitHub
2. Totally unnecessary and annoying whilst reading the documentation on ReadtheDocs
3. Both of the above

Personally I prefer viewing the documentation on RTD - I find the ToC pushes relevant information "below the fold" on each page - however I know it can't be removed since others navigate by using the GitHub Markdown.

I've been thinking that we could use CSS to style away the ToC on RTD by hiding the relevant `<ul>` as shown:

```css
h1:first-of-type+ul,
h2:first-of-type+ul{display: none}
```

This works fine and removes the contents of the ToC itself, but irritatingly would still leave the line `<h2>Contents</h2>` on screen - would it make sense to remove the `## Contents` line so both GitHub users and RTD users could be happy?

I mean do our users really need a sub-header to tell them that the list of links is a Table of Contents?

**Comment by fgalan** [comment]
Maybe the "trick" is not using the word "Content" for that, but the title of the page.

For instance, from Orion documentation, we have (https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/user/ngsiv2_implementation_notes.md):

![imagen](https://user-images.githubusercontent.com/1534240/44789363-abc71900-ab9c-11e8-992f-2cf730a69e0b.png)

Which in RTD renders (https://fiware-orion.readthedocs.io/en/master/user/ngsiv2_implementation_notes/index.html) as:

![imagen](https://user-images.githubusercontent.com/1534240/44789086-0613aa00-ab9c-11e8-874a-7a741dcc6857.png)

If I'm understanding correctly your proposal  (maybe I'm not :), using your idea, the table of content will not be diplayed in RTD so it would be shown something like that:

![imagen](https://user-images.githubusercontent.com/1534240/44789294-7fab9800-ab9c-11e8-9f69-5f7266b41cfc.png)

which from my point of view is fine.

What do you think?

**Comment by jason-fox** [comment]
That is the idea!  Any ToC  entries should be the first list on items  on the page and should **not** have a subtitle.

It shouldn't be:

```
# Meaningful Title
## Table of Contents
* xxxx
* xxxx
* xxxx
* xxxx
```

But 

```
# Meaningful Title
* xxxx
* xxxx
* xxxx
* xxxx
```

Removing the words **Table of Contents** is tricker as  the CSS for removing the first header preceding the first unordered list would need to be *CSS3* which I don't think is sufficiently supported yet - so the best thing is to delete the unnecessary words **Table of Contents**  instead.
