### ISSUE TITLE
Over-updating attributes at CB appart from the ones corresponding to the measure

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#654]
Given the following situation (case 1):

* A service provisioned for IoTA-UL using active attribute mapping (i.e. t -> temperature, h -> humidity, p-> pressure) and static attributes (location)
* A measure t=32 is received in IoTA-UL (i.e. autoprovisioned device)
* The entity at CB ends with temperature=32, but also humidity and pressure appear (with "" value)

A similar situation happens with measures that doesn't match any mapping (case 2):

* A service provisioned for IoTA-UL using active attribute mapping (i.e. t -> temperature, h -> humidity, p-> pressure) and static attributes (location)
* A measure mm=32 is received in IoTA-UL (i.e. autoprovisioned device)
* The entity at CB ends with mm=32, but also temperature, humidity and pressure appear (with "" value)

Thus, it seems that the IoTAgent is over-updating for attributes not included in the measure. Maybe the existence of static attributes in important in order to reproduce this case.

**Comment by AlvaroVega** [comment]
It seems that only happens with autorpovisioned devices.

**Comment by fgalan** [comment]
> That empty attributes are **only added at provision time**, not after a new measure comes. In autoprovision then that empty attributes are added as a provision result.

So you mean that case 1 above is actually correct behaviour, right?

**Comment by fgalan** [comment]
I understand that "case 2" has been solved with the following PRs:

https://github.com/telefonicaid/iotagent-node-lib/pull/873
https://github.com/telefonicaid/iotagent-json/pull/458
https://github.com/telefonicaid/iotagent-ul/pull/430

**Comment by AlvaroVega** [comment]
IMHO yes, case 2 is solved now

**Comment by fgalan** [comment]
Thus, case 2 solved and case 1 is correct behaviour. This issue can be closed.
