### ISSUE TITLE
Now (config.js )"timestamp: true" establish a common politic for the whole Agent It should be particular to each group/device

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-node-lib#655]
Now (config.js )"timestamp: true" establish a common politic for the whole Agent It should be particular to each group/device

**Comment by AlvaroVega** [comment]
```config.iota.timestamp``` should be preserved.

A new flag would be added to group model (timestamp).
https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/groups/groupRegistryMongoDB.js#L60
But what would be the meaning?
I think global config.iota.timestamp should apply to all devices. But if false, then if group contains timestamp then should be applied to current device.
