### ISSUE TITLE
[Bug] Alias plugin in NGSIv2 sends 

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#660]
Alias plugin sends `object_id` field as part of updateContext requests to Orion Context Broker, causing an error response.

This can be easily seen by modifying https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/ngsiv2/plugins/alias-plugin_test.js#114 to set log level to DEBUG and running:
```
node_modules/mocha/bin/_mocha test/unit/ngsiv2/plugins/alias-plugin_test.js
```

For instance, in the case of the last test:
```
{
    "url": "http://192.168.1.1:1026/v2/entities/light1/attrs",
    "method": "POST",
    "headers": {
        "fiware-service": "smartGondor",
        "fiware-servicepath": "gardens"
    },
    "json": {
        "configuration": {
            "type": "Object",
            "value": "string_value",
            "object_id": "c"
        }
    }
}
```

The problem is caused by https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/attributeAlias.js#L79, which was introduced in https://github.com/telefonicaid/iotagent-node-lib/commit/1bf213c71fb12fa1830cebf7fc4f979975acdcc9#diff-ff46611a8109d3e51a6de4533978a04c.

**Comment by dcalvoalonso** [comment]
It was not detected by the unit tests because it seems that the nock version we are using (9.0.14) does not check the value of additional fields which are not part of the mock payload.

I have seen several PR and commits that may be related to this bug:

https://github.com/telefonicaid/iotagent-node-lib/issues/635
https://github.com/telefonicaid/iotagent-node-lib/pull/639
https://github.com/telefonicaid/iotagent-node-lib/pull/638
...

@fgalan @AlvaroVega

**Comment by dcalvoalonso** [comment]
In order to illustrate a bit better this problem, I have done a PR that updates nock module to the last version: https://github.com/telefonicaid/iotagent-node-lib/pull/670

As you can see minor changes are required in the mocks to pass the tests in some cases. Nevertheless, the following tests are still failing:
- https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/ngsiv2/expressions/expressionBasedTransformations-test.js
- https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/ngsiv2/plugins/alias-plugin_test.js
- https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/ngsiv2/plugins/multientity-plugin_test.js

In all the cases, the problem is that the IOTA tries to send to the CB a payload that contains `object_id` field for the attributes.

**Comment by fgalan** [comment]
Just some doubts/questions, just to see if I'm understanding correctly...

So, appart from the unit test that has been adjusted in PR #670, there is a real bug in the implementation that makes IOTAgent sending incorrect requests to CB. Do you have an example of wrong NGSIv2 request? (you have  posted a JSON above, but it seems to be a "testing artifacts" used in the unit test code and it would be useful to see the one corresponding to the actual API call)

The bug has been recently introduced and wasn't in the code before the PRs you cite https://github.com/telefonicaid/iotagent-node-lib/issues/660#issuecomment-421041564, right? Is it the bug in the library (2.7.0)? Or was introduced after frozen it?

**Comment by dcalvoalonso** [comment]
The bug is present in the last release of the library (2.7.0) as I think it was introduced as part of a set of PR: #631, #636, #637,#638 and #639.

You can try an example of https://github.com/telefonicaid/iotagent-json but you have to comment line https://github.com/telefonicaid/iotagent-json/blob/master/lib/iotagent-json.js#137. 
I think that the problem is that https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/attributeAlias.js adds for NGSIv2 `object_id` fields in the entities in https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/attributeAlias.js#L79. In your integration tests we did not identify this bug because of https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/timestampProcessPlugin.js. This plugin in https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/timestampProcessPlugin.js#L75 creates a new NGSIv2 entity and somehow filters the `object_id` values.  I have detected this because, in https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN, we are not using so far this plugin.

**Comment by fgalan** [comment]
Thank you very much for the feedback. Now I think I have a clearer idea of what's going on :)

It is not a big problem, as currently Orion is ignoring extra fields within the attribute JSON (so, if an "object_id" field comes along with "value", "type" and "metadata" it just ignores it). However, it's ugly and will become a problem in the future if strict syntax checking is implemented (there is an issue in the Orion repository about it, see https://github.com/telefonicaid/fiware-orion/issues/1256).

If you have a proposal to fix it, please go ahead with it (I understand the best place is ongoing PR #670). Otherwise, tell us and we try to do our best to fix it.

Thanks!

**Comment by AlvaroVega** [comment]
Hi, @dcalvoalonso lora agent is using ngsi v1 or ngsi v2? SInce https://github.com/telefonicaid/iotagent-node-lib/pull/639 use ngsiv1 will not work fine with alias plugin

**Comment by dcalvoalonso** [comment]
@AlvaroVega @fgalan I have just tried to develop a possible fix for this issue in https://github.com/telefonicaid/iotagent-node-lib/pull/670.

Now, all the units tests are passed with the last version of nock module, not only for the https://github.com/telefonicaid/iotagent-node-lib but also for the IOTAs (JSON, UL and also LoRaWAN).

**Comment by fgalan** [comment]
I understand this issue has been fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/670

@dcalvoalonso should it be closed?

**Comment by dcalvoalonso** [comment]
Sure @fgalan ! Thanks!!
