### ISSUE TITLE
Static attributes sent to CB with every measure

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-node-lib#661]
Once a device is defined with static attributes, the static attributes are sent to CB with every measure received by the iotagent for that device.

In theory, this is the expected behaviour, (https://github.com/telefonicaid/iotagent-node-lib#device-provisioning-api) but it sounds sensible to update static attributes only during device creation  or during device update.

**Comment by fgalan** [comment]
A link to documentation describing the current behaviour should be added (we would need to change such  documentation if the implementation is changed).

**Comment by manucarrace** [comment]
Issue updated (https://github.com/telefonicaid/iotagent-node-lib#device-provisioning-api)

**Comment by AlvaroVega** [comment]
Similar to https://github.com/telefonicaid/iotagent-node-lib/issues/654 ?

**Comment by AlvaroVega** [comment]
Static attributes are always contacted to attribute update list by
https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/ngsi/ngsiService.js#L434

**Comment by fgalan** [comment]
> Similar to #654 ?

Yes, it is similar. Both discuss "overupdating" cases, although which attributes are "overupdated" are different in each issue.

**Comment by AlvaroVega** [comment]
Since a change in a static attribute is not notified to CB when a device is updated (issue https://github.com/telefonicaid/iotagent-node-lib/issues/662) this behavior is doing that.

**Comment by manucarrace** [comment]
Noted and understood
