### ISSUE TITLE
Static attributes not sent to CB in a device update operation

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-node-lib#662]
When a device update is issued, the IoTAgent does not send the static attributes to CB, it only sends to the CB the TimeInstant attribute. Even in the case that a static attribute is updated, the IoTAgent does not send the static attributes to the CB.

**Comment by fgalan** [comment]
A link to documentation describing the current behaviour should be added (we would need to change such documentation if the implementation is changed).

**Comment by AlvaroVega** [comment]
It is supposed done by: 
https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/deviceService.js#L831
https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/deviceService.js#L881

**Comment by AlvaroVega** [comment]
By definition a static attribute is supposed to not change.

**Comment by manucarrace** [comment]
Noted and understood
