### ISSUE TITLE
Support authentication with Oauth2 using FIWARE Keyrock IDM

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#663]
As it is explained in https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md, for the current implementation of OAuth2 based authentication:

> The code was tested using Keycloak and Auth0 (it may require customisation for other providers - while OAuth2 is a standard, not all implementations behave in the same way, especially as regards status codes and error messages.

Therefore, in order to support [FIWARE IDM Keyrock](https://github.com/ging/fiware-idm), we need to take into account the responses when an access token is asked.

In addition, the current implementation only covers the case of an IoT Agent sending updates to the CB, but the operations derived of a device provisioning request are not included.

**Comment by fgalan** [comment]
Implemented by PR #664

**Comment by fgalan** [comment]
PR #664 doesn't cover NGSIv2 support. It will be done in a separate PR. See https://github.com/telefonicaid/iotagent-node-lib/pull/664#discussion_r218820849

**Comment by fgalan** [comment]
After PR #664, PR https://github.com/telefonicaid/iotagent-node-lib/pull/726 lands the contribution into master.

**Comment by fgalan** [comment]
Now that PR #726 has been merged, should this issue be closed or is there something pending?
