### ISSUE TITLE
TimeInstant must consider timezone attribute

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#672]
With current implementation, TimeInstant values are always expressed using UTC timezone. The timezone attribute provided when a device or group is provisioned shall be used.

This has been requested by users:
https://stackoverflow.com/questions/35992228/fiware-idas-timeinstant-attribute
https://stackoverflow.com/questions/51428637/fiware-idas-ul-timeinstant-attribute

**Comment by fgalan** [comment]
I understand this has been implemented by PR #674 

@dcalvoalonso should this issue be closed?

**Comment by dcalvoalonso** [comment]
Sure! As always, thanks for your collaboration and feedback! :)
