### ISSUE TITLE
Support new versions of Node.js

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#681]
As Node.js 4 maintenance LTS cycle expired in April 2018 and Node.js 6 will do it in April 2019, we need to *officially* support Node.js 8 or even Node.js 10. Please take a look at https://github.com/nodejs/Release#release-schedule

In addition, we have detected that using Node.js 4 implies a higher use of RAM memory that may lead to out of memory errors.

@fgalan @jason-fox

**Comment by jason-fox** [comment]
To clarify, the suggestion here ongoing would be to use the **major** version number of the `iot-node-lib` library to indicate the underlying **node version** and  for each lib to have **different** npm dependencies if necessary.

- Add `.nvm`  files to each branch to emulate different node versions
- `npm audit fix —force`  to update dependencies
- Add node version to the `package.js` to fix to a specific node version for each  branch
- Each branch runs travis tests on one version of node only

... and the tests must run **green** of course before creating `4.x.x`, `6.x.x` and `8.x.x`

Once the node library and its dependencies are updated,  we can start testing  IoT Agents (JSON, Ultralight, LoRaWAN etc.) based on Node 8 using the `8.x.x` lib and updated dependencies which should close most vulnerabilities.

Updates thereafter will involve backporting changes to the older node branches

**Comment by dcalvoalonso** [comment]
@jason-fox I have just tried to see which is the impact of updating all dependencies with respect to the support of the current Node.js versions (4 and 6).
As you can see in https://github.com/telefonicaid/iotagent-node-lib/pull/682, it is quite easy to do the update, just a couple of very minor changes are required due to changes in mongodb and mongoose APIs.

Anyway, the conclusion is that an updated version of the iotagent-node-lib will not be compatible with Node.js v4.

Finally, after having updated all dependencies, we still have 18 vulnerabilities. All of them are related to dev-dependencies which are no longer maintained, e.g., grunt-github-pages.

**Comment by fgalan** [comment]
However, the "all green" for the four node versions in https://github.com/telefonicaid/iotagent-node-lib/pull/683 seems to probe that ioagent-node-lib is compatible with Node.js v4 (before updating any dependency)...

CC: @AlvaroVega

**Comment by dcalvoalonso** [comment]
You're right @fgalan but sooner or later we must update dependencies... @jason-fox Do you think that it is necessary to have one branch per Node.js version? So far the only problems seem to be related with Node.js v4...

**Comment by fgalan** [comment]
Could you elaborate on the problem in the travis Node.js v4 regression, pls? Which pacakge upgrade has caused it?

**Comment by jason-fox** [comment]
@dcalvoalonso At the moment I only see Node 4 as necessary right now, since it is legacy support. Node 6 will be necessary at some point (e.g. if the main code base is updated to ECMA6 or Node 6 reaches end of life)

I assume crux of the issue is the bundled npm version with each version of node - Node 8 ships with npm 5 for example and will have access to a different set of (potentially incompatible) drivers to earlier versions.

If grunt is no longer necessary I would remove it. It is perfectly possible to lint, test and run coverage direct with `npm run <script>`

e.g.:

```
    "lint": "jshint test/*.js test/**/*.js lib/*.js lib/**/*.js --config .jshintrc",
    "mocha": "mocha ./test/* ./test/**/* ",	    "mocha": "mocha ./test/* ./test/**/* ",
    "istanbul": "istanbul cover _mocha -- -R spec ./test/* ./test/**/*"	    
    "test:coverage": "istanbul cover _mocha -- -R spec ./test/* ./test/**/* && istanbul-coveralls"
```

The globs need tidying - that is all.

**Comment by dcalvoalonso** [comment]
I have tried to see which are the dependencies causing problems in Node.js v4: https://github.com/telefonicaid/iotagent-node-lib/pull/684

- logops: causes the following error: `Block-scoped declarations (let, const, function, class) not yet supported outside strict mode``
- query-string: One unit test fails. Maybe we could fix it.
- grunt: causes the following error: `The package grunt@1.0.3 does not satisfy its siblings' peerDependencies requirements!`
- sinon: It seems that it the highest version that can be installed with Node.js v4.

@fgalan What do you think about removing grunt? If we can achieve the same functionality with npm as @jason-fox  proposed, for me it is OK.

**Comment by dcalvoalonso** [comment]
Following https://github.com/telefonicaid/iotagent-node-lib/issues/681#issuecomment-432142644, I have removed Grunt and created a set of npm scripts which should replace previous functionality.
**I have also removed some unused dependencies and the result is that so far there are no vulnerabilities and just two dependencies avoid maintaining support to Node.js v4: logops and query-string.**

In the former case, I think that we can go on without updating it, it's nothing especially critical, and I can try to fix the test that fails for query-string.

**Comment by jason-fox** [comment]
Grunt as a task runner has dependencies which in turn may expose additional vulnerabilities and may not be upgradeable in some circumstances. The idea here is to minimize the total number of libraries we are depending on and therefore make maintenance simpler in the future.

If grunt is not needed and not adding value let's delete it - simplify the code base, just rely on `npm`.

I would assume that the other remaining grunt tasks are just [lava code](http://antipatterns.com/lavaflow.htm)

**Comment by dcalvoalonso** [comment]
In https://github.com/telefonicaid/iotagent-node-lib/pull/682, following @jason-fox suggestion in https://github.com/telefonicaid/iotagent-node-lib/issues/681#issuecomment-432142644, I have implemented all these tasks just with npm.
The problem also with some of the grunt-related dependencies we are using is that they are not maintained any more, e.g., 
- https://www.npmjs.com/package/grunt-dox: Last version published 5 years ago.
- https://www.npmjs.com/package/grunt-exec: Last version published 1 year ago.
- https://www.npmjs.com/package/grunt-githooks: Last version published 3 years ago.
My feeling is that if we remove grunt, we could even achieve to update almost all dependencies and maintain support for Node.js v4 at the same time.

**Comment by fgalan** [comment]
I understand this issue is already covered by the ongoing work (for instance PRs https://github.com/telefonicaid/iotagent-node-lib/pull/683 and https://github.com/telefonicaid/iotagent-node-lib/pull/682) and issues #699 and #700.

Thus, I'd suggest to close this issue.

**Comment by dcalvoalonso** [comment]
I agree, let's close it!
