### ISSUE TITLE
createInitialEntityNgsi2 and other methods are not using the service group cbHost but the global one

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/iotagent-node-lib#685]
this means that currently a different cbHost per deviceGroup is not properly supported

**Comment by chicco785** [comment]
it looks to me that the problem is quite deep (the feature of cbHost for a specific device group was probably not properly tested), since device data used in the different communications are not "merged" anyhow with the group data.

**Comment by chicco785** [comment]
I have already a partial fix, i need only to complete the tests (which
is more painful than solving the issue :P) hope to complete by the end
of this week

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-node-lib/pull/697 addresses this issues, at least partially.

@chicco785 what do you think? Is the fix in the same line than the one you proposed? Could the test you say are finalizing be a contribution to cover the fix?

**Comment by fgalan** [comment]
After merging PR #697, could this issue be closed? Or is some piece of work pending and should keep opened?

@chicco785 what do you think?
