### ISSUE TITLE
Upgrade logops to 2.1.0 

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#689]
As we are still supporting Node.js v4, we cannot update logops to the latest version (2.1.0 ). Further details can be seen in https://github.com/telefonicaid/iotagent-node-lib/pull/682.

Once Node v4 goes away, it will be removed from travis-ci and we shall update logops.

This decision was taken after considering the alternatives in https://github.com/telefonicaid/iotagent-node-lib/pull/682#pullrequestreview-169451203.

**Comment by fgalan** [comment]
We have been discussing about removing Node v4 in this repository by the end of year (2018). That would the moment to address also this issue (maybe even in the same PR).

**Comment by fgalan** [comment]
In closing this issue in favour of more general #699
