### ISSUE TITLE
Remove XML related code

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#691]
As XML payloads are not used anymore by any IoT Agent nor NGSI, it would be good to remove xmldom dependency and all the code related to support this functionality.

This was agreed and discussed as part of https://github.com/telefonicaid/iotagent-node-lib/pull/682#pullrequestreview-169446079

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/724
