### ISSUE TITLE
Remove Node v4

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#699]
(To be addresses in January 2019)

Node v4 will be removed by the end of 2018. In particular, this issue involves the following actions:

* Node v4 should be removed from .travis.yml
* engine version should be modified to be >=6 in packages.json
* logops library should be updated to 2.1.0 in packages.json

**Comment by fgalan** [comment]
I'm also a big fan of linters :) However, when the linter goes beyong simple fixes like line length, indent, syntax cleanup, etc. and starts to involve changes in programming patterns (such as using `async await` instead of callbacks) things needs to be thougth with care.

Thus, I agree in doing it by stages, starting with the simple fixes and let deep changes for the end.

By the way, we are currently using `jshint` for linting. Should I understand that `eslint` is a better tool (I didn't know it)? Do you have some introductory reference about it or a comparison? Thanks!

**Comment by jason-fox** [comment]
From https://www.sitepoint.com/comparison-javascript-linting-tools/

> ESLint is also the obvious choice if you want to use ES6 (or ES2015, as they seem to be calling it now). Of all the tools mentioned, it has the widest support for ES6 features.

We could introduce `Husky` with `JsLint` right away (to see that it performs correctly) and then update the linter to `Eslint` when Node v4 is finally dropped

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/iotagent-node-lib/pull/723
