### ISSUE TITLE
Authentication iotagent configuration is not supported by conf env vars

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#704]
Authentication iotagent configuration is not supported by conf env vars:
https://github.com/telefonicaid/iotagent-node-lib/blob/master/config.js#L34

```
 authentication: {
         enabled: false,
         type: 'keystone',
         header: 'X-Auth-Token',
         host: 'localhost',
         port: '5000',
         user: 'iotagent',
         password: 'iotagent'
 },    
```
and is needed by docker container

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/705
