### ISSUE TITLE
Alias resulting in the same name may fail in combination with multi entity plugin

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#711]
For instance, in the next examples we have diferent object_id (count1, count2, etc.), all them maping to the same attribute (name) but different entities (SO1, SO2, etc.).

```
"active" : [ 
{
"type" : "number",
"name" : "vol",
"object_id" : "cont1",
"entity_name" : "SO1",
"entity_type" : "WM"
}, 
{
"type" : "number",
"name" : "vol",
"object_id" : "cont2",
"entity_name" : "SO2",
"entity_type" : "WM"
}, 
{
"type" : "number",
"name" : "vol",
"object_id" : "cont3",
"entity_name" : "SO3",
"entity_type" : "WM"
}, 
{
"type" : "number",
"name" : "vol",
"object_id" : "cont4",
"entity_name" : "SO4",
"entity_type" : "WM"
}, 
{
"type" : "number",
"name" : "vol",
"object_id" : "cont5",
"entity_name" : "SO5",
"entity_type" : "WM"
}
```

```
curl -i -X GET 'http://localhost:7896/iot/d?k=...&i=disp1&d=|cont1|38'
```

It may be related with the removal of object_id done at PR #670 to fix bug #660.

**Comment by fgalan** [comment]
This issue is tough. We are researching it. See PR #709

**Comment by dcalvoalonso** [comment]
I can try to help you @fgalan. Maybe we could start by adding some unit tests in a separate branch that demonstrate the bug and the expected functionality.

**Comment by fgalan** [comment]
@AlvaroVega is looking into this in paralllel, but of course help is hightly welcome :)

The unit test should be as follows:

* Provision an entiy as the one shown inthe example, i.e. diferent object_id (count1, count2, etc.), all them maping to the same attribute (name) but different entities (SO1, SO2, etc.).
* Send a measure, i.e. cont1=38
* Ensure that only the entity associated to cont1 (i.e. SO1) has its vol modified. All the other entities (SO2, etc.) are untouched.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/712

**Comment by fgalan** [comment]
Additional test added in PR #714. The issue can be considered solved.
