### ISSUE TITLE
Usage of context availability subscriptions in IOTAs

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#715]
This isssue is an spin off from https://github.com/telefonicaid/iotagent-node-lib/issues/701.

Q (@fgalan): In which scenario are IOTAs using context availability subscriptions? Or it is just a feature implemented some place in the library but actually never used?

A (@dcalvoalonso): As you can see in https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/deviceService.js#L624, all the IOTAs send context availability registrations each time a new device is provisioned. I understand that this feature is needed for lazy attributes and commands:
> Lazy attributes: some sensors will be passive, and will wait for the IoT Agent to request for data. For those measures, the IoT Agent will register itself in the Context Broker as a Context Provider (for all the lazy measures of that device) ...
> Commands: in this case, the interaction will begin by setting an attribute in the device's entity, for which the IoT Agent will be registered as CP...

Source: https://github.com/telefonicaid/iotagent-node-lib#device-to-ngsi-mapping

**Comment by fgalan** [comment]
I'm looking to https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/deviceService.js#L624 but I don't see the point in which context availiability subscription is performed

Maybe the code has moved and now that reference is not valid?

**Comment by dcalvoalonso** [comment]
In https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/deviceService.js#L630, `registrationUtils.sendRegistrations` is called. You can see in https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/registrationUtils.js#346 the content of this function. For instance, in https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/registrationUtils.js#238, you have the code for NGSIv2.

**Comment by fgalan** [comment]
Thanks for the links.

I have tried to follow the code and, although I see how registration is done (either `POST /v2/registrations` or `/NGSI9/registerContext`) I don't see the place in which context availability subscription is done.

Moreover, I have looked for "subscribeContextAvailability" in all the code base (as the operation to create new context availability subscriptions is either `POST /NGSI9/subscribeContextAvailability` or `POST /v1/registry/subscribeContextAvailability` without any result: https://github.com/telefonicaid/iotagent-node-lib/search?q=subscribeContextAvailability&unscoped_q=subscribeContextAvailability

So probably when I said "subscribe context availability" you understood "context registration" and are now missunderstanding each other? :)

**Comment by fgalan** [comment]
> So probably when I said "subscribe context availability" you understood "context registration" and are now missunderstanding each other? :)

In fact, probably is the other way arround... you first used "context availability registration" term in #701 and I continue with "context availability subscription". Sorry for that...

Let's start over. Claritying terms:

* context availability registration -> `POST /v2/registrations`, `POST /NGSI9/registerContext` or `POST /v1/registry/registerContext`
* context availability subscription -> `POST /NGSI9/subscribeContextAvailability` or `POST /v1/registry/subscribeContextAvailability`

My guess is that:

* IOTAs do context availibity registrations operations on CB (during the provisioning process)
* IOTAs never do context availibity subscriptions on CB

Is my interpretation correct?

**Comment by dcalvoalonso** [comment]
Sorry for the confusion @fgalan, sometimes I find difficult to differentiate these concepts.

> My guess is that:
> 
> IOTAs do context availibity registrations operations on CB (during the provisioning process)
> IOTAs never do context availibity subscriptions on CB

You are completely correct! :)

**Comment by fgalan** [comment]
Thanks for the clarification. So, I think the discussion is over and this issue can be closed.
