### ISSUE TITLE
Travis CI not working for node v4

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#718]
It seems that travis CI is not working properly for node v4. It always report ok, even when there are fails in unit tests.

For instance

![imagen](https://user-images.githubusercontent.com/1534240/48828084-21431f80-ed6f-11e8-9884-9b7d62d98c52.png)

However, maybe it doesn't worth the effort to fix it, given that node v4 will be removed in less than 2 months. What do you think @dcalvoalonso ?

**Comment by dcalvoalonso** [comment]
Going to back a previous version of Nock would fix most of the tests. Nevertheless, I agree with you... we are going to deprecate this in a very short time so I would not spend more effort fixing this.
