### ISSUE TITLE
Wrong mirror webhook config

### ISSUE THREAD

**Issue by caa06d9c** [telefonicaid/iotagent-node-lib#725]
Please, change the mirror webhook config as described [here](https://fiware-requirements.readthedocs.io/en/latest/repo_webhook/index.html)

**Comment by fgalan** [comment]
Updated. Now it looks like:

![imagen](https://user-images.githubusercontent.com/1534240/49785619-798f9080-fd21-11e8-86b4-a7161af96b22.png)

Please check if it is working now and close the issue in that case. Thx!

**Comment by caa06d9c** [comment]
It works. Thanks
