### ISSUE TITLE
[Documentation] README.md minor mistake

### ISSUE THREAD

**Issue by dherykw** [telefonicaid/iotagent-node-lib#738]
I have found a minor mistake in the documentation, in the *Device to NGSI Mapping* section, lazy attributes description, last line (until **_de_** device):

Lazy attributes: some sensors will be passive, and will wait for the IoT Agent to request for data. For those measures, the IoT Agent will register itself in the Context Broker as a Context Provider (for all the lazy measures of that device), so if any component asks the Context Broker for the value of that sensor, its request will be redirected to the IoT Agent (that behaves as an NGSI10 Context Provider). This operation will be synchronous from the customer perspective: the Context Broker won't return a response until **_de_** device has returned its response to the IoT Agent.

Best

**Comment by fgalan** [comment]
Thanks for the report! Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/741

If you find some similar one you can create a fixing PR if you want instead of creating an issue.
