### ISSUE TITLE
[MUST] Show versioned documentation

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-node-lib#754]
On the IoT Node Lib ReadtheDocs project, no versioned documentation is displayed

- Goto https://readthedocs.org/projects/iotagent-node-lib/versions/
- Ensure that **active** checkmark is ticked against relevant release tags

**Comment by fgalan** [comment]
Done (added 2.8.0, 2.7.0 and 2.6.0). Please have a look and close it is you find it solved. Thanks!

**Comment by jason-fox** [comment]
:+1:
