### ISSUE TITLE
Setting up oauth2 authentication with keyrock IDM

### ISSUE THREAD

**Issue by letavia** [telefonicaid/iotagent-node-lib#761]
Hola,

I am trying to set up authentication for my IoT Agent using oauth2 method. Here is the configuration in the config.js file:

```
{
        enabled: true,
        type: 'oauth2',
        url: 'http://<keyrock_host>:3000',
        header: 'Authorization',
        clientId: <client_id of application in keyrock>,
        clientSecret: <client_secret of application in keyrock>,
        tokenPath: '/oauth2/token',
        permanentToken: true
    }
```

Is this the correct configuration?
And to my knowledge when we do service and device provisioning, we have to include a parameter called "trust", but I am not sure what to put in as the trust. 

Also, what is the expected behavior when we have enabled authentication? I tried the provisioning through north port (default: 4041) without x-auth-token header and it went through. Is the token similar to the token we are using to access context broker through pep-proxy (I have my context broker behind pep-proxy)?

Thanks for any help.

**Comment by fgalan** [comment]
I'm CCing @chicco785 @dcalvoalonso 

I wasn't be personally involved in the OAuth2 implementation in the library but I think they were (in some degree at least) so maybe can help.

**Comment by letavia** [comment]
Thanks @fgalan 
@chicco785 @dcalvoalonso can you help with my questions?

**Comment by chicco785** [comment]
assuming you use the last version of keyrock, check here the discussion on permanent token:
https://fiware-idm.readthedocs.io/en/latest/oauth/oauth_documentation/index.html

in "trust" you will need to store a permanent token. the authentication discussed here covers the fact that the agent can communicate with a protected context broker, it is not related with protecting the access to the iot agent, for that you need to configure in front of it a pep and proper policies

**Comment by dcalvoalonso** [comment]
So just to try to contribute clarifying your doubts:
- If you want to protect the north interface of your IoT Agent, then you must deploy a PEP Proxy and do a similar configuration to the one you have for the Context Broker. But this is completely transparent to the IoT Agent, you don't need to configure anything nor to introduce additional parameters in the device or service provisioning.
- If your IoT Agent must work against an Orion Context Broker which is behind a PEP Proxy, then you need to configure OAuth2 authentication. This consists of the following steps:
  1. To modify the config.js file with authentication information. Please check https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md for further information.
  2. To introduce `trust` token in the service provisioning as it is explained in https://github.com/telefonicaid/iotagent-node-lib#post-iotservices. This `trust` token in the case of FIWARE KeyRock is a refresh_token or permanent token.
3. To do the device provisioning using the group of the previous step.

After this process, the IoT Agent will automatically retrieve access tokens from KeyRock and use them to send requests to the Context Broker.

**Comment by letavia** [comment]
Actually I am looking at both applications, protecting the north and south interface, but lets talk about the south first. My context broker is working fine behind the pep-proxy so I am using the configuration for the context broker (client_id and client_secret) in the keyrock to configure config.js as you suggested.
I did the service provisioning using the token (the same token to access context broker through pep-proxy) as the trust and did the device provisioning based on the service. 
Then I sent data through south interface of the IoT Agent to change the value of the device parameter without any token (no x-auth-token header) and it went through to context broker.

Did I miss something here? Shouldn't the scenario protect south interface from updating device data in context broker?

**Comment by dcalvoalonso** [comment]
> I did the service provisioning using the token (the same token to access context broker through pep-proxy) as the trust and did the device provisioning based on the service.
Then I sent data through south interface of the IoT Agent to change the value of the device parameter without any token (no x-auth-token header) and it went through to context broker.

This is the expected behaviour. What you are actually doing is to configure the IoT Agent to obtain an OAuth2.0 token from keyrock so that the requests done by the IoT Agent to the Context Broker contain the x-auth-token and therefore authentication can be checked by the PEP Proxy. To sum us, what you are doing here is to configure the IoT Agent to as an OAuth2.0 client.

> Actually I am looking at both applications, protecting the north and south interface, but lets talk about the south first.

As we explained in some previous comments. This is completely transparent to the IoT Agent and independent of the service provisioning, etc. If you want to protect the south interface of your IoT Agent you just need to follow the same approach as with the Context Broker:
1. Register the IoT Agent as an application in the IDM KeyRock.
2. Register a new PEP Proxy for the IoT Agent application in the IDM KeyRock.
3. Deploy a new PEP Proxy and modify the configuration with the details obtained in the previous steps.
4. Your sensor should obtain an access_token from KeyRock using some of the flows explained in https://fiware-idm.readthedocs.io/en/latest/oauth/oauth_documentation/index.html to report new observations.

**Comment by letavia** [comment]
> This is the expected behaviour. What you are actually doing is to configure the IoT Agent to obtain an OAuth2.0 token from keyrock so that the requests done by the IoT Agent to the Context Broker contain the x-auth-token and therefore authentication can be checked by the PEP Proxy. To sum us, what you are doing here is to configure the IoT Agent to as an OAuth2.0 client.

Ok I get how it works now, but why when I am using invalid token as the trust it still gets through as if pep-proxy does not function here (I don't see any configuration for pep-proxy, only context-broker).  If I look at the logs, IoT Agent passes through the command straight to the context-broker, hence token is not validated with IDM (you need to pass through pep-proxy to validate the token).

About the other procedures to protect IoT with pep-proxy, I understand you can set up a pep-proxy for each IoT Agent, but I think it would be overkill. In the application configuration in IDM keyrock, there's a section to register IoT sensors. Can we use this instead to protect the sensors by using the pep-proxy for the application?

**Comment by dcalvoalonso** [comment]
> Ok I get how it works now, but why when I am using invalid token as the trust it still gets through as if pep-proxy does not function here (I don't see any configuration for pep-proxy, only context-broker). If I look at the logs, IoT Agent passes through the command straight to the context-broker, hence token is not validated against IDM Keyrock (you need to pass through pep-proxy to validate the token).

In the configuration of the IoT Agent, have you specified the port of the Orion Context Broker directly or the one exposed by the PEP Proxy?

> About the other procedures to protect IoT with pep-proxy, I understand you can set up a pep-proxy for each IoT Agent, but I think it would be overkill. In the application configuration in IDM keyrock, there's a section to register IoT sensors. Can we use this instead to protect the sensors by using the pep-proxy for the application?

If I am not wrong, the option to register IoT sensors in KeyRock allows generating an ID/password to get access tokens by means of a grant type Resource Owner Password Credentials. With this token, you could send requests to an IoT Agent which is protected by a PEP Proxy. You must note that checking if a request contains a valid access token and checking it against KeyRock is out of the scope of the IoT Agent functionalities. Of course, this could be implemented but to be honest I don't see the benefit so far. :)

**Comment by letavia** [comment]
> In the configuration of the IoT Agent, have you specified the port of the Orion Context Broker directly or the one exposed by the PEP Proxy?

Yes, I just figured it out. It works as I expected now.

I think you are correct about Keyrock IoT sensors registration, it's just a way to generate tokens to be used to access application behind the pep-proxy. I was initially thinking to protect the north port of IoT Agent to control the provisioning of the devices with tokens assigned to the devices respectively, but that does not seem how it works because Keyrock does not provide authorization for registered IoT sensors (yet, I hope).

**Comment by dcalvoalonso** [comment]
OK @letavia. Could we close the issue then?

**Comment by letavia** [comment]
Yes. Thanks a lot for your help! @dcalvoalonso

**Comment by dcalvoalonso** [comment]
You're more than welcome! I don't have enough privileges on this repo so you can close the issue yourself. :)
