### ISSUE TITLE
Unit tests are not passed

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#774]
As can be seen in the history, from e71712cfed94e424af36091568485d641298a821, unit tests are not passed in the master branch.

**Comment by fgalan** [comment]
I'm looking to the last commit and it seems test are being passed::

![imagen](https://user-images.githubusercontent.com/1534240/56113591-98679300-5f5e-11e9-8958-071127d9026e.png)

What is seem to "fail" is the coverage check... However a decreae in coverage of 0.02% is ok with me :)

**Comment by dcalvoalonso** [comment]
Upssss.... Sorry, you are more than right! :S
