### ISSUE TITLE
Fiware Summit  2019 - Lib Porting efforts

### ISSUE THREAD

**Issue by chopmann** [telefonicaid/iotagent-node-lib#785]
Several Attendees have expressed the intention/need of porting this library to another language (c++, golang, rust..) to enable low-power devices to connect directly to NGSI Context Brokers without the need of a "Gateway".

This Issue should collect some of the open questions gathered at the Summit

@jason-fox

**Comment by fgalan** [comment]
The idea of the IOTA architecture is that the device (probably low powered, as you say) runs a very simple piece of software to use a native protocol (MQTT for instance) to send measures to the IOTA, which runs in another place (e.g. the cloud). The device can implement the native protocol in C/C++ or even in more efficient tecnologies and low level technologies (FPGA, etc.), depending the case. Thus, this is not a matter or porting the library to another language from my point of view.

In other words, IOTAs are not intended to execute into devices. Devices, specially low-power devices would prefer to use an specific comunication prototol, lighter that NGSI. Moreover IOTAs are intended to manage large groups of devices, it makes no sense to use one instance for one device. If you just want to make your devices send NGSI it 's not a good solution to employ IOTAs for this also.

Or maybe I don't understanding the use case (in which case I'd suggest to expand it adding more information as comment to this issue).

**Comment by chopmann** [comment]
@fgalan thank you for the clarification.

**Comment by fgalan** [comment]
You're welcome! :)
