### ISSUE TITLE
[Discuss] Should IoT Agents use pm2?

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-node-lib#790]
There is lots of interesting discussion about whether to use `pm2` within a Dockerized deployment. Whether it is a good idea, a bad idea or whatever. My thought on this is that we should probably be agnostic on this and leave that decision down to the DevOps in question.

At the moment we install `pm2` as part of the `Dockerfile` and  hard-code use of `pm2` in the `entrypoint.sh`, I would suggest adding an environment variable switch to either invoke using `pm2` or invoke using node directly.

Something like:

```bash
if [ "$USE_PM2" != "" ]
then
  echo "IoT Agent encapsulated by pm2-runtime see https://pm2.io/doc/en/runtime/integration/docker/"
  pm2-runtime bin/iotagent-json
else
  echo "IoT Agent running standalone"
 node bin/iotagent-json
fi
```

Questions

-  Is this a good option?
-  Should we start extending `keymetrics/pm2:10-slim`?
- What should the name of the `ENV` be?
- Which other FIWARE components could also be aligned?

Related: 
- https://github.com/Unitech/pm2/issues/1879
- https://github.com/conwetlab/ngsi-proxy/pull/9

I'd be interested in your opinions on this: @dcalvoalonso @fgalan @aarranz

**Comment by fgalan** [comment]
Your idea seems to be the most flexible option. The price to pay is a more complex entrypoint.sh file, but I think is not too much complexity increase so probably it worths the change.

With regards to env var name, all IOTA env vars use an `IOTA_` prefix. However, if this is going to have a wider usage in other GE based in node (Perseo FE, STH, etc.) maybe something more neutral should be used. USE_PM2 is not a bad name. ENABLE_PM2 and RUN_WITH_PM2 could be other alternatives. Any other suggestion?

Doubt: what do you mean by _"Should we start extending `keymetrics/pm2:10-slim?`"_. Could you elaborate a little bit, please?

**Comment by jason-fox** [comment]
Currently  a typical `Dockerfile` starts.

```Dockerfile
ARG NODE_VERSION=8.16.0-slim
FROM node:${NODE_VERSION}
... etc
RUN npm install pm2@3.2.2 -g
..etc
```

It could be altered to:

```Dockerfile
ARG NODE_VERSION=10-slim
FROM keymetrics/pm2:${NODE_VERSION}
```

and extend from the `keymetrics/pm2` image.


There is also the side issue of when to update default node used within the Docker image (i.e. from **Node 8** to **Node 10**)  This does not _necessarily_ need to occur at the same time as deprecating Node 8.

**Comment by fgalan** [comment]
If the pm2 usage were fixed (as it is now) then `keymetrics/pm2` could be an option to take into account. But given it would be option through the PM2_USE (or other name) variable, then I think is better to keep using the official node images at dockerhub.

**Comment by fgalan** [comment]
PRs addressing this issue in the different IOTA repositories:

* https://github.com/telefonicaid/sigfox-iotagent/pull/58
* https://github.com/telefonicaid/lightweightm2m-iotagent/pull/196
* https://github.com/telefonicaid/iotagent-ul/pull/378
* https://github.com/telefonicaid/iotagent-json/pull/415
* https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/pull/79

**Comment by fgalan** [comment]
Almost done. Only PR https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/pull/79 seems to be pending now.

**Comment by jason-fox** [comment]
@fgalan - I believe this issue can be closed.

**Comment by fgalan** [comment]
Given that https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/pull/79 was already merged, yes I think it can be closed.
