### ISSUE TITLE
Device auto-provision per device group

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-node-lib#805]
In current implementation there is a configuration parameter in config.js called  "appendMode" which specifies the way the IoT Agent delivers the measures to Context Broker (append, update, appendstrict, ..)

It would be nice to extend this functionality to be able to change this parameter in order to apply per device group (apikey). This way, a given device group would be changed to accept or not the creation of new entities in Context Broker.

Moreover, it would be nice to avoid the creation of new auto-provisioned devices. (nice to have)

**Comment by fgalan** [comment]
> Moreover, it would be nice to avoid the creation of new auto-provisioned devices

It could be a flag in the provisioning JSON, i.e. "autoprovision": true|false (default is true, to keep backward compatibility).

**Comment by AlvaroVega** [comment]
This is something similar to the work done for timestamp

**Comment by AlvaroVega** [comment]
This issue was implemented in agents:
https://github.com/telefonicaid/iotagent-ul/pull/384
https://github.com/telefonicaid/iotagent-json/pull/431
