### ISSUE TITLE
[feature request] mongodb authentication

### ISSUE THREAD

**Issue by SamuelTJackson** [telefonicaid/iotagent-node-lib#844]
Hi,
it should be possible to set the mongodb username, password and authdb. 

something like:
| Environment variable      | Configuration attribute         |
| :-----------------------    | :------------------------------ |
| IOTA_MONGO_USER           | `mongodb.user`                  |
| IOTA_MONGO_PASSWORD       | `mongodb.password`              |
| IOTA_MONGO_AUTH_DB        | `mongodb.authDB`                |

**Comment by fgalan** [comment]
It sounds interesting and it shouldn't be complex (just a matter of using the new parameters in the point of the code in which the connection to MongoDB is done).

It would be great if somebody supporting the use case (i.e. using MongoDB server with authentication) could provide the implementation. We will be more than happy to review the pull request with this :)

Thanks for the feedback!

**Comment by SamuelTJackson** [comment]
I'm not an expert in javascript but this is my suggestion. Maybe it helps:
https://github.com/telefonicaid/iotagent-node-lib/blob/09048b9f0a799bff3ee394790c23c47bec5af727/lib/commonConfig.js#L87 insert:
```
'IOTA_MONGO_USER',
'IOTA_MONGO_PASSWORD',
'IOTA_MONGO_AUTH_DB',
```
https://github.com/telefonicaid/iotagent-node-lib/blob/09048b9f0a799bff3ee394790c23c47bec5af727/lib/commonConfig.js#L109 insert:

```
'IOTA_MONGO_USER',
'IOTA_MONGO_PASSWORD',
'IOTA_MONGO_AUTH_DB',
```

https://github.com/telefonicaid/iotagent-node-lib/blob/09048b9f0a799bff3ee394790c23c47bec5af727/lib/commonConfig.js#L290 insert:

```
if (process.env.IOTA_MONGO_USER) {
        config.mongodb.user = process.env.IOTA_MONGO_USER;
}

if (process.env.IOTA_MONGO_PASSWORD) {
        config.mongodb.password = process.env.IOTA_MONGO_PASSWORD;
}
if (process.env.IOTA_MONGO_AUTH_DB) {
        config.mongodb.authDB = process.env.IOTA_MONGO_AUTH_DB;
}
```
https://github.com/telefonicaid/iotagent-node-lib/blob/09048b9f0a799bff3ee394790c23c47bec5af727/lib/model/dbConn.js#L197 insert:

```
if (currentConfig.mongodb.user && currentConfig.mongodb.password) {
   currentConfig.username = currentConfig.mongodb.user;
   currentConfig.password = currentConfig.mongodb.password;
}

if (currentConfig.mongodb.authDB) {
  options.authDB = {auth_db: currentConfig.mongodb.authDB};
}
```
https://github.com/telefonicaid/iotagent-node-lib/blob/09048b9f0a799bff3ee394790c23c47bec5af727/lib/model/dbConn.js#L91 insert:

```
if (options.authDB) {
        var delimiter = options.replicaSet ? '&' : '?';
        url += delimiter + 'authSource=' + options.authDB.auth_db;
}
```

https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md add new varialbes:
| IOTA_MONGO_USER           | `mongodb.user`                  |
| IOTA_MONGO_PASSWORD       | `mongodb.password`              |
| IOTA_MONGO_AUTH_DB        | `mongodb.authDB`                |

**Comment by SamuelTJackson** [comment]
I'm not allowed to create a new branch for a pull request, am I?

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/846
