### ISSUE TITLE
Leading slashes in MQTT topic

### ISSUE THREAD

**Issue by jmezzera** [telefonicaid/iotagent-node-lib#866]
Today I came across with a post in a forum that stated leading slashes in MQTT topics are a bad practice (first level of hierarchy being null). It made sense and I started looking for other references of this idea and found a lot of them.

Is there any reason the agents use this nomenclature? Should it be changed?

**Comment by AlvaroVega** [comment]
Could you share with us any of that references?

**Comment by jmezzera** [comment]
Sure!
[Here's](https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/) one that's been quoted in several post and issues from other projects.
I get it's not mosquitto, but it should be considered a decent source.

**Comment by AlvaroVega** [comment]
Thanks for your point!
Since beginning we iot-agents are using topics which starts by '/', so currently many apps are using it. We would like to accepts topics without initial `/` but always keeping the posibility (i.e. by a configuration flag) of usage previous topics with the initial '/'

**Comment by fgalan** [comment]
@jmezzera given that you have identified the issue and I understand have the need to use topics without / prefix, maybe it's a good idea you develop the contribution to the code (in both IOTA-UL and IOTA-JSON) with the configuration flag that @AlvaroVega is proposing, please?

We would be more than happy to review your contribution :)

**Comment by jmezzera** [comment]
@AlvaroVega  I totally agree with you, I know this has to be managed carefully so it does not break any existing configurations. In fact, I personally use the leading slash.

@fgalan let me see if I have time to look into this.

>  I understand have the need to use topics without / prefix

Actually no, it was a suggestion I received and wanted to share it with the community.
This does not mean I'm not willing to try and improve the solution.

**Comment by jmezzera** [comment]
I had a look to the source and this is what I have in mind:
* Instead of making it an Either Or case (allow leading slashes or not), allow both (i.e. subscribe the agent to all combinations - with and w/o `/` at the beginning). In this case, it will be listening to any message. This would imply a bit more of logic when parsing the message
* The problem arises when the agent has to publish to some topic (send config or a command). In this case, I would take @AlvaroVega's advice and have a flag in the config file to specify wether a slash is required or not. If anyone comes across a solution where this is not needed, please share it. 

What do you think about this approach?

**Comment by fgalan** [comment]
Sounds good to me... although I'd need to see the pull request implementing this to provide more precise feedback. Thanks!

**Comment by jmezzera** [comment]
Is there a standard procedure for developing and creating PR for this module? The best I could find is the one in [readTheDocs](https://fiware-iotagent-ul.readthedocs.io/en/latest/usermanual/index.html#development-documentation)?

 Whats the setup needed for testing? Before any changes, I ran the tests and got errors, mostly connection refused to CB (192.168.1.1, which, of course, I don't have anything listening there). Am I supposed to have a CB running on that IP? 

Sorry for my ignorance.

**Comment by fgalan** [comment]
I'd recommend to have a look at .travis.yml file in the repository root. The same procedure that Travis does to check if a PR is ok should be done in local before submitting the PR. Maybe some docker is needed to be up and running (MQTT broker?).

**Comment by fgalan** [comment]
Solved by (not in this repo, but in IOTA's repos):

* PR https://github.com/telefonicaid/iotagent-ul/pull/429
* PR https://github.com/telefonicaid/iotagent-json/pull/481
