### ISSUE TITLE
Support client_credentials grant_type for oauth2

### ISSUE THREAD

**Issue by vraybaud** [telefonicaid/iotagent-node-lib#872]
Today for Oauth2 authentication to a context broker, only refresh_token grant_type is supported.
It would be nice to also support the grant_type client_credentials: https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/

Is there any reason this is not supported yet?

**Comment by fgalan** [comment]
I think that @chicco785 was the one implementing the OAuth2 stuff (I don't remember exactly... sorry @chicco785 if this is not the case ;).

Maybe he can provide more information on this.

**Comment by chicco785** [comment]
refresh_token is a very secure way (you can invalidate tokens without compromising either user either client credentials), that's the only reason afaik

**Comment by bobeal** [comment]
I have one question about this: even if a `refresh_token` is long-lived (I've seen expiration policies ranging from 60 days to 1 year), it will eventually expire.

To handle this, we are regularly and manually issuing a PUT request on the /iot/services endpoint to update the stored refresh_token with a fresh new one.

Is this the correct way of doing it?

**Comment by chicco785** [comment]
@bobeal i think it's a good approach :) alternative you need to look for an OIDC implementation that allows for not expiring tokens

**Comment by bobeal** [comment]
Thanks @chicco785 for your answer. We are using Keycloak, there should be a way to configure this ...

PS: @vraybaud is no longer working at EGM (and so, no longer working on IoT Agents), so I think you can close this issue.

**Comment by fgalan** [comment]
> PS: @vraybaud is no longer working at EGM (and so, no longer working on IoT Agents), so I think you can close this issue.

Closed.
