### ISSUE TITLE
Listing service groups returns only a single service group

### ISSUE THREAD

**Issue by dberenguer** [telefonicaid/iotagent-node-lib#894]
**Version 1.10.0**

This documentation:
https://fiware-tutorials.readthedocs.io/en/latest/iot-agent/index.html#service-group-crud-actions

Describes the API call to get the list of service groups available under a service path:

REQUEST:
```
curl -X GET \
  'http://localhost:4041/iot/services' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /'
```

RESONSE:
```
{
    "_id": "5b07b2c3d7eec57836ecfed4",
    "subservice": "/",
    "service": "openiot",
    "apikey": "4jggokgpepnvsb2uv4s40d59ov",
    "resource": "/iot/d",
    "attributes": [],
    "lazy": [],
    "commands": [],
    "entity_type": "Thing",
    "internal_attributes": [],
    "static_attributes": []
}
```

However both the documentation and our tests result in the UL agent returning a single object (service group) instead of a list.

Is this the normal behaviour? How should we proceed in order to get the list of service groups?

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/893
