### ISSUE TITLE
Replace '':" by "-" or "_" for default entity_name (autoprovisioned devices, provisioned devices without entity_name) to be DB friendly

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#944]
Default `entity_name` for a device autoprovisioned (or provisioned device without entity_name) includes `:` in entity_name: `<device_type>:<device_id>`

That characters is often bad idea for default datatype of databases (alphanumeric strings)

Maybe this default separator should be configured per iota/service

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/iotagent-node-lib/blob/8b821e9d50addc9dd8a60e1ddb10592cfa3dd692/lib/services/devices/deviceService.js#L732

**Comment by fgalan** [comment]
PR #949 has been merged. Maybe this issue can be closed? Or is there something pending?
