### ISSUE TITLE
analize/ensure ngsiv2 + options=upsert is used to create/update entities

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#956]

**Comment by AlvaroVega** [comment]
Upsert is used to create devices:
https://github.com/telefonicaid/iotagent-node-lib/blob/e85304dd257addcfac0f9ceaddf8d1e9ddf82463/lib/services/devices/devices-NGSI-v2.js#L213-L226

**Comment by AlvaroVega** [comment]
But is not using upsert when update an entity:
https://github.com/telefonicaid/iotagent-node-lib/blob/e85304dd257addcfac0f9ceaddf8d1e9ddf82463/lib/services/devices/devices-NGSI-v2.js#L270-L280

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1111 (and associated PRs in IOTA repos: https://github.com/telefonicaid/iotagent-ul/pull/615 and https://github.com/telefonicaid/iotagent-json/pull/732)
