### ISSUE TITLE
Mixed mode implementation breaks the code of the IOTAs using iotagent-node-lib

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-node-lib#963]
After merging the "mixed mode" NGSI-LD related PR https://github.com/telefonicaid/iotagent-node-lib/pull/947, the code of the IOTAs using iotagent-node-lib got broken.

It seems that PR removes a function `checkNgsi2()` that IOTAs code needs.

An "emergency fix" was done to recover the CI e2e in PRs #957 and #959 (and also a little comment addition in #962). However, a proper fix needs to be done (with the current solution I'm not sure if the mixed mode will work at all).

We need the contributors of NGSI-LD functionality to take care of this and provide a proper fix, please.

(This issue is created in the iotagent-node-lib repository as "common place" for IOTAs, although probably IOTAs code also need to be modified)

CC: @jason-fox

**Comment by jason-fox** [comment]
According to the `checkNgsi2()` method documentation:

> It checks if the configuration file states the use of NGSIv2. Returns the supported NGSI format

What precisely does this mean? Prior to NGSI-LD `checkNgsi2()` returned a boolean `true` if the operation defined in `config.js` was not NGSI-v1.  This was used for legacy checks and frequently resulted in  `if ... then .. else` clauses before I refactored the NGSI-v1, NGSI-v2 and NGSI-LD  subclasses.

With NGSI-LD added to the codebase does `checkNgsi2()` mean:

-  _I am configured  in pure **NGSI-v2** mode_?  i.e. `true` for **NGSI-v2** only
-  _I am capable of parsing  **NGSI-v2** requests_?  i.e. `true` for **NGSI-v2** or **mixed**
-  _I am not running in **NGSI-v1** legacy mode_?  This is currently describe as `isCurrentNgsi()` 

Or is more info required like `checkNgsiLD(typeInformation)` where *mixed* mode may give `true` or `false` dependent upon the configuration of the device.

**Comment by fgalan** [comment]
`checkNgsi2()` was based on the static setting in `config.js` and probably it doesn't have sense after the changes done in PR #947.

This issue is not about recovering `checkNgsi2()` as *it was*. It is about to align IOT Agents implementation with the library API changes done in PR #947, as that PR breaks the library-usercode API. If at the end `checkNgsi2()` is not needed because the IOT Agents are now using the new functions (`ngsiVersion()`, `isCurrentNgsi()`, etc.), that's also fine and `checkNgsi2()` can be removed at the end.

**Comment by jason-fox** [comment]
So this is a request to update which repos exactly? Where is `checkNgsi2()` used external?

**Comment by jason-fox** [comment]
Ahh got it - like in IoTAgent JSON:

```javascript
if (attribute === constants.TIMESTAMP_ATTRIBUTE) {
        if (iotAgentLib.configModule.checkNgsi2()) {
            return constants.TIMESTAMP_TYPE_NGSI2;
        }
        return constants.TIMESTAMP_TYPE;
    }
```

This should be `isCurrentNgsi()`

**Comment by fgalan** [comment]
> So this is a request to update which repos exactly? Where is `checkNgsi2()` used externally?

Main IOTAs (and IOTA Manager) should be reviewed for `checkNgsi2()` usages. I mean:

* https://github.com/telefonicaid/iotagent-json
* https://github.com/telefonicaid/iotagent-ul
* https://github.com/telefonicaid/sigfox-iotagent
* https://github.com/telefonicaid/lightweightm2m-iotagent
* https://github.com/telefonicaid/iotagent-manager

**Comment by jason-fox** [comment]
Unlike the other agents Sigfox has no timestamp support using `checkNgsi2()`
IoT Agent Manager has no instances of `checkNgsi2()`

**Comment by fgalan** [comment]
The following links can be used to check usage of `checkNgsi2` in every repository:

* https://github.com/telefonicaid/iotagent-json/search?q=checkNgsi2
* https://github.com/telefonicaid/iotagent-ul/search?q=checkNgsi2
* https://github.com/telefonicaid/lightweightm2m-iotagent/search?q=checkNgsi2
* https://github.com/telefonicaid/sigfox-iotagent/search?q=checkNgsi2
* https://github.com/telefonicaid/iotagent-manager/search?q=checkNgsi2

After merging the PRs, all them return 0 results, so all the IOTA Lib "users" have been fixed.

With regards to the unmerged PR https://github.com/telefonicaid/iotagent-node-lib/pull/965, I think that a better approach would be just to drop the `checkNgsi2()` function from the iotagent-node-lib API. Given that all the library users have been already adapted this function is no longer needed.

@jason-fox what do you think?

**Comment by jason-fox** [comment]
Sure, no problem, I can remove it. Although the bigger issue is that what is considered as the  full external interface of the library is not correctly documented.  There is a growing divergence between what is listed [here](https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/fiware-iotagent-lib.js#L304-L372) and technically accessible and what is listed in the [docs][https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/usermanual.md#function-reference] as accessible functions.

The fact that `config` is exposed implies that an method in `commonConfig.js` could be used externally - it would make a lot more sense to restrict this to a smaller set of methods on `fiware-iotagent-lib.js` only.

**Comment by fgalan** [comment]
After merging PR https://github.com/telefonicaid/iotagent-node-lib/pull/965 I think this issue can be closed.

With regards to your comments on documentation of the external interface, I fully agree. Documentation should be reviewed in order to match exactly that external interface (and, once done, be very careful with new PRs modifying that external interface to ensure the documentation is modified accordingly).
