### ISSUE TITLE
Question: How/when to remove NGSI-v1 from the library?

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-node-lib#966]
I know **NGSI-v1** is deprecated, but at some point I assume **NGSI-v1** support is to be dropped. Just to ensure things don't get lost here is a reminder for future development:

1) [x] Delete NGSI-v1 modules refactored out by #842 
2) [x] Delete NGSI-v1 unit tests - look for prefix _NGSI-v1_
3) [ ] Look for instances of `isCurrentNgsi()` across current  IoT Agent codebases - see #963 - remove NGSI-v1 path of execution
4) [x]  Fix documentation (moving examples to NGSI-v2, remove NGSI-v1 specific topics, etc.)
5) [x]  Do a final check (grep-wise) for “NGSIv1”, “NGSI-v1”, “NGSI v1”, "v1", etc. to remove any additional leftover that could remain after the accomplished above steps

### Questions

- Anything missing with this course of action?
- This would of course be a **breaking change** - would the package move to `3.0.0`?
- Should this update be aligned with full **NGSI-LD** support being completed?

**Comment by jason-fox** [comment]
Following on from: https://github.com/telefonicaid/iotagent-ul/pull/460#discussion_r553299500 and `isCurrentNGSI()` changes

Removing stuff from the Lib will be easy, but there will need to be testing on the various downstream projects. Should there be a release of the IoT Agents before attempting the removal?

**Comment by fgalan** [comment]
We think removing deprecated NGSI-v1 from IOTAs would be a good idea. Please find feedback below.

> Anything missing with this course of action?

We would suggest to add two extra items to the list of checkboxes: 

- [ ] Fix documentation (moving examples to NGSI-v2, remove NGSI-v1 specific topics, etc.)
- [ ] Do a final check (grep-wise) for “NGSIv1”, “NGSI-v1”, “NGSI v1”, "v1", etc. to remove any additional leftover that could remain after the accomplished above steps

> This would of course be a **breaking change** - would the package move to `3.0.0`?

Makes sense. In IOTAs probably we should to the same and move to 2.0.0. 

> Should this update be aligned with full **NGSI-LD** support being completed?

We think they are independent things. I mean, NGSI-v1 removal can be started without waiting for NGSI-LD support being completed.

> Should there be a release of the IoT Agents before attempting the removal?

We think it would be a good idea. Although the PRs can be started now, they will be merged after a new release had been done. However, I think that new release will be done soon.

**Comment by jason-fox** [comment]
Related to #970  - a potential timetable for this is as follows:

1) In the current release 2.14.0 NGSI-v1 is deprecated but still supported.
2) In the next release 2.15.0  NGSI-v1 is deprecated but still supported. (released before May 2021)
3) NGSI-v1 can then be removed - **without class refactoring**

**Comment by fgalan** [comment]
I'd say that after merging PR #995 and all the related others in IOTAs repos this issue is complete. There are some checkboxes above not marked, but probably they are completed tasks.

@jason-fox could you have a look and close this issue if you think everything is completed, please?

**Comment by jason-fox** [comment]
This task is completed.
