### ISSUE TITLE
Problem with running tests related to project

### ISSUE THREAD

**Issue by marcinbudny** [telefonicaid/iotagent-node-lib#97]
I'm having issues with running tests for the IoT agent library. Here's error description from mocha:

```
1) MongoDB Group Registry test When a new device group creation request arrives should store the service information from the headers into the DB:
 Uncaught TypeError: Cannot read property 'length' of undefined
  at processResults (/home/marcin/iotagent-node-lib/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
  at /home/marcin/iotagent-node-lib/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
  at /home/marcin/iotagent-node-lib/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
  at b (domain.js:183:18)
  at /home/marcin/iotagent-node-lib/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
  at b (domain.js:183:18)
  at Server.Base._callHandler (/home/marcin/iotagent-node-lib/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
  at /home/marcin/iotagent-node-lib/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
  at MongoReply.parseBody (/home/marcin/iotagent-node-lib/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
  at null.<anonymous> (/home/marcin/iotagent-node-lib/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
```

My environment is:
* clean install of Ubuntu Server 14.04
* fresh clone of repository
* Mongo 3.0.4 installed as specified [here](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/)
* node 0.10.25 and npm 1.3.10
* `npm install` and `npm install -g grunt`
* `grunt test`

The problem is also occuring on Windows.

What might be the problem?

**Comment by dmoranj** [comment]
The first thing you should try is to use a lower version of MongoDB. We are working with 2.4 and 2.6 versions, so maybe there is some incompatibility between the version of Mongoose and the one of MongoDB. I'll try to check it myself. By the way, what version of Node.js are you using?

**Comment by marcinbudny** [comment]
Thank you for quick reply. I'll check the lower mongo version as soon as I have some time and will let you know.
I have already updated the issue description with node (0.10.25) and npm (1.3.10) versions.

**Comment by marcinbudny** [comment]
As I mentioned, I also tried to run the tests on Windows. Node version was 0.12.4

**Comment by dmoranj** [comment]
The Node version in Ubuntu is the appropriate one. You should stick to 0.10.x for the moment, but that shouldn't be a problem really (some of the IoTAgents we are developing are using 0.12.x; for instance, the Sigfox one). I hope I have some time tomorrow to fix some issues in the agents, and I'll try to reproduce this bug.

**Comment by marcinbudny** [comment]
Hi Daniel,
After downgrading to mongo 2.6.10, the tests pass. 
Do you plan to support mongo 3 any time soon?

**Comment by dmoranj** [comment]
Sorry, I missed this message. It's in the roadmap, but I don't think it will be supported in the short term, as we have some more urgent issues. I will close this issue and open a new one, concerning the support of Mongo 3.
