### ISSUE TITLE
PUT  to /iot/services?apikey=<apikey> returns 204 even if no valid body is provided

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#973]
API https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/api.md#put-iotservices

example of body (note that this body is valid for iotagent-manager but not for iotagent)
```
{"services":[{"apikey":"rabp0c3vzt6jydn5wer9q7txb","timestamp":true,"expressionLanguage":"jexl","attributes":[],"entity_type":"thing","protocol":["IoTA-JSON"],"static_attributes":[],"commands":[],"description":"myjson"}]}
```

**Comment by AlvaroVega** [comment]
Check if group is tainted before save it: 
https://github.com/telefonicaid/iotagent-node-lib/blob/fb64ec876f8ac33e65a1105528fb3d1ca31896c5/lib/services/groups/groupRegistryMongoDB.js#L280-L284

**Comment by Sunny-NEC** [comment]
@AlvaroVega 
I am trying to reproduce this issue in my local system and executing the PUT request on invalid body. 
**URL using in PUT Request :**
http://localhost:4041/iot/services?apikey=rabpoc3vzt6jydn5wer9q7txb
**Body :**
{"services":[{"apikey":"rabp0c3vzt6jydn5wer9q7txb","timestamp":true,"expressionLanguage":"jexl","attributes":[],"entity_type":"thing","protocol":["IoTA-JSON"],"static_attributes":[],"commands":[],"description":"myjson"}]}

**OUTPUT:**
400 bad request

It is working fine in my local system (if no valid body provided). Please let me know what is your concern.  
Please find the screenshot of PUT Request.

 
![image](https://user-images.githubusercontent.com/75657997/141421919-564f7157-c263-46d9-834e-27056cade942.png)

If anything is left from my end please let me know.

**Comment by AlvaroVega** [comment]
Maybe this issue has been fixed by another fix or refactor and we can close it.

**Comment by fgalan** [comment]
I agree with @AlvaroVega suggestion. Thanks @Sunny-NEC for testing it!
