### ISSUE TITLE
MQTT commands sent twice.

### ISSUE THREAD

**Issue by jandres6579** [telefonicaid/iotagent-node-lib#982]
I configured the iotagent-json over MQTT and orion-LD broker. After provisioning a device with an actuator (for instance "start") and monitoring MQTT messages... I see the "start" command was sent twice to the device. I attach MQTT monitor and iotagent-json log where iotagen-node-lib seems work wrong.

$ mosquitto_sub -h localhost -p 1884 -t "#" -v | xargs -d$'\n' -L1 bash -c 'date "+%Y-%m-%d %T.%3N $0"'
**2021-01-28 11:11:52.193 /1234/device001/cmd {"start":" "}
2021-01-28 11:11:52.200 /1234/device001/cmd {"start":" "}**

Do you obtain the same result?

I put the logs of iot-agent, I think it's strange the red lines, it seems two threads after they. (59f99ac1-4bf2-420a-867a-3a65324e6c27, 4a68b7ab-699d-4707-ac4e-7d93f10e10e8).

fiware-iot-agent | time=2021-01-28T10:23:01.121Z | lvl=DEBUG | corr=59f99ac1-4bf2-420a-867a-3a65324e6c27 | trans=59f99ac1-4bf2-420a-867a-3a65324e6c27 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=openiot | subsrv=/ | msg=Request for path [/ngsi-ld/v1/entities/urn:ngsi-ld:Device:001/attrs/start] from [localhost:4041] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.121Z | lvl=DEBUG | corr=59f99ac1-4bf2-420a-867a-3a65324e6c27 | trans=59f99ac1-4bf2-420a-867a-3a65324e6c27 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=openiot | subsrv=/ | msg=Body:
fiware-iot-agent |
fiware-iot-agent | {
fiware-iot-agent |     "type": "Property",
fiware-iot-agent |     "value": " "
fiware-iot-agent | }
fiware-iot-agent |
fiware-iot-agent |  | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.121Z | lvl=DEBUG | corr=59f99ac1-4bf2-420a-867a-3a65324e6c27 | trans=59f99ac1-4bf2-420a-867a-3a65324e6c27 | op=IoTAgentNGSI.ContextServer-LD | from=n/a | srv=openiot | subsrv=/ | msg=Handling LD update from [localhost:4041] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.121Z | lvl=DEBUG | corr=59f99ac1-4bf2-420a-867a-3a65324e6c27 | trans=59f99ac1-4bf2-420a-867a-3a65324e6c27 | op=IoTAgentNGSI.ContextServer-LD | from=n/a | srv=openiot | subsrv=/ | msg={
fiware-iot-agent |     "type": "Property",
fiware-iot-agent |     "value": " "
fiware-iot-agent | } | comp=IoTAgent

**fiware-iot-agent | time=2021-01-28T10:23:01.121Z | lvl=DEBUG | corr=59f99ac1-4bf2-420a-867a-3a65324e6c27 | trans=59f99ac1-4bf2-420a-867a-3a65324e6c27 | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=openiot | subsrv=/ | msg=Looking for device with name [urn:ngsi-ld:Device:001]. | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.121Z | lvl=DEBUG | corr=59f99ac1-4bf2-420a-867a-3a65324e6c27 | trans=59f99ac1-4bf2-420a-867a-3a65324e6c27 | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=openiot | subsrv=/ | msg=Looking for device with name [urn:ngsi-ld:Device:001]. | comp=IoTAgent**

fiware-iot-agent | time=2021-01-28T10:23:01.123Z | lvl=DEBUG | corr=**4a68b7ab-699d-4707-ac4e-7d93f10e10e8** | trans=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"openiot","subservice":"/","type":"Device"} | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.124Z | lvl=DEBUG | corr=**8fb809ce-92b4-45ea-bcd5-eca11f5df9b7** | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"openiot","subservice":"/","type":"Device"} | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.125Z | lvl=DEBUG | corr=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | trans=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type","apikey"]] not found: [{"service":"openiot","subservice":"/","type":"Device"}] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.125Z | lvl=DEBUG | corr=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | trans=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | op=IoTAgentNGSI.DeviceService | from=n/a | srv=n/a | subsrv=n/a | msg=deviceData before merge with conf: {"lazy":[],"active":[{"object_id":"s","name":"isOpen","type":"boolean"}],"commands":[{"name":"start","type":"command","object_id":"start"},{"name":"stop","type":"command","object_id":"stop"}],"staticAttributes":[{"name":"name","type":"Text","value":"Device:001 provision"}],"subscriptions":[],"_id":"60128db26b494edfac0a0a9f","creationDate":"2021-01-28T10:10:58.456Z","id":"device001","type":"Device","name":"urn:ngsi-ld:Device:001","service":"openiot","subservice":"/","registrationId":"urn:ngsi-ld:ContextSourceRegistration:60128db2346dfb80630f61c5","internalId":null,"protocol":"MQTT_JSON","transport":"MQTT","explicitAttrs":false} | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.125Z | lvl=DEBUG | corr=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | trans=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | op=IoTAgentNGSI.DeviceService | from=n/a | srv=n/a | subsrv=n/a | msg=deviceData after merge with conf: {"lazy":[],"active":[{"object_id":"s","name":"isOpen","type":"boolean"}],"commands":[{"name":"start","type":"command","object_id":"start"},{"name":"stop","type":"command","object_id":"stop"}],"staticAttributes":[{"name":"name","type":"Text","value":"Device:001 provision"}],"subscriptions":[],"_id":"60128db26b494edfac0a0a9f","creationDate":"2021-01-28T10:10:58.456Z","id":"device001","type":"Device","name":"urn:ngsi-ld:Device:001","service":"openiot","subservice":"/","registrationId":"urn:ngsi-ld:ContextSourceRegistration:60128db2346dfb80630f61c5","internalId":null,"protocol":"MQTT_JSON","transport":"MQTT","explicitAttrs":false,"internalAttributes":null} | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.125Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type","apikey"]] not found: [{"service":"openiot","subservice":"/","type":"Device"}] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.125Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.DeviceService | from=n/a | srv=n/a | subsrv=n/a | msg=deviceData before merge with conf: {"lazy":[],"active":[{"object_id":"s","name":"isOpen","type":"boolean"}],"commands":[{"name":"start","type":"command","object_id":"start"},{"name":"stop","type":"command","object_id":"stop"}],"staticAttributes":[{"name":"name","type":"Text","value":"Device:001 provision"}],"subscriptions":[],"_id":"60128db26b494edfac0a0a9f","creationDate":"2021-01-28T10:10:58.456Z","id":"device001","type":"Device","name":"urn:ngsi-ld:Device:001","service":"openiot","subservice":"/","registrationId":"urn:ngsi-ld:ContextSourceRegistration:60128db2346dfb80630f61c5","internalId":null,"protocol":"MQTT_JSON","transport":"MQTT","explicitAttrs":false} | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.125Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.DeviceService | from=n/a | srv=n/a | subsrv=n/a | msg=deviceData after merge with conf: {"lazy":[],"active":[{"object_id":"s","name":"isOpen","type":"boolean"}],"commands":[{"name":"start","type":"command","object_id":"start"},{"name":"stop","type":"command","object_id":"stop"}],"staticAttributes":[{"name":"name","type":"Text","value":"Device:001 provision"}],"subscriptions":[],"_id":"60128db26b494edfac0a0a9f","creationDate":"2021-01-28T10:10:58.456Z","id":"device001","type":"Device","name":"urn:ngsi-ld:Device:001","service":"openiot","subservice":"/","registrationId":"urn:ngsi-ld:ContextSourceRegistration:60128db2346dfb80630f61c5","internalId":null,"protocol":"MQTT_JSON","transport":"MQTT","explicitAttrs":false,"internalAttributes":null} | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.125Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentJSON.Commands | from=n/a | srv=n/a | subsrv=n/a | msg=Handling MQTT command for device [urn:ngsi-ld:Device:001] in service [openiot - /] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.125Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=openiot | subsrv=/ | msg=Looking for device with name [urn:ngsi-ld:Device:001]. | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.127Z | lvl=DEBUG | corr=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | trans=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | op=IoTAgentJSON.Utils | from=n/a | srv=n/a | subsrv=n/a | msg=Getting effective API Key | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.127Z | lvl=DEBUG | corr=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | trans=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"openiot","subservice":"/"} | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type","apikey"]] not found: [{"service":"openiot","subservice":"/"}] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentJSON.Utils | from=n/a | srv=n/a | subsrv=n/a | msg=Using default API Key: 1234 | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentJSON.Commands | from=n/a | srv=n/a | subsrv=n/a | msg=Sending command execution to device [1234] with apikey [device001] and payload [{"type":"command","value":" ","name":"start"}]  | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Creating execution for function [executeCommand] and protocol [MQTT] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Binding found for function [executeCommand] and protocol [MQTT] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IOTAJSON.MQTT.Binding | from=n/a | srv=n/a | subsrv=n/a | msg=Sending command execution to [/1234/device001/cmd] with payload [{"start":" "}] and with mqtt options [{"qos":0,"retain":false}] | comp=IoTAgent

**fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=INFO | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IOTAJSON.MQTT.Binding | from=n/a | srv=n/a | subsrv=n/a | msg=Cmd:
fiware-iot-agent |  "{\"start\":\" \"}" was sent to the device /1234/device001/cmd with mqtt options {"qos":0,"retain":false} | comp=IoTAgent**

fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentJSON.Commands | from=n/a | srv=n/a | subsrv=n/a | msg=Handling MQTT command for device [urn:ngsi-ld:Device:001] in service [openiot - /] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.128Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBDeviceRegister | from=n/a | srv=openiot | subsrv=/ | msg=Looking for device with name [urn:ngsi-ld:Device:001]. | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.130Z | lvl=DEBUG | corr=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | trans=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | op=IoTAgentJSON.Utils | from=n/a | srv=n/a | subsrv=n/a | msg=Getting effective API Key | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.130Z | lvl=DEBUG | corr=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | trans=4a68b7ab-699d-4707-ac4e-7d93f10e10e8 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type","apikey"] with queryObj {"service":"openiot","subservice":"/"} | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.134Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type","apikey"]] not found: [{"service":"openiot","subservice":"/"}] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.134Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentJSON.Utils | from=n/a | srv=n/a | subsrv=n/a | msg=Using default API Key: 1234 | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.134Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentJSON.Commands | from=n/a | srv=n/a | subsrv=n/a | msg=Sending command execution to device [1234] with apikey [device001] and payload [{"type":"command","value":" ","name":"start"}]  | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.134Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Creating execution for function [executeCommand] and protocol [MQTT] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.134Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Binding found for function [executeCommand] and protocol [MQTT] | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.134Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IOTAJSON.MQTT.Binding | from=n/a | srv=n/a | subsrv=n/a | msg=Sending command execution to [/1234/device001/cmd] with payload [{"start":" "}] and with mqtt options [{"qos":0,"retain":false}] | comp=IoTAgent

**fiware-iot-agent | time=2021-01-28T10:23:01.134Z | lvl=INFO | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IOTAJSON.MQTT.Binding | from=n/a | srv=n/a | subsrv=n/a | msg=Cmd:
fiware-iot-agent |  "{\"start\":\" \"}" was sent to the device /1234/device001/cmd with mqtt options {"qos":0,"retain":false} | comp=IoTAgent**

fiware-iot-agent | time=2021-01-28T10:23:01.134Z | lvl=DEBUG | corr=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | trans=8fb809ce-92b4-45ea-bcd5-eca11f5df9b7 | op=IoTAgentNGSI.ContextServer-LD | from=n/a | srv=n/a | subsrv=n/a | msg=Update action from [localhost:4041] handled successfully. | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:01.135Z | lvl=DEBUG | corr=59f99ac1-4bf2-420a-867a-3a65324e6c27 | trans=59f99ac1-4bf2-420a-867a-3a65324e6c27 | op=IoTAgentNGSI.DomainControl | from=n/a | srv=openiot | subsrv=/ | msg=response-time: 14 | comp=IoTAgent
fiware-iot-agent | time=2021-01-28T10:23:05.429Z | lvl=DEBUG | corr=8e8de29a-5004-46f1-ae9b-fd6799d34654 | trans=8e8de29a-5004-46f1-ae9b-fd6799d34654 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=n/a | subsrv=n/a | msg=Request for path [/iot/about] from [localhost:4041] | comp=IoTAgent

**Comment by AlvaroVega** [comment]
DId you tried with qos = 2 ?

**Comment by fgalan** [comment]
Are you sure you are not running two instances of IOTA-JSON? What does `ps ax | grep iota` tell? Maybe you are using an HA setup with redundant instances?

**Comment by jandres6579** [comment]
> DId you tried with qos = 2 ?

The same.

**Comment by jandres6579** [comment]
> Are you sure you are not running two instances of IOTA-JSON? What does `ps ax | grep iota` tell? Maybe you are using an HA setup with redundant instances?

E$ ps ax | grep iota
 5905 pts/3    S+     0:00 grep --color=auto iota
32141 ?        Ssl    0:01 node /opt/iotagent-json/bin/iotagent-json --  config.js

**Comment by jandres6579** [comment]
Here my docker-compose, and curl requests (provisioning and invoke command):

version: "3.5"
services:

  # Orion is the context broker
  orion:
    image: fiware/orion-ld:0.6.1
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "${ORION_PORT}:${ORION_PORT}" # localhost:1026
    expose:
      - "${ORION_PORT}"
    command: -dbhost mongo-db -logLevel DEBUG -forwarding
    healthcheck:
      test: curl --fail -s http://orion:${ORION_PORT}/version || exit 1
      interval: 5s

  # IoT-Agent is configured for the JSON Protocol
  iot-agent:
    image: fiware/iotagent-json
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
    networks:
      - default
    expose:
      - "${IOTA_NORTH_PORT}"
      - "${IOTA_SOUTH_PORT}"
    ports:
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}" # localhost:4041
      - "${IOTA_SOUTH_PORT}:${IOTA_SOUTH_PORT}" # localhost:7896
    
    volumes:      
      - ./config.js:/opt/iotagent-json/config.js

    environment:
      - IOTA_CB_HOST=orion # name of the context broker to update context
      - IOTA_CB_PORT=${ORION_PORT} # port the context broker listens on to update context
      - IOTA_NORTH_PORT=${IOTA_NORTH_PORT}
      - IOTA_REGISTRY_TYPE=mongodb #Whether to hold IoT device info in memory or in a database
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_TIMESTAMP=true # Supply timestamp information with each measurement
      - IOTA_AUTOCAST=true # Ensure Ultralight number values are read as numbers not strings
      - IOTA_MONGO_HOST=mongo-db # The host name of MongoDB
      - IOTA_MONGO_PORT=${MONGO_DB_PORT} # The port mongoDB is listening on
      - IOTA_MONGO_DB=iotagentjson # The name of the database used in mongoDB
      - IOTA_HTTP_PORT=${IOTA_SOUTH_PORT} # The port used for device traffic over HTTP
      - IOTA_PROVIDER_URL=http://iot-agent:${IOTA_NORTH_PORT}
      - IOTA_DEFAULT_RESOURCE=/iot/json

      - IOTA_CB_NGSI_VERSION=ld # use NGSILD when sending updates for active attributes
      - IOTA_JSON_LD_CONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      - IOTA_FALLBACK_TENANT=openiot

    healthcheck:
      interval: 5s

  # Database
  mongo-db:
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "${MONGO_DB_PORT}"
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017
    networks:
      - default
    volumes:
      - mongo-db:/data
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s

  mosquitto:
    image: eclipse-mosquitto
    networks:
      - default
    ports:
      - "1884:1883"
      - "9002:9001"
    restart: unless-stopped

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  mongo-db: ~


*********************

curl --location --request POST 'http://localhost:4041/iot/devices' \
--header 'fiware-service: openiot' \
--header 'fiware-servicepath: /' \
--header 'Content-Type: application/json' \
--data-raw '{
 "devices": [
    {
        "device_id":   "device001",
        "entity_name": "urn:ngsi-ld:Device:001",
        "entity_type": "Device",
        "protocol": "MQTT_JSON",
        "transport": "MQTT",
        "timezone":    "Europe/Berlin",
        "attributes": [
            { "object_id": "s", "name": "isOpen", "type": "boolean" }
        ],
        "commands": [
            { "name": "start", "type": "command" },
            { "name": "stop", "type": "command" }
        ],
        "static_attributes": [
            {"name":"name", "type": "Text","value": "Device:001 provision"}
        ]
    }
  ]
}'

************************

curl --location --request PATCH 'http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:Device:001/attrs/start' \
--header 'Content-Type: application/json' \
--header 'NGSILD-Tenant: openiot' \
--header 'Link: <https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{ 

		"type": "Property", 
		"value": " " 

}'

**Comment by jandres6579** [comment]
@AlvaroVega @fgalan @jason-fox  It seems the error is here:
[](https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/northBound/contextServer-NGSI-LD.js)
in "handleUpdateNgsiLD" function:

[apply(async.map, **req.body**, apply(generateUpdateActionsNgsiLD, req)), reduceActions, async.series],

seems it is JSON but the sentence need an array, if I put

[apply(async.map, **[req.body]**, apply(generateUpdateActionsNgsiLD, req)), reduceActions, async.series],

seems it works. what do you think?

**Comment by fgalan** [comment]
Thanks for the report! I understand (by the _"seems it works"_) that you have tested for real (i.e. "hacking" the code) and it works. Is my understanding correct? Maybe you could do a pull request with the fix in that case.

The bug seems to be in NGSI-LD specific code (contextServer-NGSI-LD.js). It only appears NGSI-LD cases (i.e. using `ngsiVersion: 'ld'` in configuration or `ngsiVersion: 'mixed` in configuration + `"ngsiVersion": "ld"` in provision API)? Or it also happens in NGSIv2 cases (i.e. using `ngsiVersion: 'v2'` in configuration or `ngsiVersion: 'mixed` in configuration + `"ngsiVersion": "v2"` in provision API)?

**Comment by jandres6579** [comment]
@fgalan I have tested hacking code but, only once. My code is a fast way to test and I think it doesn't look very fancy to propose a pull request. :)

Regarding when it appears...
- I detected it only in 'ld'
- It doesn't appear with 'v2'. I hacked v2 code where I saw req.body.entities is an array. It inspired me to my proposal and worked.
- Regarding 'mixed'' I didn't test but I suppose the issue appears too, because the code is shared.

What do you think?

**Comment by jason-fox** [comment]
I've raised a test and fix here: https://github.com/telefonicaid/iotagent-node-lib/pull/985

**Comment by fgalan** [comment]
Having merged the PR, I understand this issue can be closed. Thanks!
