### ISSUE TITLE
Attributes/commands removed after device provisioning

### ISSUE THREAD

**Issue by jandres6579** [telefonicaid/iotagent-node-lib#983]
If I run iotagent-ul or iotagent-json over NGSI-LD and provisioning a device with attributes and/or commands. When the device sends the first message, NGSI-LD context broker, for instance orion-LD removes all attributes/commands from the broker except are included in this first message... seems iotagent-node-lib/lib/services/ngsi/entities-NGSI-LD.js files is wrong and "/ngsi-ld/v1/entityOperations/upsert" must be modified to "/ngsi-ld/v1/entityOperations/upsert/?options=update".

**Comment by fgalan** [comment]
In CC people involved in NGSI-LD development in the case they can provide help: @jason-fox @bobeal

**Comment by jandres6579** [comment]
> In CC people involved in NGSI-LD development in the case they can provide help: @jason-fox @bobeal

I see this issue @jason-fox before open the issue and he said to me:
---
This was a bug in the IoT Agent Node lib - it was discovered here: https://github.com/telefonicaid/iotagent-node-lib/pull/888 and fixed in a PR:
https://github.com/telefonicaid/iotagent-node-lib/pull/924
---

If I access to https://github.com/telefonicaid/iotagent-node-lib/pull/924/file, I see "?options=update" was added to lib/services/devices/devices-NGSI-LD.js file. But now I see in another file https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/ngsi/entities-NGSI-LD.js that ?options=update was not added to sendUpdateValueNgsiLD function.

**Comment by jason-fox** [comment]
There is no problem in adding `?options=update` in entities-NGSI-LD.js and it would make sense:

Open PR here: https://github.com/telefonicaid/iotagent-node-lib/pull/984
