### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by tstorek** [telefonicaid/iotagent-node-lib#994]
hello,

the documentation says that the loglevel could be retrieved by 'PUT' but it is rather a 'GET'

Cheers

**Comment by AlvaroVega** [comment]
@tstorek could you please provide a link to that documentation?

**Comment by fgalan** [comment]
@tstorek maybe you could even do a pull request with the fix itself if you want (it is just to change a word :)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1422
